### ISSUE TITLE
Remove tracker.webtorrent.io from default torrents

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent-desktop#1017]
`tracker.webtorrent.io` is gone, but the default torrent files still include it. Let's save some connection attempts and confusing error logs and remove it.

**Comment by chovy** [comment]
I still can't get webtorrent to work even on torrents with seeders.

The cli works fine (starts downloading right away).

The only 3 websocket trackers I've found all say "pending" when trying to connect.

http://i.imgur.com/TrWjcUn.png

Is there any other solution? It seems like the basic functionality doesn't work.

**Comment by feross** [comment]
@chovy In the future, please open a new issue instead of posting your questions into an unrelated issue.

That said, the "pending" status you see on websocket connections is normal. That's just how Chrome shows WebSocket connections. If you actually click on the line and go to the Frames tab, you can see the data being sent to the tracker:

<img width="621" alt="screen shot 2017-03-06 at 1 46 46 pm" src="https://cloud.githubusercontent.com/assets/121766/23631484/8b10ff74-0273-11e7-88a6-bb9c154f5f78.png">

If you're trying to download a torrent that is only seeded by normal torrent peers (TCP), then you will be unable to do so unless you're using a client that supports TCP. Right now, that's WebTorrent Desktop, `webtorrent-cli`, and `webtorrent-hybrid`. If you're using webtorrent in the browser, you're out of luck until there are more webtorrent peers in the world.

**Comment by chovy** [comment]
Gotcha. I got it working without a firewall using webtorrent-hybrid -- I posted https://github.com/feross/webtorrent-hybrid/issues/25 here as it seems relevant to the issue I'm having. Just need to figure out how to allow iptables to let traffic in for webtorrent webrtc

**Comment by littlepig2013** [comment]
I still can't get it work if I do not specify a torrent. Could you provide any available torrent?

**Comment by bluefchen** [comment]
the same bug in my WebTorrent desktop.
I remove all the default tracker list . and just add my local tracker.
but there are still 3 tracker in the torrent file:
wss://tracker.btorrent.xyz
wss://tracker.fastcast.nz
wss://tracker.openwebtorrent.com

**Comment by raspher** [comment]
is this issue solved ?

**Comment by feross** [comment]
@raspher Sent a PR to fix it: https://github.com/webtorrent/webtorrent-desktop/pull/1838
