### ISSUE TITLE
0.17.1 Mac doesn't play in VLC

### ISSUE THREAD

**Issue by ethaniel** [webtorrent/webtorrent-desktop#1019]
I've noticed this for a few versions now. Stuff stopped playing my VLC player. When I click "play in vlc" in webtorrent, VLC opens and I see the movie entry in the playlist, but when I click "play" in VLC nothing happens. 

I have to open the downloading file directly in VLC to play it. Perhaps Webtorrent-to-VLC stream is somehow broken?

**Comment by feross** [comment]
What OS and version? Are there any logs in the developer console or webtorrent process?

Click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

If you don't see any errors, then please check in one more place! Click View > Developer > Show WebTorrent Process, select the Console tab and copy-paste all the text.

Being able to see that output would help us out very much. Thanks.

**Comment by feross** [comment]
- Also, is this happening for video or audio?

I'm going to do a release tonight that will fix some bad exceptions that *could* cause something like this. Would be great if you could test after the release is done, as well.
