### ISSUE TITLE
Cannot create a torrent without WebTorrent trackers

### ISSUE THREAD

**Issue by dcposch** [webtorrent/webtorrent-desktop#1024]
**What version of WebTorrent Desktop?** 0.17.2

**What operating system and version?** all

**What did you do?**

Drag any file onto the app. In the Create Torrent screen, delete all trackers from the announce list except the first one (`udp://tracker.openbittorrent.com:80`). Then, right-click the newly created torrent and select Save Torrent File As... Finally, use `parse-torrent` to inspect the resulting `.torrent` file.

**What did you expect to happen?**

You should see only one tracker in the announce list.

**What actually happened?**

You see four trackers in the announce list:

```
    "udp://tracker.openbittorrent.com:80",
    "wss://tracker.btorrent.xyz",
    "wss://tracker.fastcast.nz",
    "wss://tracker.openwebtorrent.com"
```

**Comment by feross** [comment]
This seems related to https://github.com/webtorrent/webtorrent-desktop/issues/881
