### ISSUE TITLE
WebTorrent buggy at system startup in Ubuntu

### ISSUE THREAD

**Issue by ghost** [webtorrent/webtorrent-desktop#1055]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
17.2

**What operating system and version?**
Ubuntu 16.04

**What did you do?**
Restarted computer.

**What happened?**
WebTorrent starts but only as a system process. You can't actually see the tray icon, nor can you see the program in the menu bar.

It also causes File manager to stop working altogether, which means I can't open folders or anything, until I kill all the WebTorrent processes in System monitor.

Everything is fine if I open WebTorrent normally, however. It's only when you have the 'launch at system startup' option that it starts to cause trouble.

**Comment by janat08** [comment]
yep, 100% cpu usage (slowly climbs up) till you can't quit, and then it looks like OS is bricked. Tried putting it to sleep and then waking up, it wouldn't even lite up the screen.

**Comment by kopy-kate** [comment]
Seems like a major issue that is preventing long-term use of WebTorrent really. I actually only use WebTorrent Desktop right now for all my downloads, I love it. It'll be just as good as transmission once the CPU issue is fixed.

**Comment by feross** [comment]
Adding a `bug` label so we can dig further into this issue. If anyone has additional ideas for how to solve this, please share.
