### ISSUE TITLE
Webtorrent is giving lag to macOS sierra 10.12

### ISSUE THREAD

**Issue by Shankymahajan** [webtorrent/webtorrent-desktop#1056]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Latest
**What operating system and version?**
MacOs seirra 10.12

Recently I'm facing issues with webtorrent . I'm not able to open  webtorrent because whenever I'm tart it .It makes my macbook lags a lot . After it I have to restart it . I faced this issue in linux mint cinnamon too but in cinnamon whenever it crashed it can restarted again but not in macOS .

**Comment by wwwfsamuel** [comment]
same here on osx 10.11.2
 most of the cpu is used by the web torrent helper 

[Sample of WebTorrent Helper.txt](https://github.com/feross/webtorrent-desktop/files/573608/Sample.of.WebTorrent.Helper.txt)
[Sample of WebTorrent.txt](https://github.com/feross/webtorrent-desktop/files/573609/Sample.of.WebTorrent.txt)

**Comment by mokas01** [comment]
WebTorrent Desktop : 0.18 (0.98.5)
same issue after upgrading to osx 10.12.4
After killing the process Webtorrent Helper (using 200% of the CPU), no log anymore
