### ISSUE TITLE
Download speed indicated in the UI is higher than it actually is

### ISSUE THREAD

**Issue by lachenmayer** [webtorrent/webtorrent-desktop#1062]
Not a major issue at all, I kinda like seeing my shitty internet speeds lifted a bit :P

**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.17.2 (0.97.2)

**What operating system and version?**
OS X 10.11.6

**What did you do?**
Download a torrent & checked the download speed

**What did you expect to happen?**

**What actually happened?**
Download speeds are indicated as roughly 3 times what MenuMeters indicates (more or less consistently).

![image](https://cloud.githubusercontent.com/assets/38614/19941623/c17f990a-a128-11e6-8a41-549b425b694c.png)

**Comment by feross** [comment]
I think this is what happens when WebTorrent is using a lot of CPU. @lachenmayer - next time this happens, can you check what the CPU utilization of the app is and share here? Thanks.
