### ISSUE TITLE
New Dialogs

### ISSUE THREAD

**Issue by zeke** [webtorrent/webtorrent-desktop#1064]
I see that WebTorrent is now using homemade dialogs:

![screen shot 2016-11-02 at 5 52 39 pm](https://cloud.githubusercontent.com/assets/2289/19978208/574e432a-a1b3-11e6-9581-7cf7f0653662.png)

Out of curiosity, what motivated the choice to use them? Some guesses:

- Easier to implement that native dialogs
- Stylistic flexibility
- Difficult to write automated tests for native Electron dialog behavior
- Something else?

**Comment by feross** [comment]
Hey @zeke! Sorry for the delay in responding to this. The reason we switched to homemade dialogs was that we needed a dialog that had an input field and I believe that Electron does not support `window.prompt()` which is the browser way of creating such a dialog.

You can see it in action here:

![screen shot 2018-05-10 at 5 42 09 pm](https://user-images.githubusercontent.com/121766/39900855-8e861d20-5479-11e8-9e36-7b898588dd41.png)

**Comment by zeke** [comment]
Thanks for following up. It looks like there are some userland implementations of prompt. Here's one: https://github.com/sperrichon/electron-prompt

That said, I don't think this needs to change in webtorrent. What you have now works just fine!

**Comment by feross** [comment]
💪
