### ISSUE TITLE
Display downloading info while playing in VLC

### ISSUE THREAD

**Issue by aurimus** [webtorrent/webtorrent-desktop#1070]
Can't see any info on torrents downloading while in VLC mode.

**Comment by feross** [comment]
Yeah, good idea. We should show the same basic info (download/upload speed, etc.) that we do when the torrent is playing within WebTorrent and it's stalled.

**Comment by cezar-carneiro** [comment]
I think it's a great idea, I felt the same need the first time i played a video... I will open a PR in a couple of days

**Comment by subins2000** [comment]
From #1814, it'd be also cool to show the bottom playback red line for progress. Some players like mine (smplayer) resets playback to 0 (some other players get stuck, VLC) when I seek to a position which hasn't been downloaded. With the red line, I can now know which places to correctly seek to.

**Comment by feross** [comment]
This is now fixed on `master` and will be in the next release.
