### ISSUE TITLE
Renaming idea

### ISSUE THREAD

**Issue by jimmywarting** [webtorrent/webtorrent-desktop#1078]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.17.2 (0.97.2)

**What operating system and version?**
OS X

**What did you do?**
Download a torrent

**What did you expect to happen?**
If a folder or a filename includes brackets then i would like everything inside of it including the brackets trimmed away. It's sometimes often I get torrents with `[www.example.com]` that are trying to advertise them self on other torrenting sites.
It's less annoying if they add it in the end but when they put it in the beginning and the only letters you can read is `[www.exam...` then it gets **** annoying cuz you don't know what it's

I would really like to have this as an option

**What actually happened?**
folder/files names are the same

**Comment by jimmywarting** [comment]
one reason i would really like to have this is so that plex can recordize what is a movie and what is a TV episode

**Comment by feross** [comment]
Thanks for the feature request!

WebTorrent Desktop values simplicity more than most torrent apps. This sometimes means saying 'No' to good ideas. We try to implement only the most important features that a torrent app needs and make those features as good as possible. We don't want the app to get overloaded with knobs and dials that may only benefit a small percentage of users.

That's not to say we won't ever add large new features. We support powerful features like instant streaming, dynamic piece prioritization, web peers (WebRTC), etc. but only when they have a clear benefit to a vast majority of users. See the [80-20 rule](https://en.wikipedia.org/wiki/Pareto_principle).

I don't think it makes sense to implement this feature right now. I hope this makes sense!
