### ISSUE TITLE
App priority

### ISSUE THREAD

**Issue by ethaniel** [webtorrent/webtorrent-desktop#1088]
WTD puts my macbook pro to a halt when it decides to rehash the torrents on start.
It needs to be set to lowest disk and processor priority and give away resources to other programs.

**Comment by feross** [comment]
This is one option, but the real solution I want to work toward is making webtorrent not try to do everything at once / as fast as possible. We need a queueing system of some sort, so we don't use all cores trying to go as fast as possible.

**Comment by SecT0uch** [comment]
Lookinf forward this feature

**Comment by feross** [comment]
Closing this in favor of this issue: https://github.com/webtorrent/webtorrent/search?q=cpu+is%3Aissue&type=Issues
