### ISSUE TITLE
The About window doesn't work properly

### ISSUE THREAD

**Issue by roccomuso** [webtorrent/webtorrent-desktop#1094]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
v0.17.2, this wasn't happening with the older version.
**What operating system and version?**
Ubuntu 16
**What did you do?**
Just opened the About window
**What did you expect to happen?**
See the about window with the version number.
**What actually happened?**
![screenshot from 2016-12-07 11-01-04](https://cloud.githubusercontent.com/assets/6730217/20963205/ca315926-bc6c-11e6-809b-c4be87f5085f.png)

**Comment by feross** [comment]
@roccomuso Can you try restarting the app and seeing if you can reproduce this? I want to see if it happens every time for you, or if it was just this once.

I've seen this happen once or twice before for no reason. I think it's an Electron bug.

**Comment by roccomuso** [comment]
@feross I've installed this last version also on another Ubuntu PC, same error. (I've updated from the Version 0.14.0 (0.96.4), that version was ok).
Even after several restart i see that error.

**Comment by feross** [comment]
@roccomuso That's really strange. Let's see if updating Electron (in the next WebTorrent Desktop release) fixes this problem. I can't think of what else it could be.

**Comment by feross** [comment]
Also, fwiw, it works fine for me:

<img width="536" alt="screen shot 2016-12-09 at 1 43 53 am" src="https://cloud.githubusercontent.com/assets/121766/21044466/f9235b4a-bdb0-11e6-99de-88aac822b329.png">

**Comment by roccomuso** [comment]
Confirmed, after a while the error is gone.
**Version 0.17.2 (0.97.2) (64-bit)**
