### ISSUE TITLE
Incorrect behavior on low disk space.

### ISSUE THREAD

**Issue by diimdeep** [webtorrent/webtorrent-desktop#1106]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.17.2

**What operating system and version?**
macOS Sierra

**What did you do?**
Trying to download torrent that exceeds available size on hard drive.

**What did you expect to happen?**
Some kind of visibility about not enough disk space.
Pause without starting download and don't preallocate disk space (pause not implemented?) 

**What actually happened?**
Webtorrent allocates maximum available space it can, and starts download believing that allocated space equals 100% of torrent, which is not. So when it downloads that part of, it reports to user 100% which is false. 

Update: Free space and restart help.

**Comment by aurimus** [comment]
+1

**Comment by aurimus** [comment]
Confirmed on Ubuntu 17.04. I don't think the preallocation part is correct. In my experience it marks the torrent 100% as soon as it runs out of space.
