### ISSUE TITLE
smi subtitle support

### ISSUE THREAD

**Issue by sundoufu** [webtorrent/webtorrent-desktop#1108]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.17.2

**What operating system and version?**
Windows 10

**What did you do?**
I went to open subtitles dialog

**What did you expect to happen?**
I can add smi subtitle files to streaming

**What actually happened?**
I coulndn't. only srt files were possible.

**Comment by feross** [comment]
I've never heard of this format before. Is it popular?

I found some more information here: https://en.wikipedia.org/wiki/SAMI

**Comment by ashe-sparcs** [comment]
I'm a Korean user. In Korea, smi format is very popular. If you have some spare time to work on this issue, adding this feature will make me very grateful.

**Comment by manixate** [comment]
VLC supports SMI files so you could use it as your player.

**Comment by hicom150** [comment]
Although it could be doable with something like [smi2vtt](https://github.com/nupamore/smi2vtt), I don't know if I would add more dependencies to webtorrent-desktop given that VLC supports perfectly SMI files 😅
