### ISSUE TITLE
Cannot add duplicate torrent on torrent resume

### ISSUE THREAD

**Issue by roccomuso** [webtorrent/webtorrent-desktop#1109]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
- WebTorrent v.0.17.2 (0.97.2) (64-bit)

**What operating system and version?**
- Ubuntu 16.04 LTS

**What did you do?**
- Trying to resume a torrent.

**What did you expect to happen?**
- The torrent being resumed

**What actually happened?**
- Popup saying: **Error: Cannot add duplicate torrent**

**Comment by feross** [comment]
Can you try to reproduce this error once more? But this time when it happens, click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

If you don't see any errors, then please check in one more place! Click View > Developer > Show WebTorrent Process, select the Console tab and copy-paste all the text.

Being able to see that output would help us out very much. Thanks.
