### ISSUE TITLE
Video stuttering during playback

### ISSUE THREAD

**Issue by maverickmax** [webtorrent/webtorrent-desktop#1114]
**What version of WebTorrent Desktop?** 
Version 0.17.2 (0.97.2) (32-bit)
**What operating system and version?**
Windows 10 pro
**What did you do?**
dragged and dropped a movie torrent and started streaming playback.
**What did you expect to happen?**
a smooth playback of the video file.
**What actually happened?**
every minute there was a 5 second freezing of frame or a stutter.once the stutter was complete all the missed frames during that 5 second period would play immediately(looks like a fast forward to the current frame)upon completing the 5 second period, the playback resumes to a normal playback only to have it repeat again in the next minute.

**Comment by bnjmnt4n** [comment]
This seems like an unknown issue with the connection or some other factor. If you can provide information on how to reproduce this consistently we can help to debug. Otherwise, I'm closing this issue for now.
