### ISSUE TITLE
Disconnect stops the download

### ISSUE THREAD

**Issue by martinambrus** [webtorrent/webtorrent-desktop#1132]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.18.0 (0.98.5)

**What operating system and version?**
Windows 7 Ultimate 64-bit

**What did you do?**
A disconnect from the Internet occured and WiFi was down. After a while, Internet and WiFi both started to work again.

**What did you expect to happen?**
For the downloads to continue.

**What actually happened?**
Nothing. Downloads keps in a stale state. Pausing and resuming manually helped though.

**Comment by CaviarBlaque** [comment]
I can confirm this issue. Pausing a download then resuming didn't help in my case. Removing then re-adding torrents didn't help either. I've even quit the app and relaunched it but nothing changed. Eventually after many attempts it does make a stable connection.

**Comment by martinambrus** [comment]
This sounds to me like quite a serious issue, has nobody any interest in fixing it for the community?

**Comment by feross** [comment]
WebTorrent has no notion of internet connectivity status at the moment. This would be a good feature.
