### ISSUE TITLE
Bind ip & port

### ISSUE THREAD

**Issue by Clodo76** [webtorrent/webtorrent-desktop#1142]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
WebTorrent Desktop 0.18.0 Linux

**What operating system and version?**
Debian 8 Jessie with XFCE

**What did you do?**
Seed torrents.

**What did you expect to happen?**
WebTorrent bind to IPv4 address for incoming connections

**What actually happened?**
     netstat -pln | grep LISTEN
show the line
    tcp6       0      0 :::50634                :::*                    LISTEN      1280/WebTorrent --t
but not any 'tcp' ipv4 bind.
Seem listening only over IPv6 on a machine without IPv6.
IPv6 it's also disabled
    cat /proc/sys/net/ipv6/conf/all/disable_ipv6
return 1
and there isn't any interface with IPv6 in ifconfig.

There isn't any configuration file or command-line params where i can force IPv4 bind and maybe a fixed port? Thanks.

**Comment by feross** [comment]
We should check and make sure that we're binding to both IPv4 and IPv6 by default in the webtorrent library. It looks like by default Node.js will only bind to IPv6, if it's available. https://nodejs.org/api/net.html#net_server_listen_port_hostname_backlog_callback
