### ISSUE TITLE
Feature - Auto add torrent files

### ISSUE THREAD

**Issue by pallavmac** [webtorrent/webtorrent-desktop#1149]
Auto add torrent files to web torrent if it finds one in a folder specified by the user. So If I add a torrent file to the downloads folder, auto adding it to the list when I open web torrent is an immensely useful feature. especially when needing to add multiple torrent files.

**Comment by codealchemist** [comment]
You can also leave one machine running WebTorrent Desktop, listening for file changes on a specific folder, then remotely add torrent files to that folder and have them load without interacting with the UI at all. Really useful for batch downloading too.
This is a powerful feature.

**Comment by codealchemist** [comment]
Hey @pallavmac, the feature is implemented in this PR: #1154  
If you want to start playing with it you can clone the repo and switch to `watch-folder` branch.
Any feedback you can provide is welcome.

Cheers!
