### ISSUE TITLE
Torrent Queue support

### ISSUE THREAD

**Issue by chinabala** [webtorrent/webtorrent-desktop#1153]
For some reason while I download more than 3 torrents at the same time, my laptop fan goes crazy and no mention on the heats..

May I suggest to add a torrent queues for next update? So that users can adjust torrent jobs according to their hardware specs. for best performance and experience.

thanks:)

**Comment by lewisl9029** [comment]
This could also be a reasonable workaround for the hanging issues described in https://github.com/feross/webtorrent-desktop/issues/932 when multiple torrents are involved.

Right now, all I can do when my downloads freeze is to uncheck each torrent manually and restart WebTorrent, then start downloading one by one in order. Being able to specify a queue depth would basically automate this process and result in a huge quality of life improvement for those of us experiencing this issue.

**Comment by bnjmnt4n** [comment]
Closing this as a duplicate of #1088.
