### ISSUE TITLE
ClearType not working on menu bar.

### ISSUE THREAD

**Issue by BangladeshBank** [webtorrent/webtorrent-desktop#1159]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
v0.18.0-ia32
**What operating system and version?**
Windows 10
**What did you do?**
Open WebTorrent
**What did you expect to happen?**
See ClearType work
**What actually happened?**
ClearType works on everything in the desktop, and the title bar of WebTorrent, but doesn't work on the menu bar.

**Comment by feross** [comment]
Interesting. Maybe we just need to update Electron to fix this?
