### ISSUE TITLE
Group files by folder and ability to select single folder for download

### ISSUE THREAD

**Issue by kompot** [webtorrent/webtorrent-desktop#1160]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.18.0 (0.98.5)

**What operating system and version?**
OS X 10.12

**What did you do?**
Open torrent contents by clicking on item in main list

**What did you expect to happen?**
Expect to show contents grouped by folder

**What actually happened?**
Flat file list that is hardly readable with current flattened file list with 10+ files present

**Comment by nilskp** [comment]
Duplicate of #755?

**Comment by kompot** [comment]
Definitely, closing this one.
