### ISSUE TITLE
[Feature Request] Download specific files from a torrent

### ISSUE THREAD

**Issue by CaviarBlaque** [webtorrent/webtorrent-desktop#1161]
**What version of WebTorrent Desktop?**
Version 0.18.0 (0.98.5) (64-bit)

**What operating system and version?**
Windows 10 Pro

**What did you do?**
Download a torrent containing multiple files (about 100)

**What did you expect to happen?**
A promt asking me which of the available files I would like to download

**What actually happened?**
The app attempted to download them all at once in no specific order. I had to manually cancel 99 downloads and delete the partially downloaded files I was left with. 

The ability to prioritize downloads, to schedule them in sequence, would be nice too

**Comment by bitstrider** [comment]
Right now, when streaming a multi-file torrent, we can use `Playback > Skip Next / Previous` to navigate through the individual files (though they may not be in the order we expect). It would be a lot better to be able to select the specific file we want to stream from a list of all the files.

**Comment by feross** [comment]
@CaviarBlaque Thanks for the issue. We'll take your feedback into account.

@bitstrider You can click on the torrent entry in the list and it will expand and allow you to select a specific file to stream.
