### ISSUE TITLE
Allow renaming for user torrents

### ISSUE THREAD

**Issue by ItachiSan** [webtorrent/webtorrent-desktop#1169]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.18.0 (0.98.18) (64-bit)

**What operating system and version?**
ArchLinux, GNOME 3, latest packages.
However, I do believe it is the same everywhere.

**What did you do?**
1. Add some magnet or torrent you want to playback.

**What did you expect to happen?**
To have an option, somewhere, to rename the generated name.

**What actually happened?**
The option is missing.

**Additional information**
I would suggest to have the renaming option somehow related to the downloaded content (right click on it and then `Rename`...?).
Even though it is not a necessary feature, I think it is a really nice one.

**Comment by feross** [comment]
This is a cool feature suggestion, but I don't think it's on the roadmap for anytime soon. So I'm going to close this for now.
