### ISSUE TITLE
Can't see anything but a black window

### ISSUE THREAD

**Issue by InfamousThug** [webtorrent/webtorrent-desktop#1170]
WebTorrentDesktop (Windows 64bit) Version 0.18.0

I'm using Windows 10 64bit

 I have used webtorrent on different occasions but this time I installed it once more and once its installed it runs it automatically... And a gray background shows and then its suppose to show suggested torrents.... Only did it not do it this time... Instead the window showed the gray and then it was black... It doesn't show me anything. 
If I try to paste a torrent magnet using the top bar tools it does start it but I still cant control it or see anything on the main panel.

I don't know why it's doing this to me but I've tried uninstalling it and reinstalling it. I even uninstalled it and went to AppData to remove all folders with the name WebTorrent... But still does the same thing.

I have installed the old version v0.17.2 but it does the same thing for me.

I don't know what to do. It doesn't show me anything. Just a black screen

**Comment by marcus-sa** [comment]
Have you tried the newest version 0.18.0?

**Comment by InfamousThug** [comment]
Yes it's the first version I tried and saw the problem and reinstalled
multiply

**Comment by TinpDb** [comment]
Hello, same thing is happening to me and it happens with the curse/twitch program too. The programs run fine and every functionality seems to work, but it's just black. I can start a download by randomly clickling, or start streaming a torrent (or watch a streamer/call a friend on the twitch app), but it's just... black. Here are some screenshots. 
![image](https://cloud.githubusercontent.com/assets/15949838/26015125/d9684f1c-375f-11e7-89d6-f8ec6e82b551.png)
 
Here's a screenshot of twitch app, on startup it shows fine
![image](https://cloud.githubusercontent.com/assets/15949838/26015135/e90bc1ce-375f-11e7-8a12-8fc6e6888995.png)

But this is what I get after the loading animation.
![image](https://cloud.githubusercontent.com/assets/15949838/26015145/fee44af2-375f-11e7-9bd9-7ad3fddcfcf1.png)

I just noticed that pasting the screenshot it turns white, so... I don't know. Something. Hope this helps you guys solve this issue.

**Comment by TinpDb** [comment]
UPDATE: the latest big windows update (creator's) fixed everything for me.
