### ISSUE TITLE
Fedora install

### ISSUE THREAD

**Issue by gtomas41** [webtorrent/webtorrent-desktop#1173]
How can I compile the latest tar.gz source for Fedora 25?
Thank you.

**Comment by pradhanphy** [comment]
You dont need to compile. Just run ./WebTorrent in the unzipped folder.

**Comment by bnjmntn** [comment]
Hi @gtomas41! WebTorrent Desktop is made using [node.js](https://nodejs.org/). To build it from source, you can use [npm](https://www.npmjs.com/) to download dependencies and build. See https://github.com/webtorrent/webtorrent-desktop#how-to-contribute.
