### ISSUE TITLE
Started event issue

### ISSUE THREAD

**Issue by wI2L** [webtorrent/webtorrent-desktop#1177]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.18

**What operating system and version?**
MacOSX El Capitan

**What did you do?**
Started a torrent with the files already downloaded.

**What did you expect to happen?**
Expected the client to send a `Started` event with `left=0`

**What actually happened?**
Tracker received event `Started` with a left parameters not equal to zero in the payload.

Hey
Let me add a bit of context here.
I am writting a tracker in go with the Webtorrent protocol support. During my tests I have noticed that the client send a `left` parameter in its JSON payload while it already have all the files downloaded in local. Usually, trackers can recognized initial seeders because they send `left=0` with the event `started`, and not `completed`.

This leads to wrong scrape stats in scrape/announce response payloads.

Could you please address this issue ?

Thanks

**Comment by wI2L** [comment]
up ?

**Comment by bnjmnt4n** [comment]
I think this issue should be opened at the webtorrent repository as it is not specific to WebTorrent Desktop. See https://github.com/webtorrent/webtorrent.
