### ISSUE TITLE
Feature Request!!!

### ISSUE THREAD

**Issue by Sashusss** [webtorrent/webtorrent-desktop#1178]
We would like to have:

Shut down PC when download is done.
------
Put PC to sleep when download is done.

These options would be great.

Thank you.

**Comment by marcus-sa** [comment]
This is possible on Linux and Mac, but I don't know about Windows.
You can just execute "shutdown now" in the terminal to shut down the PC.
So it's pretty much just using the exec from child_process, and when download is done, just execute the command.

**Comment by Flet** [comment]
The [power-off](https://www.npmjs.com/package/power-off) package would do the trick! :)

The real question is: Does this feature fit with this projects "minimal preferences" approach?

Also, what might the user experience be to enable/disable it?

**Comment by codealchemist** [comment]
This might be another good candidate for a plugin.
I started working on the [plugins branch](https://github.com/webtorrent/webtorrent-desktop/tree/plugins) a while ago and made some progress.
It would be awesome if someone can checkout that branch and help building it.
It's something complex and I don't think I can do it all alone.

WebTorrent Desktop can continue to be really simple and easy to use while providing users the power to extend its basic features with plugins.
