### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by talarari** [webtorrent/webtorrent-desktop#1181]
hey, love the player, haven't seen any new releases lately, is this project still active?

**Comment by mika76** [comment]
I find the best way to check is to look at the network graph: https://github.com/webtorrent/webtorrent-desktop/network

**Comment by ritz078** [comment]
Based on webtorrent-desktop, I have been trying to work on a separate project https://snape.now.sh/ . I will eventually be moving towards webtorrent-desktop like features with better UX.
