### ISSUE TITLE
About Window

### ISSUE THREAD

**Issue by morigs** [webtorrent/webtorrent-desktop#1182]
**What version of WebTorrent Desktop?**
???

**What operating system and version?**
Linux (Deepin 15.4 Desktop)

**What did you do?**
Open About window

**What did you expect to happen?**
See info about app

**What actually happened?**
![js code](https://cloud.githubusercontent.com/assets/13474134/26753007/93e106d4-4865-11e7-8805-40bdec4ec5fa.png)

**Comment by DiegoRBaquero** [comment]
Do you have latest? Can you reinstall?

**Comment by morigs** [comment]
Now everything is fine. Version 0.18.0. Strange bug
