### ISSUE TITLE
Ability to download streams in order (one at a time)

### ISSUE THREAD

**Issue by ldipenti** [webtorrent/webtorrent-desktop#1187]
Hello,

This is a feature request, I've been testing version 0.18.0 for the Mac and couldn't find this option: 
If I add several torrents, all start downloading at once. For those of us with a small Internet pipe, it would be useful to have a setting to tell the app it should download the torrents one at a time, maybe by defining the order on the list?

Thanks.

**Comment by emma-goldman** [comment]
This would be a nice feature indeed! 

Also, to enable sequential downloading for multi-file torrents would be great!

I'm using Windows 10 Version 0.19.0 (0.98.21) (64-bit)

**Comment by feross** [comment]
Thanks for the suggestion. We need to add a queueing system as part of the solution to the CPU issues that happen when adding many torrents. There's an issue somewhere open about this (don't have the link handy), so I'm going to close this one.

**Comment by feross** [comment]
Edit: Actually, let's just use this issue
