### ISSUE TITLE
NZB Support

### ISSUE THREAD

**Issue by theman480** [webtorrent/webtorrent-desktop#1189]
Is there any way to implement nzb support on this amazing tool?

**Comment by marcus-sa** [comment]
NZB is something entirely else than torrenting
There's loads of other programs like this, that is specifically made for NZB.

https://github.com/SiCKRAGETV/SiCKRAGE
https://github.com/Radarr/Radarr
https://github.com/Sonarr/Sonarr
https://github.com/CouchPotato/CouchPotatoServer

**Comment by theman480** [comment]
What? I know the issue is too old but I have to comment on this, any of the tools you listed is for streaming.

**Comment by Borewit** [comment]
https://github.com/spotweb/spotweb
https://github.com/sabnzbd/sabnzbd

**Comment by Borewit** [comment]
Not sure where you are looking for, but NZB is not very suitable for streaming
