### ISSUE TITLE
Played sample video instead of the movie

### ISSUE THREAD

**Issue by neobugx** [webtorrent/webtorrent-desktop#1191]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu.

-> 0.18.0 (0.98.5) (64-bit)

**What operating system and version?**

-> Windows 10 Pro 64-bit 10.0.15063

**What did you do?**

-> Tried to play my downloading movid.

**What did you expect to happen?**

-> Movie start playing via WebTorrent or VLC.

**What actually happened?**

-> Webtorrent played the sample movie file.

Please add a smarter check for the movie file. Something like comparing the sizes of the torrent's video files and play the biggest one in size (this will be the actual movie).

**Comment by DiegoRBaquero** [comment]
Does it happen when you restart the app?

Could you record your screen to see it happen?
