### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by ThatFatPat** [webtorrent/webtorrent-desktop#1192]
Hi, My name is Iddo.
Amazing work on th Desktop client, keep it up!
I have a problem. I am not a native speaker and need to use subtitles.
Problem is, it's not very easy with the player...
So I'm asking for two things:

    Enabling Timeshifting for subtitles

    Integrate the OpenSubtitles API for looking up subtitles, or even just acquiring the best match.

If it helps, I can work on the behind the scenes code for getting the best match from OpenSubtitles...

Thanks anyway, and keep up the good work!

**Comment by codealchemist** [comment]
Hi Iddo!
We already talked about **downloading subs** in WebTorrent, but decided not to go that way.
Instead, we started looking into a plugins system and the possibility of externally supporting it, by installing a 3rd party plugin.
Look at #1156 for reference.

Regarding **time shifting**, that might be interesting.
:)

Cheers!

**Comment by bnjmnt4n** [comment]
Closing this for now while we wait for plugin support (#664/#1156).
