### ISSUE TITLE
Webtorrent not listing android-tv chromecast receiver.

### ISSUE THREAD

**Issue by tonyhawz** [webtorrent/webtorrent-desktop#1193]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.18.0 (0.98.19) (64-bit)

**What operating system and version?**
Ubuntu 16.04.2 LTS 

**What did you do?**
Start movie

**What did you expect to happen?**
My chromecast (android tv, mibox 3) listed at the cast menu

**What actually happened?**
it wasn't

**Notes** 
it is related to mafintosh/chromecasts#29 
I have built webtorrent with andyshinn/chromecasts@efee2a9  and it worked

**Comment by davisjackie321** [comment]
Yea

**Comment by feross** [comment]
This issue was fixed in the `chromecasts` package and was released in WebTorrent Desktop v0.19.0 (released on 2018-01-26).
