### ISSUE TITLE
Compatibility with Win XP

### ISSUE THREAD

**Issue by azat11** [webtorrent/webtorrent-desktop#1194]
I downloaded the latest version of installer from the site, and then the zip archive from here.
"WebTorrentSetup-v0.18.0-ia32.exe" and "WebTorrent-v0.18.0-win-ia32.zip".
But I get "not a valid win32 application" when I try to run it.
I'm running Win XP SP3.
Does this mean there is no comaptibility with this OS?

**Comment by DiegoRBaquero** [comment]
Probably not, everything we use is pretty recent and XP has been EOL for a while now. I'd suggest upgrading your OS, we can't keep backwards compatibility for OS that were released more than 10 years ago.

Is your OS 32 bits?

**Comment by azat11** [comment]
Yes, 32 bits.
Thanks for the answer, and for the WebTorrent itself.)
Although it seems I can't really use it, cause I run 8 year old PC) Not an option for now, using more recent and popular OS) Thanks)

**Comment by DiegoRBaquero** [comment]
Sorry to hear. Electron's team stated that it's Win7+ only.
