### ISSUE TITLE
When checks files exists with multiple torrent at once causing HDD overload

### ISSUE THREAD

**Issue by samurai815** [webtorrent/webtorrent-desktop#1195]
WebTorrent Desktop version 0.18.0 (0.98.5) (32-bit)

Windows 7

When I add many files torrent to check files exists, it checks files exists with multiple torrent at once causing HDD overload Or stop checking at 0% when there are too many torrents waiting
So, I recommend checking in order one by one

**Comment by WarcraftAcc** [comment]
WebTorrent Desktop version 0.18.0 (0.98.5) (64-bit)

Windows 10 Pro

i can confirm this issue
