### ISSUE TITLE
App does not start on macOS 10.13

### ISSUE THREAD

**Issue by MoOx** [webtorrent/webtorrent-desktop#1197]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

0.18 (and master branch)

**What operating system and version?**

macOS 10.13 Beta 2 (17A291m)

**What did you do?**

I am trying to launch the application.

**What did you expect to happen?**

The app to open

**What actually happened?**

The app is not opening the main window.

I tried with master branch. Here are some logs

<details><summary>$ npm install && npm start</summary>
<pre><code>
> macos-alias@0.2.11 install /Users/MoOx/Sync/Development/webtorrent-desktop/node_modules/macos-alias
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/volume/src/volume.o
  SOLINK_MODULE(target) Release/volume.node

> fsevents@1.1.1 install /Users/MoOx/Sync/Development/webtorrent-desktop/node_modules/fsevents
> node install

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/Users/MoOx/.nvm/versions/node/v8.1.3/bin/node',
node-pre-gyp verb cli   '/Users/MoOx/Sync/Development/webtorrent-desktop/node_modules/fsevents/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.33
node-pre-gyp info using node@8.1.3 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/Users/MoOx/Sync/Development/webtorrent-desktop/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v57-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v57-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.1 and node@8.1.3 (node-v57 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v57-darwin-x64.tar.gz 
node-pre-gyp verb command build [ 'rebuild' ]
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  COPY /Users/MoOx/Sync/Development/webtorrent-desktop/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp
node-pre-gyp info ok 

> fs-xattr@0.1.15 install /Users/MoOx/Sync/Development/webtorrent-desktop/node_modules/fs-xattr
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/xattr/src/async.o
  CXX(target) Release/obj.target/xattr/src/error.o
  CXX(target) Release/obj.target/xattr/src/sync.o
  CXX(target) Release/obj.target/xattr/src/util.o
  CXX(target) Release/obj.target/xattr/src/xattr.o
  SOLINK_MODULE(target) Release/xattr.node

> electron-chromedriver@1.7.1 install /Users/MoOx/Sync/Development/webtorrent-desktop/node_modules/electron-chromedriver
> node ./download-chromedriver.js

> bufferutil@3.0.1 install /Users/MoOx/Sync/Development/webtorrent-desktop/node_modules/bufferutil
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.1.2
prebuild-install info looking for local prebuild @ prebuilds/bufferutil-v3.0.1-node-v57-darwin-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/MoOx/.npm/_prebuilds/https-github.com-websockets-bufferutil-releases-download-v3.0.1-bufferutil-v3.0.1-node-v57-darwin-x64.tar.gz
prebuild-install http request GET https://github.com/websockets/bufferutil/releases/download/v3.0.1/bufferutil-v3.0.1-node-v57-darwin-x64.tar.gz
prebuild-install http 200 https://github.com/websockets/bufferutil/releases/download/v3.0.1/bufferutil-v3.0.1-node-v57-darwin-x64.tar.gz
prebuild-install info downloading to @ /Users/MoOx/.npm/_prebuilds/https-github.com-websockets-bufferutil-releases-download-v3.0.1-bufferutil-v3.0.1-node-v57-darwin-x64.tar.gz.14888-cadc1bd22483b.tmp
prebuild-install info renaming to @ /Users/MoOx/.npm/_prebuilds/https-github.com-websockets-bufferutil-releases-download-v3.0.1-bufferutil-v3.0.1-node-v57-darwin-x64.tar.gz
prebuild-install info unpacking @ /Users/MoOx/.npm/_prebuilds/https-github.com-websockets-bufferutil-releases-download-v3.0.1-bufferutil-v3.0.1-node-v57-darwin-x64.tar.gz
prebuild-install info unpack resolved to /Users/MoOx/Sync/Development/webtorrent-desktop/node_modules/bufferutil/build/Release/bufferutil.node
prebuild-install info unpack required /Users/MoOx/Sync/Development/webtorrent-desktop/node_modules/bufferutil/build/Release/bufferutil.node successfully
prebuild-install info install Prebuild successfully installed!

> electron@1.6.0 postinstall /Users/MoOx/Sync/Development/webtorrent-desktop/node_modules/electron
> node install.js

npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> webtorrent-desktop@0.18.0 prepublish /Users/MoOx/Sync/Development/webtorrent-desktop
> npm run build

> webtorrent-desktop@0.18.0 build /Users/MoOx/Sync/Development/webtorrent-desktop
> buble src --output build

added 1015 packages in 162.515s

> webtorrent-desktop@0.18.0 start /Users/MoOx/Sync/Development/webtorrent-desktop
> npm run build && electron .

> webtorrent-desktop@0.18.0 build /Users/MoOx/Sync/Development/webtorrent-desktop
> buble src --output build

Missing config file: Creating new one
2017-07-07 08:22:01.742 Electron[14898:358555] !!! BUG: The current event queue and the main event queue are not the same. Events will not be handled correctly. This is probably because _TSGetMainThread was called for the first time off the main thread.
</code></pre>
</details>

An electron logo is opened but no window. When I click on the logo I don't even see a menu in macOS menubar.

FYI, other electrons app are working without any problem on macOS 10.13 (atom, atom beta, slack etc)

**Comment by DiegoRBaquero** [comment]
We might need to create a new build to support it.

@feross @dcposch

**Comment by MoOx** [comment]
By running locally using npm install/start this is not building the app from scratch?

**Comment by DiegoRBaquero** [comment]
What if you update the deps?

**Comment by MoOx** [comment]
I installed from scratch since I usually use the provided app from the dmg.
But I can try npm update (but I guess this won't do anything more than a fresh install?)

**Comment by Lowtechpt** [comment]
Any news? Doesn't work for me too :(

**Comment by azag0** [comment]
I just ran webtorrent fresh from Github (npm start) on 10.13 beta and got this:

```
2017-07-22 13:13:08.283 Electron[7199:1422463] !!! BUG: The current event queue and the main event queue are not the same. Events will not be handled correctly. This is probably because _TSGetMainThread was called for the first time off the main thread.
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-11.1.12/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 3 
```

**Comment by aluisscp** [comment]
This is still happening on the latest betas. Are there any news?

**Comment by MoOx** [comment]
Magically resolved since my last update (macOS 10.13 beta 4 (17A315i))

**Comment by Lowtechpt** [comment]
Still not working.
Log in attachment 
![captura de ecra 2017-08-02 as 22 45 01](https://user-images.githubusercontent.com/30203076/28896546-c5085c00-77d4-11e7-9916-4a4908aa64c2.png)
[WebTorrent.pdf](https://github.com/webtorrent/webtorrent-desktop/files/1195396/WebTorrent.pdf)

**Comment by aluisscp** [comment]
Still happening here as well.
