### ISSUE TITLE
[Windows] External player text doesn't immediately update on change

### ISSUE THREAD

**Issue by Zyst** [webtorrent/webtorrent-desktop#1199]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.18.0 (0.98.5) (64-bit)

**What operating system and version?**
Windows 10 Home 64 bit Version 1703

**What did you do?**
Changed the default external player from VLC to mpv

![External player changed](https://user-images.githubusercontent.com/3832380/27972481-2bfdf85c-631c-11e7-8082-9dbe3ddf4214.png)

**What did you expect to happen?**
The text noting the currently used player updates to `mpv`

**What actually happened?**
It remains as `VLC`. Closing and re-opening WebTorrent seems to fix this.

![After reboot, displaying the correct player](https://user-images.githubusercontent.com/3832380/27972544-5ba5bf0e-631c-11e7-8cd0-b182af9808b2.png)

**Comment by Zyst** [comment]
Couldn't find a duplicate of this, I did go through all the open issues. I apologize if this is, however, a duplicate.

If so please link the relevant issue and close this one, I'll re-post the OP in that issue as well.

**Comment by chinabala** [comment]
Same to me. I was gonna post a New Issue, and was re-producing my steps then found it actually did change my external media player.

It really didn't work the first time....
