### ISSUE TITLE
Ubuntu version doesn't start

### ISSUE THREAD

**Issue by TheSirC** [webtorrent/webtorrent-desktop#1201]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
v0.18
**What operating system and version?**
elementaryos 0.4.1 Loki (based on Ubuntu 16.04.2 LTS)
**What did you do?**
I tried to start the application (both via the GUI or the command line via `webtorrent-desktop `
**What did you expect to happen?**
The application didn't start.
**What actually happened?**
From the command line I obtain that output : `webtorrent-desktop: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory`
But the library is present on the system

**Comment by sergiusens** [comment]
it works fine on regular Ubuntu

**Comment by TheSirC** [comment]
It seems that choosing the wrong binary `i386` instead of `amd64` make it crash. In other words, choosing the 32 bits version of the package for a 64 bits processor make it bug.
Feel free to correct me if I'm wrong.

**Comment by larson004** [comment]
I also faced the same issue.
https://webtorrent.io/desktop/ serves the 32-bit version by default.

**Comment by feross** [comment]
@larson004 Actually, we try to detect your CPU architecture based on your browser user-agent, but it's not perfect.
