### ISSUE TITLE
I can not cast to chromecast

### ISSUE THREAD

**Issue by pedrohenriquemelo** [webtorrent/webtorrent-desktop#1202]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

0.18.0 (0.98.5) (64-bit)

**What operating system and version?**

Windows, version 10

**What did you do?**

Just start the download and I waited so that it could transmit to the chromecast but the transmission icon did not appear in the program

**What did you expect to happen?**

Which appears the option in the bar where it shows the pause the chromecast icon

**What actually happened?**

Did not appear

**Comment by AshlessCinder** [comment]
related https://github.com/webtorrent/webtorrent-desktop/issues/1193

looks like a bug in a seperate project

**Comment by homerjam** [comment]
+1

Using OSX version on High Sierra

**Comment by feross** [comment]
This issue was fixed in the `chromecasts` package and was released in WebTorrent Desktop v0.19.0 (released on 2018-01-26).
