### ISSUE TITLE
Only 33 bytes download

### ISSUE THREAD

**Issue by GeorgeBgk** [webtorrent/webtorrent-desktop#1204]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.18.0 (0.98.5)
**What operating system and version?**
macOS Sierra 10.12.6 Beta (16G24b)
**What did you do?**
Clicked a magnet link on a site.
**What did you expect to happen?**
File to be downloaded
**What actually happened?**
Only 33 bytes downloaded.

**Comment by DiegoRBaquero** [comment]
Can you provide more details? Which torrent? Did any error appear? What about console logs?

**Comment by GeorgeBgk** [comment]
@DiegoRBaquero Sorry. I found out, that my hard drive was full. You should implement a "Torrent might not fit on your drive" warning

**Comment by DiegoRBaquero** [comment]
That would certainly be a good feature.
