### ISSUE TITLE
How to change the language of  WebTorrent Desktop v0.18.0 ?

### ISSUE THREAD

**Issue by KingMaxer** [webtorrent/webtorrent-desktop#1208]
How to change the language of  WebTorrent Desktop v0.18.0 (0.98.5) (64-bit) ???

I use WebTorrent Desktop v0.18.0 on the Windows10 1703 64bit (OS version15063.483) ，but I can't find
the Options for modifying languages in the software.  I try to use the"WebTorrentSetup-v0.18.0.exe"  and the "WebTorrent-v0.18.0-win.zip" ,  the software in these two files all have no language switching function. But, I find these two files all have a folder with language packs , the folder name is "locales".
That means the software may support change the language from en-US to other languages.

So, how to change the language of  WebTorrent Desktop v0.18.0 (0.98.5) (64-bit) ???

**Comment by DiegoRBaquero** [comment]
Hi, I'm sorry to tell you but WebTorrent Desktop is an english only app so far.

**Comment by KingMaxer** [comment]
Thank you for your prompt reply！@DiegoRBaquero

Is there a plan to make WebTorrent Desktop support multilanguage ?

Many Chinese users have added the WebTorrent friendly trackers in torrent files and magnet links when publishing BT resources.
If you want to know, I can tell you some related websites.
From this point of view, there may be many other users already using related technologies in other countries.
So,if the software supports multiple languages,then more users will be able to use the WebTorrent Desktop,
and then related technologies will be well used and spread.
Therefore, I think it is necessary to make WebTorrent Desktop support multilanguage.

I really hope the next version of WebTorrent Desktop can support multilanguage.

The trackers we added in torrent files and magnet links are below:
wss://tracker.openwebtorrent.com
wss://tracker.btorrent.xyz
wss://tracker.fastcast.nz
