### ISSUE TITLE
Support subtitles on DLNA devices (e.g. Xbox One)

### ISSUE THREAD

**Issue by Earth-Q** [webtorrent/webtorrent-desktop#1210]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu) 0.18.0

**What operating system and version?** MacOS 10.12.5 

**What did you do?** Streamed the torrent stream to Xbox One. Added subtitles to torrent, shows up on native app. Tried adding both before and after starting the connection to the Xbox. Neither worked. 

**What did you expect to happen?** Subtitles to show up.

**What actually happened?** No subtitles showed up.

**Comment by feross** [comment]
Does the Xbox One use DLNA for playback?
