### ISSUE TITLE
WebTorrent can't be limited to desired bandwidth (stops downloading)

### ISSUE THREAD

**Issue by WarcraftAcc** [webtorrent/webtorrent-desktop#1214]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.18.0 (0.98.5) (64-bit)
**What operating system and version?**
Windows 10 Pro (64-bit)
**What did you do?**
Block some traffic with "netlimiter"
**What did you expect to happen?**
Download speed should go up to desired amount.
**What actually happened?**
download stopped.

I use netlimiter to limit my pc's traffic so other people on my network can continue browsing normally but if i limit webtorrent it stops downloading completely.
it would be nice that webtorrent doesn't consume the whole net traffic, 
my suggestion is to **add an option to limit download/upload speeds**

**Comment by DiegoRBaquero** [comment]
This is a feature request for the main library: https://github.com/webtorrent/webtorrent/issues/163
