### ISSUE TITLE
Tray Icon doesn't appear

### ISSUE THREAD

**Issue by ghost** [webtorrent/webtorrent-desktop#1215]
I'm running gnome on Arch Linux on the latest stable release (and master).

The tray icon doesn't appear at all.

I downloaded source and removed [this check](https://github.com/webtorrent/webtorrent-desktop/blob/master/src/main/tray.js#L39) for compatibility by bypassing the checkLinuxTraySupport() function.
Everything works perfectly when it's allowed to.

Why is this check necessary? I'd imagine trying to create a tray icon on an incompatible system would lead to an error right? Why isn't createTray() just surrounded in a try/catch block?

I'm happy to contribute a PR if you point me in the right direction ;D

**Comment by DiegoRBaquero** [comment]
The check is meant for debian-based OS's. I'm guessing it would crash if it wasn't there.

A check for the OS would be needed if you want to go around it, feel free to submit a PR.

**Comment by AshlessCinder** [comment]
for reference https://github.com/webtorrent/webtorrent-desktop/issues/383

If the tray icon doesn't work then the application's window closes, but it still runs in the background without any indication.
The check is to prevent this behavior and simply close the application completely.

I'm going to submit a PR that only performs the check on Debian systems.
