### ISSUE TITLE
App does not start on macOS 10.13

### ISSUE THREAD

**Issue by aluisscp** [webtorrent/webtorrent-desktop#1218]
What version of WebTorrent Desktop? (See the 'About WebTorrent' menu)

18

What operating system and version?

macOS 10.13 Beta 4

What did you do?

Tried to launch the application.

What did you expect to happen?

The app to open

What actually happened?

The app is not responding and I have to force close it.

Opening this issue because the last one was closed but it's still happening.

**Comment by harish31** [comment]
Yes i faced the same issue

**Comment by aluisscp** [comment]
Still not working on Developer Beta 5.

**Comment by aluisscp** [comment]
Latest Developer Release is working fine.
