### ISSUE TITLE
How did you guys got that Windows Anthenticode??

### ISSUE THREAD

**Issue by etiennepinchon** [webtorrent/webtorrent-desktop#1219]
Hey! 

I love your app, I have learned a lot from it on how to use Electron.
I wanted to sign my own app for Windows so I bought a Comodo certificate. Now here is the thing, they ask me for all of those things and I think it's totally fucked up just to sign a Windows app.. 

> 1.Government issued photo ID [driver's license OR passport]
> 2.One Financial institution documents [A bank statement or credit card less than six months old]
> 3.One Non- Financial documents [Gas bill, Water bill, Power bill ]
> 4.Business entity registration with listing company name.
> 5. You need to fill out the Face to face form with Notary Signature.
> 
> You can download here the link :
> 
> https://support.comodo.com/index.php?/Knowledgebase/Article/View/903/0/face-to-face-verification-form
> 
> 6. You need to get Attested by notary (i.e above 1,2,3,5).
> 

Did you guys did something similar to this?

Kind regards,
Etienne

**Comment by DiegoRBaquero** [comment]
@feross

**Comment by etiennepinchon** [comment]
up? Anybody? :(

**Comment by feross** [comment]
Yep, we had to go through this process. It sucks. I think I went through the process as an individual, not a business which was even worse.

Sadly, there's a monopoly on these types of certs so there's no other options.

**Comment by ItsDizzy** [comment]
It's not even possible to go as an individual anymore these days :(

**Comment by etiennepinchon** [comment]
Totally crazy stuff.. I had to give up on Windows.. 😥
