### ISSUE TITLE
Large Files / Folders not working, no error message

### ISSUE THREAD

**Issue by soraryu** [webtorrent/webtorrent-desktop#1223]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.18.0 (0.98.5) (64-bit)

**What operating system and version?**
Windows 10, latest updates

**What did you do?**
File > Create New Torrent from Folder > Select a folder with 240GB of data in it. (4 8k videos with 1hr of content)

**What did you expect to happen?**
A torrent being created + showing the torrent.

**What actually happened?**
Nothing. No error message, nothing telling me "it didn't work", nothing telling me it did.
Also, couldn't find anything about max. supported file sizes.
Instant.io also does nothing when I drag one of the files there.

**Comment by DiegoRBaquero** [comment]
What's happening is that such large file would take a lot of time to be processed but there's no feedback at the moment that says that something is being done.

Instant.io uses RAM, so it wouldn't support it.

**Comment by soraryu** [comment]
Ok, so desktop should work though, just takes long?

Am 09.08.2017 18:27 schrieb "Diego Rodríguez Baquero" <
notifications@github.com>:

**Comment by feross** [comment]
@soraryu That's correct. We need a better UI to indicate the progress of the hashing process.
