### ISSUE TITLE
Not opening on Mac OS High Sierra

### ISSUE THREAD

**Issue by siddiqq** [webtorrent/webtorrent-desktop#1224]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Latest 0.18
**What operating system and version?**
Mac OS Sierra
**What did you do?**
Open app
**What did you expect to happen?**
It to open
**What actually happened?**
Didn't open

Pleaseeee fix this app as it made me absolutely hate every other torrent client I've tried. Its my favorite and I regret updating to High Sierra because of this lol. I know High Sierra is in beta but it wouldn't hurt to fix it anyway :D

**Comment by DiegoRBaquero** [comment]
Repeated: https://github.com/webtorrent/webtorrent-desktop/issues/1218
