### ISSUE TITLE
Download stuck after few minutes I have to restart it again than after few mintes same thing happen.

### ISSUE THREAD

**Issue by tauseefch** [webtorrent/webtorrent-desktop#1225]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.18.0 (0.98.5) (64-bit)
**What operating system and version?**
Windows 10 64 bit
**What did you do?**
Whenever I try to download new torrent after few minutes it stuck I have to restart the software to resume the downloading I have been using it for a very long time and as long as I have been using it I am getting this issue.
**What did you expect to happen?**

**What actually happened?**

**Comment by WarcraftAcc** [comment]
i noticed that there is an issue with download if you are limiting your bandwidth, so if you are, don't

**Comment by cezar-carneiro** [comment]
also, could be something related to the tracker, maybe

**Comment by myotavietnam** [comment]
Webtorrent is also behind NAT as other , so it need turn server , more users , less speed because all data should go through a server to connect each other .
This method is useless for p2p , best way is to make client which has transport way as http

**Comment by feross** [comment]
Sorry that you're experiencing this issue. This is a known issue and has been reported by other users. We'll do our best to fix it.
