### ISSUE TITLE
Don't download at full speed always

### ISSUE THREAD

**Issue by davidlondono** [webtorrent/webtorrent-desktop#1226]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
1.18.0
**What operating system and version?**
MacOs 10.1.2
**What did you do?**
Download a torrent at full speed
**What did you expect to happen?**
To control the max speed of the torrent to don't saturate the brand width for other connected
**What actually happened?**
no way to change the speed of download

**Comment by DiegoRBaquero** [comment]
Dup https://github.com/webtorrent/webtorrent-desktop/issues/435
