### ISSUE TITLE
Can you clarify the security model of the Signaling Server?

### ISSUE THREAD

**Issue by neuroradiology** [webtorrent/webtorrent-desktop#1228]
In the "WebTorrent: How I built a BitTorrent client in the browser" [video at the 45:11 mark](https://youtu.be/3w_6dfqrpzk?t=45m11s), Feross says that the signaling server sees the _secret_ keys for both sides of the transaction. 

Is that correct!? 

It should be trivial to harden the protocol against this by using [public key cryptography](https://en.wikipedia.org/wiki/Public-key_cryptography), which allows secure communication in an insecure channel.

This is quite basic, and I suspect the video was simply misstated. But having looked through the repo I can't tell where this happens. Can anyone else provide a link or explanation to how this is implemented?

**Comment by DiegoRBaquero** [comment]
The signaling servers sees the SDP offer and answer, which includes the keys. This should happen in https://github.com/webtorrent/bittorrent-tracker which then uses https://github.com/feross/simple-peer, which is the WebRTC wrapper.

**Comment by feross** [comment]
> Feross says that the signaling server sees the secret keys for both sides of the transaction.

Yep, I misspoke. This uses something like diffie-helman so the server can't MITM the connection even though it sees the communication in both directions initially.
