### ISSUE TITLE
Add WebTorrent to the Windows Store

### ISSUE THREAD

**Issue by Dyras** [webtorrent/webtorrent-desktop#1230]
Greetings! Excellent program you got here. Any possibility you could add it to the Windows Store? That way it could be used by Windows 10 S users. PicoTorrent is already in the Windows Store so Microsoft doesn't seem to have an issue with torrent clients.

Think about it! 😃

**Comment by SergeShkurko** [comment]
+1

**Comment by WenqiangXie** [comment]
As a Windows 10 user, I'd also love to see that the great application WebTorrent add to Windows Store. So could do that?
