### ISSUE TITLE
Instability issues when ~15 torrents opened concurrently

### ISSUE THREAD

**Issue by Moscarda** [webtorrent/webtorrent-desktop#1231]
**What happened?**
While earlier beta releases simply crashed and quit more often, recent releases, while much improved, can crash yet never close or alert the user.  This occurs most often when more than ten or so torrents are loaded (or loading, in the case of magnets—come to think of it, it is most often with magnet links) even if only a couple are active and the rest paused.  Sometimes the problem will appear as if there are either no/fewer seeds/peers, or as if one's connection is much slower than it is.  Yet once a few torrents are removed from the list, these torrents immediately find their swarm and download immediately.  Other times when I'm not eyeballing the progress bars on my downloads like a hawk, I'll check in every other hour or so and WebTorrent might appear fine (I'm sure the stats are off) but the app is stuck.  Not just the transfers, but the app.  I'd say "frozen" rather than stuck, but for the otherwise normal appearance of the UI.  I haven't done any proper troubleshooting beyond paying as much attention to my resources and whats going on when these issues arise.  Problem seems to occur regardless of available memory or storage, bandwidth, etc.  If I had to guess, I'd say WebTorrent is trying too hard to find peers all at once, and there is some kind of bottleneck effect.  

I include this issue under the stability umbrella because other lightweight torrent clients can handle even a couple hundred torrents open at once.  The ability to have a decent amount of torrents open isn't just a feature request for me, its about the ability to keep seeding a file after completion without worrying that keeping in the file list will cause WebTorrent to crash.  There are already those who criticise apps that enable sequential downloading, claiming it threatens the health and longevity of a torrent, and while I don't think its that simple, WebTorrent isn't currently stable enough for serious seeders.

**What version of WebTorrent Desktop?**
Version 0.18.0 (0.98.5)

**What operating system and version?**
macOS 10.12.6 (16G29)

**Comment by kopy-kate** [comment]
Project seems to have been abandoned earlier this year.. it seems.

WebRTC and Electron (chromium-based framework for WebTorrent to run on) seem to be CPU heavy weights for some reason. Based on my research, this problem isn't exclusive to WebTorrent.. any app that uses Electron tends to consume tons of CPU.

This I believe is the reason WebTorrent isn't living up to its full potential. It's gonna be hard work producing more efficient code that doesn't total your CPU, but it'll be worth it. Now that I've gotten the hand of Node.js I might try creating a lightweight torrent client with electron that strips everything to the bare minimum .. just ASCII text.. and then once we've gotten the CPU issue out of the way, start adding all the fancy graphics and thumbnails.

**Comment by Moscarda** [comment]
has WebTorrent really been abandoned?  Hard to believe with all the hype around Electron and the transition to a decentralised web.  What was the reason?

**Comment by kopy-kate** [comment]
Dunno. Haven't heard back from the creator, and hasn't been updated since February 2017.. though it was being actively worked on last year.

**Comment by bnjmnt4n** [comment]
Sorry for the late response! I've also experienced the issue mentioned, where torrents appear to be loading but are actually stuck at the same part for some time, but it hasn't been easy to debug and find the cause of the issue, so we aren't able to get a fix yet. As for the WebTorrent project, it definitely isn't dead, but most of our contributors have not been that active — after all, it is an open source project and we do have other things to do. I'll try to look into the issue and see if I can reproduce it and try to debug then.

**Comment by feross** [comment]
> Project seems to have been abandoned earlier this year.. it seems.

WebTorrent is not abandoned. We had a release of the desktop app on Jan 26, 2018 ([changelog](https://github.com/webtorrent/webtorrent-desktop/blob/master/CHANGELOG.md)). And the core webtorrent library has been [regularly released](https://github.com/webtorrent/webtorrent/blob/master/CHANGELOG.md) many times in 2018 as recently as yesterday (April 24, 2018).

WebTorrent is a volunteer effort ✨ so the amount of work that gets done is dependent on the free time of the volunteers who are involved.
