### ISSUE TITLE
Destop verson and NAT problem

### ISSUE THREAD

**Issue by myotavietnam** [webtorrent/webtorrent-desktop#1232]
Hi, we are building a project which use WEBtorrent destop but we are facing problem : 

**What version of WebTorrent Desktop?** - 0.1.8

**What operating system and version? WINDOW 7 64 bit

**What actually happened?
+Webtorent destop client is not able to connect with other Webtorrent destop client , just able to download from standar bittorent client .
+DMZ port forward : Can connect with each other .( webtorrent destop with webtorrent destop)
+ 2 client from 2 ISP with 2 diffirent internet IP .

Is is true that webtorrent also must forward port in router ? if so , nothing diffirent with traditional standar torrent client ..

**Comment by feross** [comment]
WebTorrent does not support NAT port forwarding yet. You can follow the progress of this feature here: https://github.com/webtorrent/webtorrent/issues/195
