### ISSUE TITLE
Audio Codecs Not Working

### ISSUE THREAD

**Issue by aluisscp** [webtorrent/webtorrent-desktop#1235]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.18.0 (0.98.5)

**What operating system and version?**
macOS 10.13 Developer Beta 9

**What did you do?**
Try to play multiple movie torrents

**What did you expect to happen?**
Play the file

**What actually happened?**
Audio Codec Unsupported

Every single file be it AAC/MP3/DTS/DD5  will fail when trying to play it.

They run fine on every other player, but I'm interested in Webtorrent-desktop to be able to stream directly to apple tv.

**Comment by adanlobato** [comment]
It happens to me too. Concretely with A52 (AC3) audio codec.

According to this comment (https://github.com/webtorrent/webtorrent-desktop/issues/1051#issuecomment-273441660) it should be a webtorrent issue, since I can play it in Chrome without issues.

**Comment by Borewit** [comment]
Is this the same issue as desribed in #1320? To mo it is not really clear if you are talking about audio as part of a movie, or pure audio files.

**Comment by sp-adan-lobato** [comment]
The audio of the movie, I can watch the movie but sound is not reproduced.

Thanks for answering!
