### ISSUE TITLE
Possibility of setting the download and upload rate?

### ISSUE THREAD

**Issue by Zorrototo** [webtorrent/webtorrent-desktop#1236]
I'm using WebTorrent Dektop on Windows 7 x64 Ultimate.

I would like to know if it is possible to add settings to limit the download and upload rates in Web Torrent in a future update? Maybe globally for the whole WebTorrent client, but also maybe settings for each torrent. I didn't find any setting in the current version but maybe that is just me. Thanks for the work on this great software, hope to see this feature added soon :)

**Comment by Zorrototo** [comment]
Of course everytime the same, I find things AFTER I post something lol

Here is similar issue from last year https://github.com/webtorrent/webtorrent-desktop/issues/435

At least this is a way to UP this request. If any dev can comment about today's status of this feature request that would be really appreciated. Thanks.

**Comment by DiegoRBaquero** [comment]
Nobody is currently working on the feature. PRs accepted.
