### ISSUE TITLE
Desktop playback - Can't hide the play bar at the bottom when in fullscreen mode.

### ISSUE THREAD

**Issue by Draqen4** [webtorrent/webtorrent-desktop#1241]
Version 0.18.0 (0.98.5)(64-bit)
Windows 10 x64

I'm trying to watch a video in fullscreen that is currently downloading, but the mouse cursor and the bar at the bottom never disappear. It did go away once randomly on its own, but then came back a few minutes later. Not sure how I can make them stay hidden?

**Comment by bnjmnt4n** [comment]
The video controls work similar to most video players, by default the cursor and controls will be hidden after a few seconds unless you move the mouse or the cursor is currently over the video controls.
