### ISSUE TITLE
Individual Torrent Location Options

### ISSUE THREAD

**Issue by PenguinInaBand** [webtorrent/webtorrent-desktop#1245]
> Version 0.18.0 (0.98.5) (64-bit)
> Windows 10 Pro 64Bit

Need an option to **prompt location for torrent on initiation**
_And/Or_ 
Need an option to **change the location of a torrent on right click.**

Also if possible, an option to prioritize file order by filename. 

# This is by far the best performing torrent client I've seen. Thanks for your great work!

**Comment by bnjmnt4n** [comment]
Setting a download location seems like a popular feature request. However prompting for a location on each download might be a little annoying. Any opinions?

**Comment by PenguinInaBand** [comment]
Option 1 is to ask the user to select the download folder during the
installation process.
Option 2 is to prompt for location each time
Option 3 is to include a feature that allows the user to change the
download location of specific torrents by right clicking on the torrent
Option 4 is to have a menu where you can turn on/off prompts by default.
