### ISSUE TITLE
Corrupt data

### ISSUE THREAD

**Issue by aurimus** [webtorrent/webtorrent-desktop#1256]
Not sure how it happens yet, but every now and then I get a torrent that's fully downloaded but in reality it has holes and the file (media) would not play through and through. What I do is delete the torrent from list and readd it, then it confirms most of the torrent and stops at the point that it has the hole and downloads it (confirming that the first full download had issues).

Ubuntu 17.04
Not sure which version of WebTorrent because can't find the version number

**Comment by feross** [comment]
Hey @aurimus! Sorry you ran into this issue. I've personally never seen this happen before. If you can provide more information to help us reproduce this, that would be very helpful.

Can you try to reproduce this error once more? But this time when it happens, click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

If you don't see any errors, then please check in one more place! Click View > Developer > Show WebTorrent Process, select the Console tab and copy-paste all the text.

Being able to see that output would help us out very much. Thanks.
