### ISSUE TITLE
Webtorrent cannot handle multiple torrent

### ISSUE THREAD

**Issue by Shankymahajan** [webtorrent/webtorrent-desktop#1258]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.18.0
**What operating system and version?**
Mac OS (High Sierra)
**What did you do?**
Downloading multiple torrents

**What actually happened?**
 PC starts Lagging alot.(90% of CPU is performing) 

I tried to download 4 and more torrent at a time but pc starts lagging. This is not the first time. I'm observing it from a while.

**Comment by feross** [comment]
Known issue. Thanks for reporting.
