### ISSUE TITLE
cursor keys affecting playhead position  pretty please?

### ISSUE THREAD

**Issue by alelondon** [webtorrent/webtorrent-desktop#1264]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

**What operating system and version?**

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by bnjmnt4n** [comment]
Hi, not too sure what the title means. Closing for now. Feel free to provide more information.

**Comment by alelondon** [comment]
Hi, please re-open this  issue, I've left new details for you to understand what I've meant.

**Comment by bnjmnt4n** [comment]
We currently also use the same shortcut as VLC (alt + arrow), as VLC is one of the most popular media players and we decided to follow its lead.

**Comment by alelondon** [comment]
certainly the most popular player is the youtube one. It behaves as i
suggested and i guess this decision was made based on usability testing. My
everyday players: mpv and smplayer behave like youtube in this respect. I
would really appreciate you reconsider this key mapping.

**Comment by alelondon** [comment]
or offer a setting in preferences to quickly map keys this way.BTW have you
had a look at mpv keyboard mapping? its great!
