### ISSUE TITLE
Feature Request: organize files with folders

### ISSUE THREAD

**Issue by qqdaiyu55** [webtorrent/webtorrent-desktop#1267]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.18.0 (0.98.20)

**What operating system and version?**
MacOS Sierra 10.12.6

**What did you do?**
**What did you expect to happen?**
**What actually happened?**

First of all, thank you guys for contributing to this awesome torrent client! I love it!
When seeding many torrents (like 30 or more), it would be inconvenient managing these torrents. I think it would be better if I can create folders and subfolders to classify and organize these torrents.

**Comment by feross** [comment]
Thanks for the feature request!

WebTorrent Desktop values simplicity more than most torrent apps. This sometimes means saying 'No' to good ideas. We try to implement only the most important features that a torrent app needs and make those features as good as possible. We don't want the app to get overloaded with knobs and dials that may only benefit a small percentage of users.

That's not to say we won't ever add large new features. We support powerful features like instant streaming, dynamic piece prioritization, web peers (WebRTC), etc. but only when they have a clear benefit to a vast majority of users. See the [80-20 rule](https://en.wikipedia.org/wiki/Pareto_principle).

I don't think it makes sense to implement this feature right now. I hope this makes sense!
