### ISSUE TITLE
webtorrent-desktop command line

### ISSUE THREAD

**Issue by teddybugs** [webtorrent/webtorrent-desktop#1269]
i install webtorrent-desktop on my openvz debian(no gnome/no x):

```
root@pino:/etc/init.d# which webtorrent-desktop
/usr/bin/webtorrent-desktop
root@pino:/etc/init.d# webtorrent-desktop --list
root@pino:/etc/init.d# webtorrent-desktop --help
root@pino:/etc/init.d#
```
how do i add torrent using command line? how to list the seeding torrent and get its magnet url?
i run the webtorrent-desktop command nothing come out.

**Comment by bnjmnt4n** [comment]
Hi, if you're looking to use a CLI version, you should be looking at https://github.com/webtorrent/webtorrent-cli.
