### ISSUE TITLE
Option to permamently delete instead of moving to trash

### ISSUE THREAD

**Issue by aurimus** [webtorrent/webtorrent-desktop#1271]
On Ubuntu 17.04 what happens with newest version of Webtorrent-desktop is that "Remove Data File" moves the downloaded media to trash bin. What I would want is that it was deleted permanently because then I need to go and delete it anyway the second time to free the space.

An option would be great

**Comment by bnjmnt4n** [comment]
We want to keep things simple in the app, so we are avoiding additional configuration, and following system defaults where deleting items sends them to the trash bin.
