### ISSUE TITLE
Not opening on Linux

### ISSUE THREAD

**Issue by bruno-farias** [webtorrent/webtorrent-desktop#1274]
**What version of WebTorrent Desktop?**
v 0.18.0
**What operating system and version?**
Elementary OS 0.4.1 Loki 64 bits (Linux 4.10.0-38-generic) GTK+ 3.18.9
**What did you do?**
Downloaded and installed from official web site
**What did you expect to happen?**
To open and use
**What actually happened?**
Nothing happen, no message, no feedback. It just close itself after show the icon on plank.

**Important:**
Installed v0.17.2 and it is running fine, seen to occur only on v0.18.0

**Comment by bnjmnt4n** [comment]
We seemed to have gotten a similar issue recently. Could you try checking if you downloaded the right version for your system (32/64-bit) ?
