### ISSUE TITLE
WebTorrent (BETA) frozen

### ISSUE THREAD

**Issue by credencem** [webtorrent/webtorrent-desktop#1279]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.18.0 (0.98.5) (64-bit)

**What operating system and version?**
Windows 10, Version 1709

**What did you do?**
Downloading torrents

**What did you expect to happen?**
Finish downloading

**What actually happened?**
Downloading stopped and screen frozen even after restart and end task.

**Comment by feross** [comment]
Can you try to reproduce this error once more? But this time when it happens, click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

If you don't see any errors, then please check in one more place! Click View > Developer > Show WebTorrent Process, select the Console tab and copy-paste all the text.

Being able to see that output would help us out very much. Thanks.
