### ISSUE TITLE
"Show in Finder" often (always) stops working after some time. 

### ISSUE THREAD

**Issue by davidvb** [webtorrent/webtorrent-desktop#1281]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
 0.18.0 (0.98.5)
**What operating system and version?**
10.13.2 Beta (17C85a)
**What did you do?**
"Show in Finder"
**What did you expect to happen?**
I expect the finder to always reveal the downloaded file.
**What actually happened?**
At some point it always stops working for me. Just nothing will happen when requesting to reveal the file in Finder.

**Comment by feross** [comment]
Can you try to reproduce this error once more? But this time when it happens, click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

If you don't see any errors, then please check in one more place! Click View > Developer > Show WebTorrent Process, select the Console tab and copy-paste all the text.

Being able to see that output would help us out very much. Thanks.
