### ISSUE TITLE
Running Scripts in Webtorrent

### ISSUE THREAD

**Issue by ibz096** [webtorrent/webtorrent-desktop#1283]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.18.0 (0.98.5) (64-bit)
**What operating system and version?**
Windows 10 Pro (64-bit)

I was wondering how to run start up scripts in Webtorrent. 

I am looking to create a script to move my files once finished using the web torrent api found in [Webtorrent API](https://webtorrent.io/docs)

I already know how to write the script, I just want to know how run the script automatically on start.
I know i can change the default download location, but I am looking start the next queued torrent when one completes. Something like a queue system so that I can prioritize which torrents get downloaded first.

Thanks :)

**Comment by bnjmnt4n** [comment]
This sounds like a good fit for the plugins system mentioned in #664, which we are in the progress of discussing the details. Closing this issue for now in place of #664.
