### ISSUE TITLE
Huge timesaver: Adding a file TAG or Comment when Download Completes.

### ISSUE THREAD

**Issue by davidvb** [webtorrent/webtorrent-desktop#1288]
**PROBLEM DESCRIPTION / USE CASE**
Often a lot of time is spend on manually keeping track of your download folder. Especially if there was a network disruption/crash/etc it can be problematic to figure out what did-or-did-not finish successfully. 

**SUGGESTED IMPROVEMENT**
Adding a file TAG or (Spotlight) Comment when something successfully finishes downloading, solves the situation explained, saving loads of time. 

— I'd suggest adding something like:
**"_#wt_Download.Finished_"**

And preferably also a time stamp like 
**_#wt_Download Finished_**, **_08.12.2017_**, **_17:46_**

As a result users can further automate their file management themselves, with 3rd party tools or basic  scripts.

**Comment by speedstyle** [comment]
If you are using torrents for general download rather than streaming, it makes much more sense to use a faster, more robust bittorrent client such as transmission.
