### ISSUE TITLE
Can't add magnet links after remove one

### ISSUE THREAD

**Issue by apolloslater** [webtorrent/webtorrent-desktop#1289]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.18.0 (0.98.5) (64-bit)
**What operating system and version?**
Windows 10 Professional
**What did you do?**
Added 2 magnet links, worked fine.  Added 3rd magnet link, it downloaded 50% then stopped.  I removed it.  Could not add any magnet links after that, even if I closed the app & reopened it.
**What did you expect to happen?**
I expected to add a bunch of magnet links.
**What actually happened?**
Could not add magnet links at all after I removed one that stopped downloading.
==>> Was able to get it working again after selecting "Quit" from the System Tray icon and reopening the app.

**Comment by feross** [comment]
Can you try to reproduce this error once more? But this time when it happens, click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

If you don't see any errors, then please check in one more place! Click View > Developer > Show WebTorrent Process, select the Console tab and copy-paste all the text.

Being able to see that output would help us out very much. Thanks.
