### ISSUE TITLE
I can't install it on win10

### ISSUE THREAD

**Issue by Joey1986** [webtorrent/webtorrent-desktop#1292]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
WebTorrentSetup-v0.18.0.exe
**What operating system and version?**
win10 1709
**What did you do?**

**What did you expect to happen?**

**What actually happened?**
can't install
[SquirrelSetup.log](https://github.com/webtorrent/webtorrent-desktop/files/1584860/SquirrelSetup.log)

**Comment by bnjmnt4n** [comment]
I'm not too sure why this error occurs, could you try re-installing too see if there are any differences?

**Comment by farribeiro** [comment]
I think is Bublé package is missing in global
