### ISSUE TITLE
Crash when exit app then start app

### ISSUE THREAD

**Issue by neminovno** [webtorrent/webtorrent-desktop#1294]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
WebTorrentSetup-v0.18.0.exe
**What operating system and version?**
Win 7 64bit
**What did you do?**
Double click to start app, X to exit app, double click to start app.
**What did you expect to happen?**
App should open/start.
**What actually happened?**
App doesn't appear. Windows crash file is created.

App probably does some clean up when exiting? When X is clicked, app is not visible, but maybe it is not closed yet, and when started again, it doesn't run.

Edit: Probably related to "saving state" timeout on [this line](https://github.com/webtorrent/webtorrent-desktop/blob/cae40b44e62423f393199637e970d87cf1414bfa/src/main/index.js#L119) on quitting.

**Comment by feross** [comment]
Are you running the `WebTorrentSetup-v0.18.0.exe` file each time to open the WebTorrent app? That file is an installer. You should only run it once to install the app. Afterwards, you can start WebTorrent by clicking the shortcut on your Desktop or in the "Programs" folder.

**Comment by neminovno** [comment]
The shortcut, of course.

**Comment by feross** [comment]
That's odd. Next time you experience this issue, can you share the crash log that is generated so we can look into this further.
