### ISSUE TITLE
下载不了

### ISSUE THREAD

**Issue by ipz-921** [webtorrent/webtorrent-desktop#1296]
##
windows 7
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
windows 7 64bit
**What operating system and version?** 

**What did you do?**
Double click to start appctrl+v torrentin WebTorrent display Loading torrent 
**What did you expect to happen?** 
App should download file
**What actually happened?**
Torrent Unable to download

**Comment by bnjmnt4n** [comment]
This needs more info in order for us to debug. Also it could be likely that the torrent does not have any seeders. Closing for now, but feel free to ping back with more detailed information.
