### ISSUE TITLE
Lack of node.js version

### ISSUE THREAD

**Issue by fithisux** [webtorrent/webtorrent-desktop#1297]
I tried to install from source for 0.19.0.
I am on windows 10 x64
I tried with latest node.js LTS 8.9.3 x64

Result : npm install seems to end without errors. Packaging fails though.

What is the recommended version of node.js ?

**Comment by feross** [comment]
The latest LTS version of Node.js (8.x) should work. Without any error logs, it's impossible to help you debug this issue.
