### ISSUE TITLE
No response when adding torrent from thepiratebay

### ISSUE THREAD

**Issue by rykel** [webtorrent/webtorrent-desktop#1298]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.18.0(0.98.5)(64-bit)

**What operating system and version?**
Windows 10

**What did you do?**
Drag a .torrent file from thepiratebay.org into WebTorrent Desktop.

**What did you expect to happen?**
Start downloading.

**What actually happened?**
Nothing happened, not even a display of the torrent.

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement. No one will be able to assist you.
