### ISSUE TITLE
external player doesn't work

### ISSUE THREAD

**Issue by alexandre1985** [webtorrent/webtorrent-desktop#1302]
**What version of WebTorrent Desktop?**
0.18

**What operating system and version?**
Manjaro Linux Deepin

**What did you do?**
I could see a video on VLC, then tried other player (mpv) and it didn't work. Then I tried vlc again and it doesn't work
**What did you expect to happen?**
Open VLC and play the video
**What actually happened?**
nothing, it doesn't open the external video player

**Comment by feross** [comment]
What is the path to the VLC binary that you are specifying?

**Comment by alexandre1985** [comment]
It took so much time that I no longer use webtorrents

**Comment by feross** [comment]
@alexandre1985 Sorry to hear that 😢
