### ISSUE TITLE
[Feature]: Option to set destination folder for finished torrents

### ISSUE THREAD

**Issue by alexilyaev** [webtorrent/webtorrent-desktop#1305]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.18.0 (0.98.5)
**What operating system and version?**
Mac OS X 10.12.6
**What did you do?**
Opened WT preferences
**What did you expect to happen?**
See an option to set a destination folder for finished downloads
**What actually happened?**
No such option

I'm actually using WT as an alternative to uTorrent, just cause it's fun.  
But I'm missing the ability to set a destination folder for finished downloads and have to do it manually which is tedious.

**Comment by bnjmnt4n** [comment]
Closing as a duplicate for #917.
