### ISSUE TITLE
MB/s and Mb/s

### ISSUE THREAD

**Issue by sakshamgoyal01** [webtorrent/webtorrent-desktop#1307]
can we get an option to convert the download speeds from MB/s to Mb/s and KB/s to Kb/s please? this will really help me see how much of my internet bandwidth is being consumed by this. this is because ISP's always provide speeds with mega *bits* not mega *bytes*

**Comment by bnjmnt4n** [comment]
We want to keep things simple for WebTorrent Desktop, hence we want to avoid additional configuration, such as this option, which can be confusing without much benefit to most users.
