### ISSUE TITLE
Error packaging for linux

### ISSUE THREAD

**Issue by Albermonte** [webtorrent/webtorrent-desktop#1324]
**What version of WebTorrent Desktop?** 0.19.0

**What did you do?** npm run package linux

**What actually happened?** Can´t package the app

Packaging app for platform linux x64 using electron v1.6.16
Linux: Packaged electron. C:\Users\[...]\webtorrent-desktop\dist\WebTorrent-linux-ia32,C:\Users\[..]\webtorrent-desktop\dist\WebTorrent-linux-x64
Linux: Creating ia32 deb...
path.js:26
function assertPath(path) {
                   ^

RangeError: Maximum call stack size exceeded

**Comment by feross** [comment]
This works for me. Pretty sure that this is something different about your specific system. 
It's not possible to debug this issue without additional information about your OS. If this is still an issue, please leave a comment or open a new issue.
