### ISSUE TITLE
Can't connect to DNLA device in my access point 

### ISSUE THREAD

**Issue by AlejandroC90** [webtorrent/webtorrent-desktop#1327]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.19.0 (0.98.20) (64-bit)

**What operating system and version?**
Arch Linux, all packages up to date

**What did you do?**
Trying to play some music or video on my DLNA Samsung TV

**What did you expect to happen?**
To find my Samsung TV to cast and watch the video

**What actually happened?**
The TV is not recognized and the icon doesn't appears

My computer is wire connected to internet and I use create_ap to create an access point to share internet with my phone and a Samsung TV(2015), I can cast stuff from the phone to the TV and I can use the PC as a DLNA server and browse it in the TV, but webtorrent doesn't find the TV at all, the icon doesn't appear and I can't use it to cast.

**Comment by feross** [comment]
Sounds like there are issues in the DLNA package we use. We'll try updating the dep and push out a new WTD version and see if this fixes it. Without being on your network, it's really hard to debug this. Let us know if you learn any other pertinent details.
