### ISSUE TITLE
Can you add Local peer discovery plugin?

### ISSUE THREAD

**Issue by Ornataweaver** [webtorrent/webtorrent-desktop#1328]
ZeroNet has it.
Local peer discovery plugin added to make ZeroNet work without an internet connection on the local network.
https://zeronet.io/
http://127.0.0.1:43110/Blog.ZeroNetwork.bit/
http://127.0.0.1:43110/Blog.ZeroNetwork.bit/?Post:126:New+version:+0.6.2

**Comment by Ornataweaver** [comment]
[local_peer_discovery.mp4.zip](https://github.com/webtorrent/webtorrent-desktop/files/1733749/local_peer_discovery.mp4.zip) of ZeroNet

**Comment by feross** [comment]
This is a neat suggestion, but it's definitely not a top priority at the moment. If you want to explore making it happen, I would start a discussion on the `webtorrent` repo where this code would likely go

**Comment by Ornataweaver** [comment]
@feross thanks.
