### ISSUE TITLE
Please add subtitle download option

### ISSUE THREAD

**Issue by shamim2018** [webtorrent/webtorrent-desktop#1331]
WebTorrent

Version 0.19.0 (0.98.20) (64-bit)
I am using elementary os Loki
Please add subtitle download option, that will make this player 100% perfect. I am loving it. Superb! Thank you, Mr. Developer.
Greetings.

**Comment by codealchemist** [comment]
Hi @shamim2018!
We won't add subtitle downloading to **WebTorrent Desktop**.
You can refer to the discussion on #677.

Sorry about that.
Still, you can use tools like **dsub** to easily download subs:
https://www.npmjs.com/package/dsub

Cheers!

**Comment by shamim2018** [comment]
Thanks a lot. I am loving Webtorrent Desktop on my Elementary OS Loki <3
Webtorrent is my prized possession.
Cheers!
