### ISSUE TITLE
Try to select the front cover as the poster for audio/music torrents

### ISSUE THREAD

**Issue by Borewit** [webtorrent/webtorrent-desktop#1332]
Improve the poster selection for audio/music based torrent, aiming to get the cover-art selected as the torrent poster. 
 
The poster selection function has an existing _ToDo_, indicating some more work needs to be done for audio based torrents:

https://github.com/webtorrent/webtorrent-desktop/blob/474654fd163f1bf8298b280937453c04b097749b/src/renderer/lib/torrent-poster.js#L22

Downloading the torrent from [the audio album: Parov Stellar - The Princess](https://archive.org/details/ParovPrincess/Parov+Stelar+-+The+Princess/) currently results in the following:
![parovprincess weird poster without music-metadata](https://user-images.githubusercontent.com/23255260/36944841-3462ccd0-1fa4-11e8-80f8-c591aae5c269.png)

**Comment by Borewit** [comment]
It does now select the correct poster in the index:
![parovprincess index with poster](https://user-images.githubusercontent.com/23255260/36945797-78f32c14-1fb3-11e8-8b3d-d57f6e925d20.png)

Playing the same track with this merge:
![parov steller - milla s dream - with poster](https://user-images.githubusercontent.com/23255260/36945839-1c710550-1fb4-11e8-943b-c3a974e9718c.png)

Putting the [music-metadata merge](https://github.com/webtorrent/webtorrent-desktop/pull/1240) (#1240) on top of that would give:
![parov steller - milla s dream - with poster and music-metadata merge](https://user-images.githubusercontent.com/23255260/36945905-f656e67c-1fb4-11e8-902e-750c5b75130f.png)

**Comment by codealchemist** [comment]
Closing after #1334.
