### ISSUE TITLE
Chrome cast on the player not working as what the normal chrome browser does.

### ISSUE THREAD

**Issue by kennethpdev** [webtorrent/webtorrent-desktop#1335]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.19.0 (0.98.21) 

**What operating system and version?**
Windows 7 (64-bit)

**What did you do?**
Click on the Cast button on the lower left of the player.

**What did you expect to happen?**
It should be able to cast the screen on my android TV just like what the Google Chrome [Cast toolbar ](https://support.google.com/chromecast/answer/7249696?hl=en )is doing or is this kind of thing aren't supported yet and you need an actual chrome cast device? I was really expecting to work like the one on the browser. Since you guys using chrome engine via electron isn't this possible yet?

**What actually happened?**
It displayed this error. I think it was searching for a device instead.
![image](https://user-images.githubusercontent.com/1641990/37035113-6bdf7076-2186-11e8-9c19-c4ca081b9689.png)

**Comment by feross** [comment]
To clarify, you're trying to cast from WebTorrent Desktop to an Android device?

I didn't know that was possible. Is this built-in to the OS or are you using a third-party app on the Android device?

Please provide more information on your exact setup so we can attempt to reproduce it.

**Comment by kenma9123** [comment]
@feross yes you can, some AndroidTV(like sony) are capable of doing this without using Chromecast device, so I believe it is built-in to the OS. I don't have to use any apps on the android side. It will just work as it is. It works when I tried to cast the youtube but not this.

**Comment by jibsta** [comment]
I have a vizio TV it has chromecast built in.

**Comment by feross** [comment]
@kenma9123 @jibsta Thanks for your responses.

@mafintosh I see that `chromecasts` is trying to connect to a `.local` URL. Does Windows actually support that type of URL?

**Comment by jibsta** [comment]
I'm sorry man I have no idea at this is a problem with your software. I use
Soda play without issue I use YouTube without issue I use video stream
without issue my Chromecast shows up in web Torrent as a castable object
when I try to cast it that's the error I get

**Comment by feross** [comment]
@jibsta Thanks, the question was for @mafintosh :)

**Comment by nikhilweee** [comment]
@feross and team: Has there been any progress on this issue? I'm having the same problem.
WebTorrent Version 0.20.0 (0.98.21) (64-bit), trying to cast from Windows 10 to a chromecast enabled Android TV.

**Comment by santaclose** [comment]
happening to me rn on windows 10

**Comment by alexpdp7** [comment]
Yeah, also on CentOS Stream 9 casting to a Chromecast with Google TV. I can cast using Chrome fine.

**Comment by alexpdp7** [comment]
Yes, I believe I reproduced the issue again last week.

Maybe build a version with https://github.com/mafintosh/chromecasts/issues/32 ? I could test it to see if it fixes the issue, then we may pursue upstream for a fix.

**Comment by alexpdp7** [comment]
It is still relevant. I could help test a build including the depending library PR to see if it solves the issue. I could try to build this myself, but I'm not familiar at all with this.

**Comment by alexpdp7** [comment]
It is still relevant. I could help test a build including the depending library PR to see if it solves the issue. I could try to build this myself, but I'm not familiar at all with this.

**Comment by alexpdp7** [comment]
It is still relevant. I could help test a build including the depending library PR to see if it solves the issue. I could try to build this myself, but I'm not familiar at all with this.
