### ISSUE TITLE
Error Could Not Connect To Chromecast

### ISSUE THREAD

**Issue by jibsta** [webtorrent/webtorrent-desktop#1336]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

Version 0.19.0 (0.98.21) (64-bit)

**What operating system and version?**
WINDOWS 10 X64
**What did you do?**
Try to Cast a Torrent
**What did you expect to happen?**
should cast 
**What actually happened?**
'Error could not connect to chrome cast : ENOT

![image](https://user-images.githubusercontent.com/37163794/37127823-7b93a16c-2245-11e8-95c0-3af22b71b572.png)

Currently streaming fine to chromecast from sodaplayer

**Comment by alxhotel** [comment]
Duplicate of #1335
