### ISSUE TITLE
Unable to play 

### ISSUE THREAD

**Issue by DoctorChe** [webtorrent/webtorrent-desktop#1338]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.19.0 (0.98.20) (64-bit)
**What operating system and version?**
LinuxMint 18.3 Cinnamon (64-bit)
**What did you do?**
I tried to play video (start steaming button).
**What did you expect to happen?**
Play video.
**What actually happened?**
I can see the label "Unable to play ". And the dialog "Sorry, we can't play that file. Cansel/Install VLC"
But I have VLC already installed.

**Comment by tengbozhang** [comment]
I have the same problem,I used webtorrent desktop to seed a mp4 file of size 1.7G, and neither desktop app nor instant io can play the video, magnet:?xt=urn:btih:c383d7b84473ccee4be30376f50c5592ef7e32d2&dn=%E7%BA%A2%E6%B5%B7%E8%A1%8C%E5%8A%A8.Operation.Red.Sea.2018.WEB-DL.1080P.X265.AAC.Mandarin.CHS.HQC.mp4&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com

**Comment by tengbozhang** [comment]
sorry,It is my fault,I find my video was damaged when I seeded it to the
net.

2018-05-04 6:28 GMT+08:00 Feross Aboukhadijeh <notifications@github.com>:
