### ISSUE TITLE
Multiple file streaming issue

### ISSUE THREAD

**Issue by emma-goldman** [webtorrent/webtorrent-desktop#1342]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.19.0 (0.98.21) (64-bit)
**What operating system and version?**
Windows 10
**What did you do?**
Created a torrent of multiple video files in one folder on desktop at home & server in office which I tried to stream from laptop (remote location). 
**What did you expect to happen?**
To be able to stream any one of the videos in the torrent file from a remote location.
**What actually happened?**
I was able to stream the first one, and begin downloading the other files randomly from remote location - however when I tried to stream any other file than the first one the "Play" button wouldn't work on any of the videos any longer.
 
![play](https://user-images.githubusercontent.com/29815625/37245868-9e2bffb4-2496-11e8-9aa5-db9824537d6a.png)

I can still play the videos from the download location but I have to manually turn off other files in the folder in order to prioritise one, and cannot stream them.

**Comment by feross** [comment]
Can you try to reproduce this error once more? But this time when it happens, click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

If you don't see any errors, then please check in one more place! Click View > Developer > Show WebTorrent Process, select the Console tab and copy-paste all the text.

Being able to see that output would help us out very much. Thanks.
