### ISSUE TITLE
WebTorrent Deskop process hangs on long video sharing list

### ISSUE THREAD

**Issue by atec21** [webtorrent/webtorrent-desktop#1343]
Every time on program start all video files seem to download again although they are already in the file system (I changed the default download directory). After I added about 8 videos, that brings my CPU to 100% and the whole system hangs. I've to kill the webtorrent process.

I would expect that downloaded video files don't begin downloading every time on program startup.

webtorrent-desktop_0.19.0-1_amd64.deb
on Linux Mint 18 Cinnamon 64-bit, Kernel 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017, CPU: AMD Athlon 64 X2 (x86_64)

**Comment by feross** [comment]
They're not re-downloading, they're just being verified, though the UI doesn't indicate that correctly. And technically, while verification is happening, request may be made to peers for the unverified pieces (a known bug: https://github.com/webtorrent/webtorrent/issues/889)

Sorry that your CPU goes to 100%. We're also aware of that issue: https://github.com/webtorrent/webtorrent/issues/903

Please follow those issues for further updates.
