### ISSUE TITLE
Can I change temp folders?

### ISSUE THREAD

**Issue by yexingliang** [webtorrent/webtorrent-desktop#1345]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

**What operating system and version?**

**What did you do?**

**What did you expect to happen?**
I wanna move the temp folder to my HDD disk.
**What actually happened?**

**Comment by feross** [comment]
What's your use case?

WebTorrent always uses your system's temp folder. If you want to change the location, see the instructions for your OS.
