### ISSUE TITLE
[Suggestion] Make please localization!

### ISSUE THREAD

**Issue by electrolom42** [webtorrent/webtorrent-desktop#1348]
**What version of WebTorrent Desktop?**
`v0.19.0`

**What operating system and version?**
`Windows 10 FCU`

**What did you do?**
`Example text for translation >>>` [langRu.txt](https://github.com/webtorrent/webtorrent-desktop/files/1865413/langRu.txt)

**What did you expect to happen?**
`Make please localization!`

**What actually happened?**
`Not enough localization, not everyone knows English!`

# `I really hope that you will listen!`

**Comment by feross** [comment]
We'd love to add more localization. Thanks for contributing that handy Russian translation file. When we get around to implementing this feature, I'm sure it will come in handy.

**Comment by KovalevArtem** [comment]
I am ready to help in the translation into Russian.
(For example, you can use Weblate, Crowdin, or any other service. Free for open source projects.)

**Comment by comradekingu** [comment]
I second Weblate. -1 for Crowdin. Zanata was mentioned in the other thread, but RedHat is moving to Weblate and isn't putting a lot of effort into Zanata.
