### ISSUE TITLE
view download/upload speed graph

### ISSUE THREAD

**Issue by sakshamgoyal01** [webtorrent/webtorrent-desktop#1350]
current version of webtorrent at time of post
windows 10 64bit

please add an option in the view tab to show download/upload speeds for the past 5 seconds, 10 seconds, 1 minute, 5 minute and 30 minute intervals. this would be very helpful to diagnose speed problems

**Comment by feross** [comment]
Thanks for the feature request!

WebTorrent Desktop values simplicity more than most torrent apps. This sometimes means saying 'No' to good ideas. We try to implement only the most important features that a torrent app needs and make those features as good as possible. We don't want the app to get overloaded with knobs and dials that may only benefit a small percentage of users.

That's not to say we won't ever add large new features. We support powerful features like instant streaming, dynamic piece prioritization, web peers (WebRTC), etc. but only when they have a clear benefit to a vast majority of users. See the [80-20 rule](https://en.wikipedia.org/wiki/Pareto_principle).

I don't think it makes sense to implement this feature right now. I hope this makes sense!
