### ISSUE TITLE
Cursor doesn't disappear in VLC (only when using WebTorrent)

### ISSUE THREAD

**Issue by s1h4d0w** [webtorrent/webtorrent-desktop#1352]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.19.0 (0.98.21) (64-bit)
**What operating system and version?**
Windows 10 Professional Version 1709
**What did you do?**
I opened a video file through WebTorrent in VLC, then made it fullscreen
**What did you expect to happen?**
VLC to work as it normally does, hiding the cursor after a few seconds
**What actually happened?**
The cursor never disappears

**Additional information**
This issue only seems to arise when I open files through WebTorrent. If I go to explorer and open the same downloaded file as I would normally do everything works fine and the cursor disappears.

Not to mention VLC staying on top of every window, forcing me to minimize it is lame as hell too. I'm not sure if this is some sort of "modal" mode of VLC and if these issues always arise when opening a file in VLC through another application.

**Comment by pastudan** [comment]
> VLC staying on top of every window, forcing me to minimize it is lame as hell too

+1

Surprised there's not an issue already open for this alone.

**Comment by feross** [comment]
This issue sounds related to the VLC "always on top" behavior. Fixed in #1286.
