### ISSUE TITLE
adding peers information

### ISSUE THREAD

**Issue by AdmASmith** [webtorrent/webtorrent-desktop#1354]
Hi can someone help me here ?

I am trying to add a peer client list (client name,ip, ...) in webtorrent-desktop, but I can not figureout how to access that information ...

I am sorry if this may not sound like a real issue ...

Thanks

**Comment by feross** [comment]
What is your use case for doing that?

WebTorrent Desktop values simplicity more than most torrent apps. This sometimes means saying 'No' to good ideas. We try to implement only the most important features that a torrent app needs and make those features as good as possible. We don't want the app to get overloaded with knobs and dials that may only benefit a small percentage of users.

**Comment by AdmASmith** [comment]
Thank you for the feedback and for providing webtorrent as a free opensource software. I am sorry if my inquiry did not sound like a real issue. Webtorrent is simple and efficient in deed ; I actually learnt a lot from reading the code I as you said it is simple and elegant and I respect that it should stay that way. Thanks again.

**Comment by feross** [comment]
Thanks for understanding, @AdmASmith :) I'm still curious about your use case for adding a list of client IPs from the UI.

If you still need this behavior, you can take a look at core engine: https://github.com/webtorrent/webtorrent which supports a `addPeer()` method.
