### ISSUE TITLE
app opened more times at once for every download

### ISSUE THREAD

**Issue by legacychimera247** [webtorrent/webtorrent-desktop#1358]
**What version of WebTorrent Desktop?** 0.19

**What operating system and version?** fedora workstation 27 with gnome 3.26

**What did you do?** clicked on the download magnet button

**What did you expect to happen?** web torrent to add that magnet to the already opened app

**What actually happened?** the app opened another time so i had 2 webtorrent opened (and so on)

**Comment by feross** [comment]
We only support Ubuntu officially. If you'd like to send a PR to fix this on Fedora, we'll happily take a look at it and merge it if it works and causes no problems. :)
