### ISSUE TITLE
Not working at all. Torrent files could not be added at all. Tried so hard but couldn't :(

### ISSUE THREAD

**Issue by rowansiwakoti** [webtorrent/webtorrent-desktop#1359]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Beta
**What operating system and version?**
Windows 10
**What did you do?**
Trying to download a movie from a torrent site.
**What did you expect to happen?**
I expect that it would download the movie.
**What actually happened?**
The torrent file could not be added to the application :( :( :(

**Comment by feross** [comment]
Can you try to reproduce this error once more? But this time when it happens, click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

If you don't see any errors, then please check in one more place! Click View > Developer > Show WebTorrent Process, select the Console tab and copy-paste all the text.

Being able to see that output would help us out very much. Thanks.
