### ISSUE TITLE
Add Mac Touch Bar Support

### ISSUE THREAD

**Issue by dfanara** [webtorrent/webtorrent-desktop#1363]
I would be interested in adding MacOS Touch Bar support for the mac application. Electron's TouchBar documentation can be found [here](https://github.com/electron/electron/blob/master/docs/api/touch-bar.md) for anyone interested.

My current feature ideas are

- Video Playback 
  - Video scrubbing
  - Play/Pause
  - Enter / Exit full screen
  - An exit button of some sort? To return back to the main torrent page
- Main Page
  - New (Launches the create new torrent window)
  - Add (Expands a list of additional buttons)
    - File
    - Address
    - From Clipboard
  
Any thoughts or feedback? I'm sure there's other prime functionality that i've overlooked that others would find useful, so please feel free to add buttons or offer different name suggestions. All of the button types can be found on the electron documentation found above. 

Mostly just wanted to gauge for any feedback before I worked on it, so if you have any interest in this addition, please give a thumbs up or leave a comment to indicate your interest.

**Comment by feross** [comment]
This sounds great. Want to send a PR?

I don't have a Mac with a Touch Bar, so I don't know what the conventions are for video player apps. I think that mirroring what QuickTime or VLC does makes the most sense for the Video Playback view. The Main Page stuff sounds great.

**Comment by dfanara** [comment]
Sorry, I've been busy with work and have not had time to pursue my idea. If someone else would like to take over the issue that'd be great. If not, I'll keep this project in mind for when things start to slow down!

**Comment by sergiorojasa** [comment]
I would like to work on this issue. If no one else is working on this.

**Comment by Borewit** [comment]
Go for it @sergiorojasa, maybe @dfanara can find a moment review once you got in implemented.

**Comment by martinwheeler** [comment]
Hi, just chiming in to see if anyone is looking into this ATM? I'm happy to jump in and tackle this 🤓

**Comment by Borewit** [comment]
Consider it to be yours @martinwheeler.

I do not own a fancy Mac Touch Bar, so I cannot review it. Maybe someone else can?

**Comment by martinwheeler** [comment]
> Consider it to be yours @martinwheeler.

Thanks!

> I do not own a fancy Mac Touch Bar, so I cannot review it. Maybe someone else can?

I did see that there was a [Touch Bar Simulator](https://github.com/sindresorhus/touch-bar-simulator) mention in the [documentation](https://electronjs.org/docs/api/touch-bar) for adding touch bar components. I'll be using the simulator for development but I'll be testing on my laptop to make sure everything works as intended. Maybe the emulator will suffice for review if no one else has a physical touch bar?

**Comment by martinwheeler** [comment]
Hey @feross @Borewit, not sure who to address this question to.

I'm thinking of copying the QuickTime touch bar buttons for the video playback view as per this screenshot:

<img width="1085" alt="Touch Bar Shot 2019-10-26 at 14 54 20" src="https://user-images.githubusercontent.com/18509578/67761052-a44c1a00-fa96-11e9-8e2b-95a1ac31a1c5.png">

Which just means adding a play/pause button and then scrubber as the rest of the buttons are there by default.

Here is what the touch bar looks like when opening the app at the moment:

<img width="1085" alt="Touch Bar Shot 2019-10-29 at 22 01 33" src="https://user-images.githubusercontent.com/18509578/67761581-af537a00-fa97-11e9-9efc-2686776ad6f8.png">

The extra button you see in the QuickTime screenshot is to open their custom quicktime scrubber. Which I will ignore for now.

For the main page I'll use the items mentioned in the first message:

> - Main Page
>   - New (Launches the create new torrent window)
>   - Add (Expands a list of additional buttons)
>     - File
>     - Address
>     - From Clipboard

These are my assumptions and just wanted to confirm I was on the correct path.

- Main Page
  - New: Performs the same action as the main menu **File -> Create New Torrent...** or CMD + N
  - Add: Tap on it to reveal further sub-buttons which can then be tapped
     - File: Performs the same action as the main menu **File -> Open Torrent File...** or CMD + O
     - Address: Performs the same action as the main menu **File -> Open Torrent Address...** or CMD + U
     - From Clipboard: Performs a paste from the users clipboard. Which will trigger the download if it's a magnet link.

**Comment by feross** [comment]
@martinwheeler Are you still interested in tackling this? Would love to review a PR from you that implements this! In particular the scrubber looks quite useful!

**Comment by martinwheeler** [comment]
> @martinwheeler Are you still interested in tackling this? Would love to review a PR from you that implements this! In particular the scrubber looks quite useful!

Sorry @feross I've taken a step back from development at the moment. I hope someone else is able to pick up this work and implement the scrubber.
