### ISSUE TITLE
Webtorrent disappears 

### ISSUE THREAD

**Issue by holger53** [webtorrent/webtorrent-desktop#1374]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.20.0 (0.98.21) (64-bit)
**What operating system and version?**
windows 10  with 2 monitors
**What did you do?**
Minimized Webtorrent and maximized again
**What did you expect to happen?**
Poping up webtorrent window
**What actually happened?**
Webtorrent appwindow disappears even it's running

**Comment by feross** [comment]
A few questions:

1. Does this happen every time you minimize, or only this once?

2. Have you figured out any way to get the window to show up? If you do, you follow these instructions the next time it happens. Click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

If you don't see any errors, then please check in one more place! Click View > Developer > Show WebTorrent Process, select the Console tab and copy-paste all the text.

Being able to see that output would help us out very much. Thanks.
