### ISSUE TITLE
Torrents freeze after a while

### ISSUE THREAD

**Issue by s1h4d0w** [webtorrent/webtorrent-desktop#1375]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.18.0 (0.98.5) (64-bit)

**What operating system and version?**
Windows 10 Professional build 1709

**What did you do?**
I wanted to download a torrent

**What did you expect to happen?**
The torrent downloading and finishing

**What actually happened?**
Torrents seems to freeze and get stuck. It's stuck on 98%, says it's connected to 53 peers and is downloading with 19MB/s, however, it's been suck on that for a while now. Nothing changes, not even the downloadspeed. WebTorrent itself seems to still be running fine, I can pause and resume the torrent, but if I resume it it immediately jumps back to the 98%, 53 peers and 19MB/s and never changes. I checked the console but I can't see any errors.

This started happening on my home PC last week, causing me to have to say goodbye to WebTorrent, but it's now also happening on my work PC. Different PCs, different torrents, etc.

**Comment by feross** [comment]
Can you try to reproduce this error once more? But this time when it happens, click View > Developer > Show WebTorrent Process, select the Console tab and copy-paste all the text.

Being able to see that output would help us out very much. Thanks.

**Comment by Bernitall** [comment]
The same thing has started happening with me.
One difference is that I'm using Webtorrent Version 0.20.0 (0.98.21) (64-bit) but beyond that, I'm looking at exactly the same issue.
And console shows nothing, no text at all.

A quick addition, just now I paused the torrent and unpaused it, to see if maybe that would make the console show anything.
Still nothing in the console, and additionally, in the main WebTorrent screen the torrent itself shows the active state (peers, speed and such) while still being frozen, but now pausing and unpausing no longer seems to put that little checkmark in the box for the torrent, it just keeps displaying an empty checkbox.

**Comment by s1h4d0w** [comment]
Sorry for the late reply, the console showed nothing, just like @Bernitall reported. His issue seems to be the exact same one I'm having and he's provided some more detailed information. Could this please be reopened?

**Comment by Defirence** [comment]
I'm also having the same issue, restarting WebTorrent seems to help. The info that pops up in the console is exactly the same as @Bernitall is experiencing.

**Comment by Lew-Rockwell-Fan** [comment]
I've also found that I can click a little to the left and below the play button an a report will open below that shows 100% instead of 99.

**Comment by Lew-Rockwell-Fan** [comment]
Prevention:
I've found I have a lot less problems if I never try to torrent more than 6 files at a time. 

Fixing it when it quits working:.
With a pristine installation, copy the config directory, preserving ownership & perms to a backup.`
When it breaks, shut it down, kill any remaining processes. Kill it however you can. Totally.
Then delete the config dir & restore it from the backup.

Works for me.

**Comment by s1h4d0w** [comment]
Not really much of a fix, a bit too much trouble for me. I guess I’ll stay on Deluge until it’s fixed.

**Comment by Lew-Rockwell-Fan** [comment]
Correct me if I'm wrong, but Deluge doesn't work with webtorrents, only traditional torrents. So, for example, it's of no use with bitchute, which is probably the primary use case for this. If I'm wrong, please point me to documentation on  how to use Deluge for this.

**Comment by s1h4d0w** [comment]
> Correct me if I'm wrong, but Deluge doesn't work with webtorrents, only traditional torrents. So, for example, it's of no use with bitchute, which is probably the primary use case for this. If I'm wrong, please point me to documentation on how to use Deluge for this.

Seeing as this has been reopened, I've never used Bitchute. I'm just here to download some public domain movies and would like to watch them while downloading, but seeing as WebTorrent has had these issues I've had to switch over to downloading them the good old fashioned way and waiting until it's finished.

**Comment by onlineth** [comment]
Agreed, this continues to be an issue

**Comment by Lew-Rockwell-Fan** [comment]
My 2 solutions still work for me. I haven't had to use the fix since I discovered the prevention over a year ago.  Both of which are simple enough they could be added to webtorrent itself if need be.  I just downloaded the new version.  I'll see how it works.
