### ISSUE TITLE
Media control area continuously appear/disappear 

### ISSUE THREAD

**Issue by mikkelsiggaard** [webtorrent/webtorrent-desktop#1376]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.19.0 (0.98.21) (64-bit) 

**What operating system and version?**
Windows 10 Home 64-bit

**What did you do?**
Was sitting in my underwear watching that episode of Homeland where Carrie goes to Russia :smiley: 

**What did you expect to happen?**
Media control area (previous, play and next-buttons etc.) to not keep appearing and disappearing. 

**What actually happened?**
When placing the mouse inside the window (either in fullscreen or not) the media control area is appearing and disappearing with regular intervals (about 5 second) without moving the mouse. 

When placing the mouse cursor outside the window the media control area is never shown.

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement. No one will be able to assist you.
