### ISSUE TITLE
Dependency Out Of Date

### ISSUE THREAD

**Issue by zero77** [webtorrent/webtorrent-desktop#1377]
The Squirrel dependency is out of date by a few versions also, it should update automatically alongside webtorrent.

https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/getting-started/1-integrating.md#basic-squirrelwindows-update-code

**Comment by feross** [comment]
@zero77 Unless I'm missing something, this is expected. We're using an older version of Electron at the moment. That includes an old version of Squirrel. Once we update Electron, we should get the newer Squirrel. LMK if this is not what you meant.
