### ISSUE TITLE
Irrelevantly high download statistic and 0 reported upload

### ISSUE THREAD

**Issue by kireerik** [webtorrent/webtorrent-desktop#1382]
WebTorrent Desktop produces irrelevantly high download statistics over time on the torrent site that I am using.
Also the statistics show 0 upload when I am using WebTorrent Desktop, however it is seeding. I think WebTorrent Desktop doesn't reports it.

related comment: https://github.com/webtorrent/webtorrent/issues/806#issuecomment-272328932

**What version of WebTorrent Desktop?**
Version 0.20.0 (0.98.21) (64-bit)

**What operating system and version?**
Windows 10 1803

**Comment by feross** [comment]
This caused by the CPU being overloaded. It's a known issue. We'll work on getting it fixed eventually. Thanks for opening this issue.

**Comment by kireerik** [comment]
Oh I see. I think in this case we should keep this issue opened until it is resolved.

By the way I am not experiencing high CPU usage.

**Comment by feross** [comment]
If you're never seeing any upload and CPU utilization is low, then that could also be caused by your NAT blocking incoming connections.

You'll need to wait until we have port mapping added. You can follow this issue: https://github.com/webtorrent/webtorrent/issues/195

**Comment by kireerik** [comment]
Thank you! I think you are right.

I have subscribed to the mentioned issue.
