### ISSUE TITLE
hash values, gpg sigs?

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [webtorrent/webtorrent-desktop#1388]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.20.0-1_amd64
**What operating system and version?**
linux buntu 16.04
**What did you do?**
downloaded, looked for a hash value & signature

**What did you expect to happen?**
Find both

**What actually happened?**
Didn't.

**Comment by feross** [comment]
We can generate hashes at build time and include them in an additional file in the release.

**Comment by Lew-Rockwell-Fan** [comment]
A hash in a GPG SIGNED text file seems kinda basic. Guess I'll pass until then. Thanks.

**Comment by feross** [comment]
The Windows and macOS binaries are code signed with a certificate that is trusted by your OS. If you wish, you can verify that in the meantime.

**Comment by feross** [comment]
Duplicate of https://github.com/webtorrent/webtorrent-desktop/issues/1388
