### ISSUE TITLE
auto-update doesnt work in ubuntu

### ISSUE THREAD

**Issue by 12345dom** [webtorrent/webtorrent-desktop#1391]
webtorrent 0.19 shows me a update available, but it doesnt auto-update in ubuntu 18.04

**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

**What operating system and version?**

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by feross** [comment]
Yep, this is a known issue. Electron didn't support an autoupdater on Linux when we wrote that feature of the app. However, this may be changing in a future version of Electron and we'll consider adding autoupdating support when/if that happens. 

Thanks for opening this issue.
