### ISSUE TITLE
Malicious traffic detected in the Helper.app

### ISSUE THREAD

**Issue by siemvaessen** [webtorrent/webtorrent-desktop#1392]
Sophos picks up on a threat in the helper:

Malicious traffic detected: 'C2/Generic-A' at '/Applications/WebTorrent.app/Contents/Frameworks/WebTorrent Helper.app/Contents/MacOS/WebTorrent Helper' (Technical Support reference: 870278347)

**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

Version 0.20.0 (0.99.3)

**What operating system and version?**

Mac 10.13.4 (17E199)

**What did you do?**

Running a torrent, happens instantly

**What did you expect to happen?**

Well, not this

**What actually happened?**

Started webtorrent, added a torrent, got flagged by Sophos.

Malicious traffic detected: 'C2/Generic-A' at '/Applications/WebTorrent.app/Contents/Frameworks/WebTorrent Helper.app/Contents/MacOS/WebTorrent Helper' (Technical Support reference: 870278347)

But read the C2/Generic-A may be a false flag, not sure,

**Comment by feross** [comment]
@siemvaessen Thanks for the report. This sounds serious, so let's get to the bottom of it. I hope you're willing to answer the following questions so we can figure this out.

- Does this happen when you add any torrent? Or just when you add certain specific ones? **Please remove all torrents from the app, then add one of the torrents from this page (https://webtorrent.io/free-torrents) and let me know if you still get the Sophos alert.**

Thanks!

---

My current guess is that the torrent you added has a tracker server that Sophos believes is infected with malware, so it is blocking the connection to that server. The Sophos page on [C2/Generic-A](https://www.sophos.com/en-us/threat-center/threat-analyses/viruses-and-spyware/C2~Generic-A.aspx) says:

> C2/Generic-A is the threat name associated with the command and control (C&C) servers used by malware. Note: C2/Generic-A is not detection of a malware payload on an infected machine. Instead it indicates Sophos products blocking network traffic (reputation or IPS filtering) to a remote machine believed to be a C&C server. The alert indicates that a machine within the network is compromised with malware.

**Comment by siemvaessen** [comment]
Hi @feross ~ this only happens with some torrents, not all. I can confirm the free-torrents you refer to do not have this issue. So we can conclude this only happens with some torrents. The message also only pops up upon **playout**, so nothing on **download**. Once play button is activated and playout starts message popsup and webtorrent desktop is also frozen. Need to restart webtorrent and I noticed upon 2nd or 3rd time playout Sophos is no longer making mention of this.  I will check logs next time and see if that helps. 

I also read  C2/Generic-A has had some false positives flags over the years.

**Comment by feross** [comment]
This seems like a false positive to me. Perhaps Sophos is flagging the local HTTP server that we start for HTTP video playback into the `<video>` tag?
