### ISSUE TITLE
Add YouTube-style keyboard shortcuts

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent-desktop#1395]
Let's consider adding the basic YouTube keyboard shortcuts in addition to the VLC ones that we already support. I don't think they conflict and they're familiar to lots of people.

Left/Right arrows - seek back/forward 5 seconds
Up/Down arrows - volume up/down 5%
<kbd>j</kbd> or <kbd>l</kbd> - seek back/forward 10 seconds
<kbd>k</kbd> - play/pause
<kbd>Shift</kbd> + <kbd>></kbd> - Increase speed
<kbd>Shift</kbd> + <kbd><</kbd> - Decrease speed

**Comment by sergiorojasa** [comment]
I would like to work on this issue.

**Comment by mathiasvr** [comment]
IMO we should not have multiple shortcuts for the same action, but I think it's fine to change the shortcuts for seeking and volume to single arrow presses.
