### ISSUE TITLE
External player can not be changed from VLC. (Windows and Linux.)

### ISSUE THREAD

**Issue by Azza-NZ** [webtorrent/webtorrent-desktop#1402]
**What version of WebTorrent Desktop?**
Version 0.20.0 (0.99.3) (64-bit) on Fedora and Version 0.20.0 (0.98.21) (64-bit) on Windows..
**What operating system and version?**
Fedora 28 (GNOME) and Windows 10 1803
**What did you do?**
Attempted to change external player through the GUI menu option and then (when unsuccessful) by config file.
**What did you expect to happen?**
New videos to open in chosen media player.
**What actually happened?**
No change to the external player. Continues to say "VLC".

**Comment by feross** [comment]
Can you try to reproduce this issue once more? But this time when it happens, click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

If you don't see any errors, then please check in one more place! Click View > Developer > Show WebTorrent Process, select the Console tab and copy-paste all the text.

Being able to see that output would help us out very much. Thanks.

**Comment by Azza-NZ** [comment]
It looks like it does change in Windows, nothing changes at first (still says "VLC" with no path) but if you close and reopen it it will have the path of the path of a the new player, and works as expected. I don't have access to my Fedora machine at the moment, will update soon. Thanks fort the reply.

**Comment by feross** [comment]
It seems like we have a state bug where the UI isn't reflecting the internal state correctly.

**Comment by mathiasvr** [comment]
This should be fixed by #1042.
