### ISSUE TITLE
Drop in speed after a while, restart WebTorrent solve it.

### ISSUE THREAD

**Issue by moshest** [webtorrent/webtorrent-desktop#1403]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.20.0
**What operating system and version?**
MacOS 10.13.4 (17E202)
**What did you do?**
Download a large torrent file from magnet link (13GB)
**What did you expect to happen?**
Download in a constant speed.
**What actually happened?**
When the torrent start, it's download on 4-6 MB/s. Sometimes, after a few minutes, the speed can goes even below 500 KB/s. Restarting WebTorrent immediately start download in the max. speed again.

Maybe some peers flagged as bad accidentally?
I encountered the same problem with PopcornTime also, does WebTorrent use the same libraries?

**Comment by feross** [comment]
Thanks for opening this issue. Performance is a known issue that we're planning to improve. We already have several issues open regarding this issue, so I'm going to close this one.
