### ISSUE TITLE
Webtorrent freeze often

### ISSUE THREAD

**Issue by WarcraftAcc** [webtorrent/webtorrent-desktop#1404]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.20.0 (0.98.21) (64bit)
**What operating system and version?**
windows 10 pro (version 1709) (os build 16299.431)
**What did you do?**
Download a mp4 file.
**What did you expect to happen?**
Normal download of the file.
**What actually happened?**
Webtorrent froze (download stoped, playback/stream stoped, everything just stood in place) - happens quite often

**Comment by feross** [comment]
Can you try to reproduce this error once more? But this time when it happens, click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

If you don't see any errors, then please check in one more place! Click View > Developer > Show WebTorrent Process, select the Console tab and copy-paste all the text.

Being able to see that output would help us out very much. Thanks.
