### ISSUE TITLE
WebTorrent doesn't unminimize on Windows 10

### ISSUE THREAD

**Issue by ghost** [webtorrent/webtorrent-desktop#1416]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

**What operating system and version?** Windows 10

**What did you do?** Clicked Icon

**What did you expect to happen?** Open WebTorrent

**What actually happened?** Nothing!

**Comment by Borewit** [comment]
Can you please be more specific, which version did you try to start?
Did it run before?
Are you confident it is not caused by some issue on your end?

**Comment by feross** [comment]
Did WebTorrent used to work for you, or is this a brand new installation?

**Comment by jraspiprojects** [comment]
brand new installation

**Comment by leytpapas** [comment]
I've experienced this before with a slight change in the facts. 
(windows OS) The window could actually 'un-minimize' but it was off-screen and while I could verify with various ways that it was there I couldn't bring it back, mouse of course couldnt reach the bar to click-n-drag it. 
My solution was to move it in-screen using shortcuts.

> **Alt-Spacebar - R** for restoring if maximized
> **Alt-Spacebar - M**  and then move with up-down-right-left keys to move it in a place that it can be seen, then hit enter to finish moving

I haven't found the reason it happens yet but I have seen in in more than one installations

**Comment by hicom150** [comment]
I could not reproduce any failure in the latest version of WebTorrent, so probably we have fixed this when updating electron 😅

**Comment by nwclaesson** [comment]
I have this problem and what "leytpapas commented on Oct 2, 2018" worked for me.
