### ISSUE TITLE
Remove downloads with missing file

### ISSUE THREAD

**Issue by Paxa** [webtorrent/webtorrent-desktop#1426]
I usually remove files after watching them (to free the space) and now I have very long list of past downloads in webtorrent.

Would it be nice to add feature to remove downloads that missing a file or folder?

**Comment by RecoX** [comment]
Any bittorrent client does that, all the clients has the option Delete torrent and data but if the client detect there is a missing file it will download it

**Comment by Paxa** [comment]
In my case, I download several files, pause seeding when complete, laster delete that files from disk but lazy to delete one by one from webtorrent...
and now I have really long list of past downloads

**Comment by mathiasvr** [comment]
In my opinion the client should not automatically remove the torrent if the file is missing.

It would be nice to provide an easier way to re-download missing data, compared to the current implementation where you must remove and add the torrent again. However, that is a different issue.

@Paxa I suggest that you use the "Remove Data File" option by right clicking a torrent, to delete both the files and torrent in a single action. Hope that's okay with you.

**Comment by Paxa** [comment]
I had more then a hundred files in a history... end up reinstalling webtorrent

**Comment by Paxa** [comment]
my idea - not deleting automatically but to add button somewhere to detect and delete torrents with missing data files.

Btw in what scenarios we may have missing file and wish it to be re-downloaded automatically?

Also I think there is a bug: add torrent via link, wait till it get name and file names, pause, unpause, and it shows error: missing file, please remove and add again

**Comment by RecoX** [comment]
Yes is totally possible add a button to delete all the torrents and torrent files where the torrent has missing file/data/corrupt.

About the bug you mention  I will try to reproduce it.
