### ISSUE TITLE
Update option with infohash

### ISSUE THREAD

**Issue by tarbib** [webtorrent/webtorrent-desktop#1427]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.19.0 (0.98.21) (64-bit)
**What operating system and version?**
Windows 10
**What did you do?**
I clicked on help to check for updates and did not find anything
**What did you expect to happen?**
I expected to find a check for updates
**What actually happened?**
I went on the official website but the connection is not good with Github from China

So I was wondering if the new releases of Webtorrent could be on webtorrent so that I only click on update and it will add the infohash to my current version of webtorrent for downloading and upgrade.
Additionally, it would great to have the infohash in there : 
https://github.com/webtorrent/webtorrent-desktop/releases

**Comment by feross** [comment]
WebTorrent automatically keeps itself up-to-date. You don't have to manually check for updates!
