### ISSUE TITLE
Ubuntu 18.04 (Gnome) no indicator icon.

### ISSUE THREAD

**Issue by tiotrom** [webtorrent/webtorrent-desktop#1430]
I can open webtorrent just fine but there is no indicator icon for Ubuntu 18.04 so if I will close the program or minimize, I'll lose it forever without being able to bring it back unless I open another instance of webtorrent and close the old one from System Manager. This makes the Webtorrent unusable.

**Comment by feross** [comment]
I believe the indicator icon used to work at one point in time on Ubuntu. Perhaps this is broke because we're on old Electron? This should hopefully be fixed when we release 0.21.0.

**Comment by thevirajshelke** [comment]
@feross I have cloned the master branch and have checked the application. I think it works perfectly fine on Ubuntu 18.04.3. When you close the application it runs in the background and you can see the indicator icon too. When you click the indicator icon you can see the option to show the application again or quit.

@tiotrom I think like @feross said this should work in the next release i.e. 0.21.0

I think we can close this issue as well :) :+1:

**Comment by feross** [comment]
Closing. Follow https://github.com/webtorrent/webtorrent-desktop/issues/1674 for updates on the release.
