### ISSUE TITLE
WebTorrent not opening in macOS Mojave 10.14

### ISSUE THREAD

**Issue by hellosaumil** [webtorrent/webtorrent-desktop#1432]
WebTorrent Version : 0.20.0

OS: macOS Mojave 10.14

It opens with an alert dialog box saying, **The last time you opened WebTorrent, it unexpectedly quit while reopening windows. Do you want to try to reopen its windows again?**
**If you choose not to reopen windows, you may have to open and position the windows yourself.**

Even if I press, **Don't Reopen** or **Reopen Windows**, it _crashes_.

**Comment by melgu** [comment]
I don't get said dialog box, but it crashes on me as well. It starts to play the welcome sound and shows the UI, but crashes before the sound was fully played.

**Comment by ETHANAIR** [comment]
same problem

**Comment by jonkoops** [comment]
This issue was already reported in #1421, please close this issue and provide further feedback there.

**Comment by MoOx** [comment]
Working with latest Mojave (beta 7). Can be closed.
