### ISSUE TITLE
resume/pause selected torrent

### ISSUE THREAD

**Issue by mxshahid** [webtorrent/webtorrent-desktop#1433]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.20
**What operating system and version?**
Win 10 - 64bit
**What did you do?**
i tried to pause selected torrent but there is no option for that
**What did you expect to happen?**
pause on the torrent that i need to select
**What actually happened?**
nothing

**Comment by jonkoops** [comment]
You can pause a torrent by pressing the checkbox next to the information about the status (see screenshot). Perhaps this could be better communicated in the design.

<img width="131" alt="screen shot 2018-07-11 at 21 29 07" src="https://user-images.githubusercontent.com/695720/42595136-8e0cc340-8551-11e8-9ec7-37a4efb551d2.png">

**Comment by mxshahid** [comment]
OMG thanks i didn't noticed this option my whole life..

**Comment by codealchemist** [comment]
Thanks for your help @jonkoops :)
Closing this issue.

Cheers!
