### ISSUE TITLE
Router overload

### ISSUE THREAD

**Issue by SerraCabo** [webtorrent/webtorrent-desktop#1441]
Version 0.20.0 (0.98.21) (64-bit)

W7/64

Although as much as I understand, Webtorrent only seeds a video if it is also opened in a browser (one tab for each video ... not possible to open dozens of videos). Although Webtorrent sits there and does not seed because I can't keep opened (browser) many videos (no up arrow), it generates traffic to a point where it overloads the router. 

If Webtorrent can't seed previously pasted torrent files (videos) by itself, it seems quite useless.

Thanks
SC

**Comment by mathiasvr** [comment]
I'm not exactly sure about what issue you are describing.

This repository is concerned with the WebTorrent desktop client, which can seed torrents both through the original BitTorrent network and a browser (WebRTC) based network.

If you are referring to the WebTorrent library for the browser, you can open an issue at https://github.com/webtorrent/webtorrent, but please provide a more detailed description of the problem if you do so, thanks.
