### ISSUE TITLE
Play/Pause at the end of watching a torrent

### ISSUE THREAD

**Issue by ankitlodha87** [webtorrent/webtorrent-desktop#1445]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.20.0 (0.99.3)
**What operating system and version?**
OSX 10.11.6 El Capitan
**What did you do?**
After watching a torrent, tried to play the next torrent
**What did you expect to happen?**
Expected the next torrent to play by pressing the play button
**What actually happened?**
The play button wasn't getting highlighted when the mouse would hover over it, and it wouldn't play, need to close and restart the app to be able to play the next torrent file.

**Comment by mathiasvr** [comment]
I have not been able to reproduce this issue, i'm using same OS version and WebTorrent version.

Do you happen to refer to the "play next" button, which I have circled here:

![untitled](https://user-images.githubusercontent.com/8664776/45703373-6d59c400-bb74-11e8-9b69-d8d5e2251069.png)

This button can only skip to the next playable file in the same torrent, and not skip to different torrents. For this you have to go back to the main screen and play another torrent.

I suspect this might not actually be the issue you describe, so feel free to reopen if this is still a problem.
