### ISSUE TITLE
Open to not download movie and just stream it like Popcorn Time?

### ISSUE THREAD

**Issue by coreybruce** [webtorrent/webtorrent-desktop#1446]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.1.3
**What operating system and version?**
Linux 
**What did you do?**
Watch a movie
**What did you expect to happen?**
Just stream the movie and not download the whole movie taking hard drive space, downloading should be a option
**What actually happened?**
Downloaded the movie even tho I didn't want it to.

**Comment by SilentBot1** [comment]
@coreybruce, 

Reading through the source of popcorn-desktop, you can see [here](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/streamer.js#L103) that popcorn-desktop does indeed download the entire selected file to disk, specifically to the path `path.join(os.tmpDir(), 'Popcorn-Time')`.

Popcorn-desktop promotes piracy, which isn't welcome here, please do not use WebTorrent for copyright infringement.

**Comment by coreybruce** [comment]
Th is wasn't using piracy, if I used the video torrent example for your website it would do the same also does it save the video temporarily as chunks than deletes it or does it save the vide oas a whole mp4 file?

**Comment by SilentBot1** [comment]
@coreybruce, 

Apologies, I didn't intend the message to come off as If I was accusing you of copyright infringement, I was just stating that outside of disusing the technical aspects of Popcorn-desktop, the actual content it serves isn't welcome.

I'll answer your question here as it's easier than making a new issue just for a question, though it does belong in [WebTorrent](https://github.com/webtorrent/webtorrent)'s issue tracker.

> if I used the video torrent example for your website it would do the same also does it save the video temporarily as chunks than deletes it or does it save the video as a whole mp4 file?

If you're asking in regards to WebTorrent in the browser, by default it stores the entire file in memory as chunks using [memory-chunk-store](https://github.com/mafintosh/memory-chunk-store), these chunks can be then converted into a Blob / Buffer or ReadStream containing the entire file.

**Comment by coreybruce** [comment]
From what I have heard that for example Popcorn Time downloads the movie than removes it after, does this do that?

**Comment by SilentBot1** [comment]
@coreybruce,

WebTorrent-Desktop downloads the files to a specified location, which can be set in the preferences. There is an option when you right-click on a download to `Remove Data File` which will remove the torrent and all the downloaded files.

**Comment by coreybruce** [comment]
will there be a option to auto remove it if you didn't want it at all in the future?

**Comment by SilentBot1** [comment]
@coreybruce, 

Can you clarify what you mean by auto remove, as in removing the torrent once you've reached the end, remove the torrent once you exit it or something else?

It's one one extra click to use the `Remove Data File` option over just removing the torrent from the client, I think it would be a nice ease of use option but not critical to implement.

**Comment by coreybruce** [comment]
Yes either remove it when I am done or close and yes it is but not every user is going to know they have to do this for examples very new computer users and it should be a automatic option especially when this application is for torrent steaming not torrent downloading otherwise this would be a totally different application with a different purposes not to mention other streaming apps do this by default anyways so I don't see why it shouldn't be a part of the steaming app

**Comment by SilentBot1** [comment]
@coreybruce,

Leeching torrents without seeding back would overall have a detrimental effect on both the BitTorrent and WebTorrent networks.

If you would like this feature, feel free to make a feature request on the issue tracker and gather feedback from the rest of the community about the feature.

**Comment by coreybruce** [comment]
Doesn't it already technically do that since all it does is download the file while streaming than doesn't continue to seed anyways? 

Alright thanks I will!

**Comment by SilentBot1** [comment]
@coreybruce,

Think of WebTorrent-Desktop as a torrent client, but with the ability to playback the media in real time, including seeking, instead of having to wait till the download is complete before playback occurs.

It will continue to seed while you have the application open in the background without removing the torrent from the application.

**Comment by coreybruce** [comment]
Ahh I see so it is more of a client with video playback, it is a really cool client. 😊
