### ISSUE TITLE
Fetching subtitles automatically

### ISSUE THREAD

**Issue by vladamx** [webtorrent/webtorrent-desktop#1455]
Is there any interest in implementing this?
Maybe I can do it.

I spend so much time in finding and downloading subs. 
While I do this, the file is already downloaded, in most cases, and I can use my player to pull subs immediately.

The act of manually finding subs defeats the purpose of using the streaming client in the first place.

**Comment by mathiasvr** [comment]
This has been discussed multiple times before, see for example #1156.
It was decided to implement subtitle download as a plugin, however plugin support will probably not be added in the near future.
