### ISSUE TITLE
Add .Mkv format support

### ISSUE THREAD

**Issue by Shankymahajan** [webtorrent/webtorrent-desktop#1458]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.20
**What operating system and version?**
mac OS mojave
**What did you do?**
Played .MKV

**What actually happened?**
played on vlc

Can We please add support to of .mkv video format . it's quite popular to compress full HD videos.

**Comment by mathiasvr** [comment]
MKV is a container format, which means it is used to embed content such as video and audio.
The MKV format is already supported, however support for the actual video or audio data (contained in the MKV file) depends on which codec it uses (this it what decides compression, etc.).

This is a known issue #1389.
Currently webtorrent-desktop is limited by the codec support of chromium, unless using an external player.
