### ISSUE TITLE
Stop Sound effect

### ISSUE THREAD

**Issue by Shankymahajan** [webtorrent/webtorrent-desktop#1459]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.20

Usually, I delete many torrent files together and it is quite annoying when I always hear the sound effect. Can we give the preference to the user to mute/disable the sounds for the app?

**Comment by mathiasvr** [comment]
The sound effects have subject to previous discussions.

Let's move the conversation to #1067, to track this issue and possible solutions in one place.
