### ISSUE TITLE
SMPlayer has no title and won't play from previous position

### ISSUE THREAD

**Issue by janat08** [webtorrent/webtorrent-desktop#1460]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
 0.20.0 (0.98.21)

**What operating system and version?**
windows 10, 1803

**What did you do?**
use smplayer as external player, start playback from webtorrent menu

**What did you expect to happen?**
for video title to appear in top bar, and for playback to resume from previous position as it does when launched manually.

**What actually happened?**
displays 0 for video title, and start from beginning

**Comment by mathiasvr** [comment]
Related to #1349.

**Comment by feross** [comment]
Fixed by https://github.com/webtorrent/webtorrent-desktop/pull/1648
