### ISSUE TITLE
The main windows get minimized forever

### ISSUE THREAD

**Issue by sardea930** [webtorrent/webtorrent-desktop#1471]
**What version of WebTorrent Desktop?** 
             Last beta  Version 0.20.0 (0.98.21) (64-bit)

**What operating system and version?**
             Windows 10 home premium 64bits

**What did you do?**
             Few days ago the app crashed and when I was opening web torrent again, it still minimized forever, no mater what buttons I press, I have tried to change bettween desktops, open and close the app many times, restarting the PC, but nothing works any time I try to open it, it keeps minimized.
         
**What did you expect to happen?**
              Maximize the main window

**What actually happened?**
              The app did not  maximize at all

**Comment by mathiasvr** [comment]
This might be related to #1416.

**Comment by sardea930** [comment]
What is #1416?
