### ISSUE TITLE
无法通过paste 进行下载

### ISSUE THREAD

**Issue by guyuewuren** [webtorrent/webtorrent-desktop#1473]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

**What operating system and version?**

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by jimmywarting** [comment]
translation: Unable to download via paste

**Comment by mathiasvr** [comment]
You can paste a magnet link or torrent url to start the download.
You cannot copy and paste a local torrent file, but must instead drag or open it with webtorrent-desktop.

Please provide a detailed description of the issue, if this does not answer your question.
