### ISSUE TITLE
magnet link string convertable into something usable in the watch directory?

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [webtorrent/webtorrent-desktop#1479]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
webtorrent-desktop_0.20.0-1_amd64.deb
**What operating system and version?**
minimalist Ubuntu 18.04 LTS made from the mini.iso with X, lightdm, and Openbox, no further DE

This is more in the nature of 2 related questions than a bug, but if there is a users' forum or some better place to post it, I'd appreciate a link. The point of both questions is the same. I'm working on a script to invoke with a link to a bitchute video page as the argument, which extracts the magnet link, a suitable string to use as a title, passes the magnet to webtorrent-desktop, waits for the WT-D to create the file locally (which will  have a cryptic name), and then create as symlink to it with the title string in another directory. So I can continue to seed files but I'll still have a directory with human understandable titles to browse and load into a media player. But using the `webtorrent-desktop "$mag_link"` nomenclature, if I let the script exit once the symlink is created, webtorrent-desktop closes, no matter how hard I try to disown it. So I have to end it with something like `read` so the script won't exit. That means every time I add a file to torrent, I get another useless process. Maybe I shouldn't have started with the gui, but it does work, except for this one flaw.

If I have a string like this:

`magnet:?xt=urn:btih:60f1cc153737cdbb1eeffe9b358bcbe74116fb63&dn=QW6pNdtxcWQz.mp4&tr=udp://explodie.org:6969&tr=udp://tracker.coppersurfer.tk:6969&tr=udp://tracker.empire-js.us:1337&tr=udp://tracker.leechers-paradise.org:6969&tr=udp://tracker.opentrackr.org:1337&tr=wss://tracker.openwebtorrent.com&as=https://seed21.bitchute.com/ZGmFnHWkjns0/QW6pNdtxcWQz.mp4&xs=https://www.bitchute.com/torrent/ZGmFnHWkjns0/QW6pNdtxcWQz.webtorrent`

I can feed it to webtorrent-desktop as an argument in a script & it works fine, adding it to the list if WT-D is already running, or starting it if it isn't. But there is a setting to watch a directory for added torrents. If I use that, is there a way to turn that string into a file that I can paste into (or create in) that directory? Because the script wouldn't be talking directly to webtorrent-desktop, but just creating a file, so presumably it could exit.

Alternately, is there an effective way to disown webtorrent-desktop from a script once you've started it?  I've tried the usual things both separately, & in combinations like this:

(nohup webtorrent-desktop $mag_link &) &
disown $!

I've also put the command string in another script & disowning THAT, scattering more sleeps than the sand man, and so on, but anyway I've tried it, it still closes when the  script closes. I've messed with bash for more than a decade & this is the first application I've found impossible  to disown.

If anyone can make or point me toward a likely source of useful suggestions, I'd appreciate it.

ADDED BY EDIT:
I don't see a delete issue button. I've found a workaround for this. I have the script check at the beginning to see if webtorrent-desktop is already running, and set a variable accordingly. Then at the end I check the variable and either enter an endless loop or exit. Only the first instance kills WT-D if it exits. I'm still curious about both  questions, but I've found my fix. Thanks.

**Comment by mathiasvr** [comment]
I'm not exactly sure what you are trying to accomplish, but if you rely on scripting and an external media player you will probably be better off using the [webtorrent-cli](https://github.com/webtorrent/webtorrent-cli) tool.

**Comment by Lew-Rockwell-Fan** [comment]
Thanks. I expect you're right,  but I've about got this working now. I still don't know why I can't disown `webtorrent-desktop  some-magnet-link` from a script, but for the main case, I've worked around that. I can start it _with no argument_ from a script and disown it just fine. _Then_ I can send it a link. That works well with starting it from an autostart script. I can't use the built in autostart feature because this thing will take over all my cpu cycles if I don't tame it with taskset and nice.
