### ISSUE TITLE
Use yarn to manage dependencies

### ISSUE THREAD

**Issue by Borewit** [webtorrent/webtorrent-desktop#1488]
**Background**

Based on a disussion started [here](https://github.com/webtorrent/webtorrent-desktop/pull/1486#issuecomment-425369379), I propose to continue the discussion here.

Do we want to check in a lock file?

And if we do, which one?
 
Do we want to:?

1. **Ignore the lockfile**, less configuration control, less security checks on dependencies, but more flexibility in using whatever local package manager you want use local.
1. **Use [npm](https://docs.npmjs.com/files/package-locks)**, the original package manager shipped with Node
2. **Use [yarn](https://yarnpkg.com/lang/en/)**, a very popular deterministic package manager developed by Facebook in collaboration with Exponent, Google, and Tilde.

**Votes:**

| no-lock-file  | NPM               | Yarn              | 
|---------------|-------------------|-------------------|
| @jimmywarting | @jimmywarting     | @Borewit          |
|               |                   | @sibiraj-s        |

Pending / not clear: @mathiasvr

**Comment by Borewit** [comment]
In addition to the benefits I already [mentioned](https://github.com/webtorrent/webtorrent-desktop/pull/1486#issuecomment-425472900):

> I am big opponent from every NPM module which require to be installed globally. You need a very justification to break out of your module scope to be installed globally, and need be non intrusive towards any other module. I noticed that yarn is close to be part of the from the core node & npm distributions. Yarn is probably, which has a good reason to be part of your global "toolbox".
> 
> Why?
> 
> 1.) As developer I experience yarn more reliable in installing / updating the dependencies after running yarn install, as a bonus it I believe it is faster. We all know we run into certain point where we have to delete node_module, my impression is that with yarn is more strict in translating the dependency requirements into installing required dependency, and is much more unlikely you run into that situation (but only if use yarn solely to take care of the dependencies). Jumping from one branch to another, this can be huge benefit, which we do on this project with PR's coming from all directions.
> 
> 2.) Yarn is more strict in the interpretation of version requirements, therefor it is less likely your code breaks due to some update which was not there before. Which improves configuration management control.
> 
> Draw-backs?
> 
> Sure, different character. Due to strict interpretation of the version, you need to pursue update versions more often, it doesn't automatically update package.json with patched version after an install.
> 
> Give it try yourself, you will have to get used to the command arguments which are a bit different.

Using yarn made working with local checked out dependencies so easy.
I maintain music-metadata, and some dependencies of music-metadata. I need to be able to test my changes to an end-user application like webtorrent during development.
Yarn made it so easy to link and unlink to a local checked out dependecy. Especially under Windows this used to be very painful.

**Comment by mathiasvr** [comment]
> Using yarn made working with local checked out dependencies so easy.

Is this similar to `npm link`? And if not, do you have an example?

Generally, I think we need more examples of how yarn could be an improvement, because it can be difficult to compare them based on opinion.

Also, I just want to note that I don't have a personal preference and is fine with either, I just have more experience with npm. If more people would prefer yarn, that's fine with me.
However, it is my impression that the differences between the two since npm v5 are minimal.

**Comment by sibiraj-s** [comment]
> the lock file was updated 8Months back.

Why not add `no lock file` to this discussion. Use what ever we want. We can stay upto date. Less maintenance of packages. With Greenkeeper, even that burden will be reduced too.

At this point all package managers are aware of how dependencies are handled based on `semver`. We can avoid `version ranges` for those libs don't follow semver

Plus, After NPM 6, I don't feel much difference between npm and yarn. but when comes to comparison between two. I vote **yarn**.

**Comment by Borewit** [comment]
I have to admit that I did not use npm a lot recently, so it may be that they have catched up on things I am not yet aware of.

> Is this similar to npm link? And if not, do you have an example?

```bash
git clone https://github.com/Borewit/music-metadata.git
cd music-metadata
# yarn install and yarn build would be required to get it to work
# The following step only has to be done once, as long as the local path remains the same
yarn link

cd ..

# Now you can use the local dependency anywhere you like
git clone https://github.com/webtorrent/webtorrent-desktop.git
cd webtorrent-desktop
yarn link music-metadata
```

Looking at [npm link](https://docs.npmjs.com/cli/link), that looks pretty similar. For some reason I was strugling with npm, and it seems work as it should with yarn. 

> Why not add no lock file to this discussion.

Fair point @sibiraj-s.

**Comment by Borewit** [comment]
> why don't we throw in pnpm to the mix also?

@jimmywarting because you are not planning to use it.

What is your final vote Jimmy?

**Comment by jimmywarting** [comment]
can i have 2 vote? either no-lock or npm

**Comment by sibiraj-s** [comment]
decided?

**Comment by Borewit** [comment]
I don't see a collective thumbs of for yarn, so I guess we continue with npm and the corresponding lockfile.
