### ISSUE TITLE
WebTorrent acting like a self DOS service, by not having proper options.

### ISSUE THREAD

**Issue by Zorrototo** [webtorrent/webtorrent-desktop#1492]
**What version of WebTorrent Desktop?** : 0.20.0 (0.98.21) (64bits)

**What operating system and version?** : Windows 7 ULTIMATE 64bits

There is a problem with WebTorrent, I have a 10MB connection, and when I add a torrent to WebTorrent, it opens as many connections as possible, and uses as much bandwidth as it can.

WebTorrent needs two options at least:
- max connections per torrent
- **max download/upload speed** <= THIS ONE ESPECIALLY!

Without these options, starting WebTorrent basically renders your computer useless during the whole download, it eats all resources network wise, it is basically like a DOS but from yourself.. Very bad in current state, I need to constantly shutdown WebTorrent if I want to check my emails or open a simple web page, then start WebTorrent again... This is really annoying and these two simple options would instantly fix these issues.

I hope you will add this in a near future..

**Comment by Zorrototo** [comment]
don't close, no one replied.

**Comment by alxhotel** [comment]
Duplicate of #435
