### ISSUE TITLE
Select All / Delete All torrents from list

### ISSUE THREAD

**Issue by fknop** [webtorrent/webtorrent-desktop#1500]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

0.20.0

**What operating system and version?**

Windows 7

**What did you do?**

Select All / Delete button from Edit menu do nothing.

**What did you expect to happen?**

I would like them to select and batch delete my torrents.

I would be glad to create a pull request if this is something the application needs. I always feel the need to batch delete my torrents instead of clicking and deleting them one by one.

**Comment by mathiasvr** [comment]
Does #1239 do what you want?

**Comment by fknop** [comment]
For the delete part it seems good.

Is the select all to pause or restart everything already implemented ?
