### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Mukiss** [webtorrent/webtorrent-desktop#1501]
Version: 0.20.0
Operating system: Windows 10
When I am trying to download something the download and upload speed go up but it says download 0 bytes and doesn't start downloading

**Comment by xXxLINKIxXx** [comment]
+
I also have.

**Comment by Mukiss** [comment]
Open

**Comment by feross** [comment]
> When I am trying to download something the download and upload speed go up but it says download 0 bytes and doesn't start downloading

The download/upload speed is based on how much data is transferred. It's possible that data you are receiving from peers is invalid (it doesn't hash correctly), in which case the download will not make progress, even though you will see that data is being downloaded.
