### ISSUE TITLE
.rpm package for Fedora, etc

### ISSUE THREAD

**Issue by adatum** [webtorrent/webtorrent-desktop#1502]
Are there plans to make a .rpm package available for Fedora and other rpm-based distributions, like the .deb that is already provided? It would be appreciated!

**Comment by TeknoMobil** [comment]
I have a lot of deployment using Fedora and other rpm packages

**Comment by feross** [comment]
Currently, Ubuntu is the only officially-supported version of Linux, though WebTorrent Desktop works great on many other flavors. I'm open to officially supporting additional flavors, but we need a volunteer to send a PR to produce the new build artifact and to agree to maintain it going forward.

So, we need answers to these questions:

- How do we produce the new build artifact? Is there a Node.js package, or does the Electron build tooling support it already?
- Who will send the PR to add it?
- Who will maintain it going forward?

**Comment by Borewit** [comment]
Implemented with PR #1694
