### ISSUE TITLE
Requesting Features: Title Bar, Menu Bar, Video Player Features and More..

### ISSUE THREAD

**Issue by V1NAY8** [webtorrent/webtorrent-desktop#1509]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.20.0 (0.98.21) (64-bit)

**What operating system and version?**
Windows 10

> ### I ❤️  what Web-torrent is doing.. I am an Amateur and would love these features. Please and I hope at least one of these help.. 🔥 

## What did you expect to happen?
**Make Webtorrent the default URI handler during installation**
## Title Bar
**Title Bar and Menu Bar Combination Just as in "VS CODE"**
![save](https://code.visualstudio.com/assets/updates/1_28/custom_menus.png)

## In Torrent Downloading/Seeding Page
 - **Join us on twitter** should be added to "Help" menu.
 - **Release Notes** Just to know the updated changes in the current version.
 - Playback menu should be disabled or hidden in this page.
 - In View -> **Go Back** must be disabled (Because there is nothing to go back)
 - In Help -> Check for Updates button to be added.
 - Multiple Language Support if Needed
 - ~**Developer Tools** must be brought to help menu (Best practices).~
 - Add **Info about torrent** (o know all properties of any file (If Video: Playback time,Dimensions, encoding).
 - Add shortcuts for (To know more about Webtorrent ) ->F1
 - Add Statistics Such as (Total Downloaded,Uploaded)
 - Update Preferences by adding a Bandwidth column **Restriction** (Maximum Upload, Download).
 - Time Elapsed (If necessary).
 - **About WebTorrent** More attractive information about the product and contributors or the packages used has to be updated.

##  In Video Playback page
 - On Hovering the control Buttons **Hints** must be displayed (E.g. Hover on Play Button display Play)
![image](https://user-images.githubusercontent.com/33659563/48077337-25b6f680-e20d-11e8-87e5-42a8a58fffcc.png)

 - Clicking on Video Must **toggle** play and pause.
 - Show **Percentage** of Volume while clicking and Dragging the volume bar.
 - Options to choose if **multiple subtitles** are loaded (Instead of Overriding).

**Comment by V1NAY8** [comment]
I am understanding the project structure and I am much happy to contribute to it.

**Comment by V1NAY8** [comment]
Can anyone tell me whether these changes are necessary...??

**Comment by feross** [comment]
Hi there, this issue is a bit too large to comment on. In the future, please suggest individual feature ideas one per issue. 

I liked a few of your suggestions so I opened issues:

https://github.com/webtorrent/webtorrent-desktop/issues/1670
https://github.com/webtorrent/webtorrent-desktop/issues/1671

Feel free to open other issues or to tackle these issues since you're new to the project. :)
