### ISSUE TITLE
WebTorrent with BitChute

### ISSUE THREAD

**Issue by radiostorm** [webtorrent/webtorrent-desktop#1510]
I seed my own videos so they remain available on my hosted server, it would be nice if there was a feature to mirror entire channels from BitChute, or at least display some friendly metadata in the WebTorrent client so we can see which videos are being seeded.

It would also be nice if you could view who the other seeders are.

**Comment by V1NAY8** [comment]
According to my knowledge, I guess in torrent we know only the Public IP of the person but not the seeders, because its a matter of privacy concern..
