### ISSUE TITLE
Two Distinct Files Get the Same Path

### ISSUE THREAD

**Issue by boramalper** [webtorrent/webtorrent-desktop#1511]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.20.0 (0.99.3) (64-bit)

**What operating system and version?**
Ubuntu 18.04
`Linux coma 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**What did you do?**
I've created a torrent from folder `b` with the following structure:

```
b
|
+ rando.txt
|
+ subdir/
  |
  + rando.txt
```

**What did you expect to happen?**
To have created a torrent with two files **with different paths** in it.

**What actually happened?**
In the created torrent, both files (`rando.txt` and `subdir/rando.txt`) have the same path `rando.txt`. See the attached .torrent file. [b.torrent.zip](https://github.com/webtorrent/webtorrent-desktop/files/2563515/b.torrent.zip)

**Comment by mathiasvr** [comment]
Related to https://github.com/feross/webtorrent/issues/845.
