### ISSUE TITLE
AC3 audio codec error

### ISSUE THREAD

**Issue by shust** [webtorrent/webtorrent-desktop#1513]
**What version of WebTorrent Desktop?**
0.20.0 (0.98.21) (64-bit)

**What operating system and version?**
Windows 10

**What did you do?**
Watch movie

**What did you expect to happen?**
The movie starts in your player

**What actually happened?**
AC3 audio codec error, asks to open in a third-party player

**Comment by mathiasvr** [comment]
Unfortunately, videos using the AC3 audio codec is not yet supported by the Webtorrent Desktop player. The issue is being tracked at #1389.

You have to install VLC, or another player and select it as external player in preferences.
