### ISSUE TITLE
WebTorrent GUI missing/Disappeared

### ISSUE THREAD

**Issue by poolboytheglorious** [webtorrent/webtorrent-desktop#1516]
I have the latest webtorrent client installed on my windows 10 home 64 bit (10.0 17134) machine.

When I try to launch the webtorrent client, the client itself runs and it is able to download torrents, but the GUI is not appearing. 
I tried to reinstall the application, and GUI successfully appeared the on the initial run, but after that GUI is not appearing. 

I have alos attempted to run the application with various compatibility settings, but with no avail.

**Comment by mathiasvr** [comment]
Related to #1416 and #1471.
