### ISSUE TITLE
Doubled Chromecast

### ISSUE THREAD

**Issue by Damilola2** [webtorrent/webtorrent-desktop#1519]
Version 0.20.0 (0.99.3)

Mac OS Mojave 10.14.1 (18B75)

When I press cast button there is my chromecast device listed twice (see screenshot for details)
<img width="188" alt="image" src="https://user-images.githubusercontent.com/44065778/49712090-d886d400-fc53-11e8-93f6-164c8b91a326.png">

**Comment by jimmywarting** [comment]
why didn't you read the first line?

DO NOT POST LINKS OR REFERENCES TO COPYRIGHTED CONTENT IN YOUR ISSUE

**Comment by Damilola2** [comment]
I'm sorry, somehow missed it, fixed the screenshot.
