### ISSUE TITLE
Annoying booping

### ISSUE THREAD

**Issue by QL568A6** [webtorrent/webtorrent-desktop#1525]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.20.0

**What operating system and version?**
Windows

**What did you do?**
Click checkbox

**What did you expect to happen?**
Silence

**What actually happened?**
Annoying booping

**Comment by QL568A6** [comment]
Just to be crystal clear, I'm talking about this checkbox:
![check](https://user-images.githubusercontent.com/25498543/50501770-e7bd9e00-0a17-11e9-9cd1-f74631d88b7f.PNG)

It also boops when it starts playing something. I find this sort of thing _extremely_ aggravating.

**Comment by mathiasvr** [comment]
Please move discussion to #1067.

**Comment by QL568A6** [comment]
> Please move discussion to #1067.

The issue thread mentioned is for another version.
