### ISSUE TITLE
Bad font rendering in GUI

### ISSUE THREAD

**Issue by solsticedhiver** [webtorrent/webtorrent-desktop#1528]
The fonts are badly rendered here all over the GUI, ubuntu 18.04, gnome shell, wayland, webtorrent installed using the .deb from website.

Just have a look at this screenshot
![Imgur](https://i.imgur.com/rlthZmD.png)
Especially look at the end of "File" or before the l of "Playback" or before the 2nd r of "Transferts" or before the l of "Help".

I built a dev version with electron 2.0.16 and the problem is gone. no errors in terminal either. please upgrade to electron 2

**Comment by gopesh97** [comment]
I want to report the same issue. 
![screenshot from 2019-02-03 21-01-24](https://user-images.githubusercontent.com/37135139/52178640-20ab1880-27f7-11e9-9fd8-1713f63f645e.png)

**Comment by feross** [comment]
Hey all, thanks for letting us know about this issue. We've already upgraded to Electron 6 on `master` so this fix will be in the next version of WebTorrent Desktop :)
