### ISSUE TITLE
Use xdg-open to play files on linux.

### ISSUE THREAD

**Issue by bilelmoussaoui** [webtorrent/webtorrent-desktop#1533]
**What version of WebTorrent Desktop?** Version 0.20.0 (0.99.3) (64-bit)

**What operating system and version?** Fedora Rawhide

**What did you do?** Run a random video that's not supported by WebTorrent Desktop (audio or video file)

**What did you expect to happen?** The app to run it in my external music/video player

**What actually happened?** Nothing, it suggests me to install either VLC or MPV while I don't want any of them. I have to set the binary path of the app manually which sucks.

You can just use `xdg-open $filepath` and that will open the assigned app to open that file automatically.  It would be nice to fallback to this instead.

**Comment by bilelmoussaoui** [comment]
Can we reopen this one?

**Comment by feross** [comment]
@bilelmoussaoui The issue is that we don't actually have the full file downloaded onto the disk. So, we're not opening the video player with a `.mp4` file or something like that, but rather an `http://` url. Won't this cause your default web browser to open? I don't think that's what you actually want.

**Comment by bilelmoussaoui** [comment]
@feross Thanks for the reply. Totally missed this. Sorry for the noise!

**Comment by Eskander** [comment]
> The issue is that we don't actually have the full file downloaded onto the disk. So, we're not opening the video player with e.g. a `.mp4` file path but rather an `http://` url.

Since the videos are downloaded sequentially, it is actually possible to use `xdg-open file-name.mkv` while the video is being downloaded. I tested that with both VLC and MPV.
