### ISSUE TITLE
Problem with "Go Back" functionality

### ISSUE THREAD

**Issue by JamesKimari** [webtorrent/webtorrent-desktop#1537]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.20.0 (0.98.21) (32-bit).

**What operating system and version?**
Windows 10 Pro 64-bit.

**What did you do?**
I pressed the "Esc" key while on the "Preferences Page".

**What did you expect to happen?**
I was expecting that the application would go back to the home page. 

**What actually happened?**
The application immediately minimized itself and would not open again unless uninstalled and then installed again. Completely terminating all instances of the app in the task manager could not solve the issue. I'm not sure whether it's a unique case or a general issue on all Windows 10 platforms. This is very annoying BTW. Please fix this bug in case you find that it's evident.

I, however, noticed that when i installed the 64-bit version, the problem stopped. Only problem is that i had to install it from another site other than the official WebTorrent site. I was advising that it would be better to clearly give both options for 32 and 64-bit architectures in the windows download section.

Thanks in advance.

**Comment by feross** [comment]
> @JamesKimari Only problem is that i had to install it from another site other than the official WebTorrent site.

I don't understand why this was necessary. Which website? I do not recommend installing from third-party sites as there is no way to guarantee that malware or other unwanted software has not been inserted. It is safest to stick with our official downloads.
