### ISSUE TITLE
Corrupted Font In Ubuntu 18.04

### ISSUE THREAD

**Issue by infosisio** [webtorrent/webtorrent-desktop#1538]
There is an issue with the font in Ubuntu 18.04 which is pretty serious; it is distorted.

It has to do with the version of the libfreetype6 package.

You have to do this to fix it:
```
sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ artful-updates main"
sudo apt-get update
sudo apt-get install libfreetype6=2.8-0.2ubuntu2.1
sudo apt-mark hold libfreetype6
```

**Comment by cbr9** [comment]
It's also corrupted in 18.10, and this doesn't fix it.

**Comment by feross** [comment]
@infosisio @cbr9 Can you try building the app using the code on `master`? I believe there's a good chance that updating to the latest Electron (as we have done on `master`) has fixed this issue.
