### ISSUE TITLE
Can't See WebTorrent xTimes After You Open And Close Multiple Times

### ISSUE THREAD

**Issue by typical-echo** [webtorrent/webtorrent-desktop#1541]
**Latest Stable Build

**Windows 10 64-Bit

**Close It And Open It Multiple Times

**It To Open

**Went Off Screen. You Have to move your cursor to the icon on the taskbar. When it shows the preview go over that and right click so it says maximize, minimize, and move. i click move and use my arrow keys to go left then i can finally see webtorrent.

**Comment by SomewhatDisoriented** [comment]
In a similar vein, the WebTorrent window gets slightly larger and starts moving off the screen to the right every time I exit and re-open the program. Also on Windows 10.

**Comment by feross** [comment]
This is likely fixed on `master` because we updated to a newer Electron version. Follow https://github.com/webtorrent/webtorrent-desktop/issues/1674 for info on the release.
