### ISSUE TITLE
Webtorrent Mac wont even force quit after stream is over

### ISSUE THREAD

**Issue by rockinfreakshow** [webtorrent/webtorrent-desktop#1543]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
v0.20.0
**What operating system and version?**
MacOS Mojave v10.14.2
**What did you do?**
the file is being downloaded; I click stream button and the media is played on VLC; I close out VLC when the video is done, that's it the webtorrent jus freezes after this step.
**What did you expect to happen?**
the webtorrent usually should go back to main panel page
**What actually happened?**
It freezes and we cannot close it or force close it or killing the pid via terminal wont work. So I stopped using the stream button altogether but somehow I accidentally click the play button every now and then & I have to hard restart my mac since the webtorrent wont even let the machine reboot. 
It happened many times & today is the day I just got sick of it & uninstalled the whole thing.

**Comment by kekkyojin** [comment]
I was able to force the app to shutdown by changing to another app and then opening the Apple menu. The app is closed, but the window is still on the screen. It takes a very long time until it finally disappears and then the system dialog box appears which asks what to do after the force quit.
