### ISSUE TITLE
[Question] Current way to get the quantity uploaded by torrent? (or overall)

### ISSUE THREAD

**Issue by tuxayo** [webtorrent/webtorrent-desktop#1544]
hi :)

I had a snippet that worked few months ago, which are the stats available in the current version's CLI?

**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.20.0 (0.100.0) (64-bit)
**What operating system and version?**
Antergos (Arch Linux based), rolling, up to date
**What did you do?**
```
console.log("##################################################################");
console.log("Total ratio:", client.ratio);
client.torrents.forEach( function(arrayItem) {
  console.log("##########", arrayItem.name, "################################") 
  //console.log("ratio", arrayItem.ratio);
  // real ratio, in case the file wasn't downloaded in WebTorrent
  console.log("uploaded", arrayItem.uploaded/1024/1024, "MiB");
  console.log("length", arrayItem.length/1024/1024, "MiB");
  console.log("session_upload/length", arrayItem.uploaded / arrayItem.length);
});
```

**What did you expect to happen?**
Do print the data.

**What actually happened?**
`Uncaught ReferenceError: client is not defined`

**Comment by tuxayo** [comment]
https://github.com/webtorrent/webtorrent/blob/71fa2641df8e431b8ec4a46d240bb9bc5ad07932/docs/api.md#clientratio

It seems that the API didn't change. So it's the client object which isn't in the same place anymore.

**Comment by feross** [comment]
`client` is the variable name that your code chooses to call the WebTorrent instance it creates:

```js
var client = new WebTorrent()
```

You should find what you named it and use that name.
