### ISSUE TITLE
FEATURE: Ability to stream without downloading/saving to disk

### ISSUE THREAD

**Issue by npyl** [webtorrent/webtorrent-desktop#1545]
Hi!
It would be awesome if there was an option to stream a torrent **WITHOUT** saving the video file(s) to disk.

Pros:
- easily save disk space
- make Webtorrent more convenient

A good idea would be, everytime a torrent is added, to ask user either to **download and stream** or **just** stream.

Not sure if this is possible but from what I understand this is what is done right now: a small chunk of data is downloaded and is played.

Thanks for this great app.

**Comment by jimmywarting** [comment]
Conn: worse torrent health by being selfish

**Comment by npyl** [comment]
You are right about this.  I totally forgot about the real ideology of torrent.

**Comment by MrDarkSkil** [comment]
If you are on Linux system just download your movie in /tmp folder 😄
