### ISSUE TITLE
cannot play large mkv

### ISSUE THREAD

**Issue by arjd** [webtorrent/webtorrent-desktop#1551]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.20.0

**What operating system and version?**
macOS 10.14.3

**What did you do?**
Tried to play and cast a large torrent (2GB+)

**What did you expect to happen?**
It plays in WebTorrent, and allows casting

**What actually happened?**
Whenever I try to play mkv's that are over 2GB or so, WebTorrent gives me this error:
![image](https://user-images.githubusercontent.com/20357504/54064219-62592580-41e0-11e9-9038-3142aed7c7d5.png)
I know mkv is a supported codec so I suspect this is a bug somewhere.

**Comment by pundoo** [comment]
It's not about the size nor the file extension (.mkv). It literally says the error 'Audio codec unsupported'. Perhaps try to find another (torrent) version of the file with different audio codec.

**Comment by pundoo** [comment]
It's not about the size nor the format '.mkv' (it's container, not codec). It literally says the error 'Audio codec unsupported' (possibly your file uses the AC3 codec, which isn't supported yet).
Perhaps try to find another (torrent) version of the file with different audio codec.

**Comment by arjd** [comment]
whoops -- you're right, apologies!
