### ISSUE TITLE
[Request] Play and cast local files

### ISSUE THREAD

**Issue by Martan404** [webtorrent/webtorrent-desktop#1556]
I would be lovely to be able to add local files to WebTorrent. It's one of few program able to stream videos with subtitles to Chromecast and it just works out of the box. 
I tried adding one of my videos and WebTorrent asked me if I wanted to create a new torrent. But for some reason nothing happened (it's an .mp4 file if that matters). But having an option to just straight play/launch it in the WebTorrent player when dragged onto WebTorrent would be sufficent I think.

Perhaps this is too far from the original intent, but it would be a great feature in my opinion.

**Comment by feross** [comment]
You should be able to just drag a file onto WebTorrent, click 'create a torrent', wait for it to be added (there's no UI feedback while the torrent is being created), and then cast it.
