### ISSUE TITLE
No internal Subtitles 

### ISSUE THREAD

**Issue by adetyaagg** [webtorrent/webtorrent-desktop#1565]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.20.0 (0.98.21) (64-bit)
**What operating system and version?**
Windows
**What did you do?**
Had to add subtitles manually. (unlike Soda Player with built in feature). when casted to chrome-cast subtitles are not casted. 

**What did you expect to happen?**
in built subtitles and functionality to cast them to chrome-cast

**What actually happened?**
N/A

**Comment by feross** [comment]
Sorry, this is not a feature we are likely to support. See https://github.com/webtorrent/webtorrent-desktop/pull/677 for previous discussion.
