### ISSUE TITLE
The "Install VLC" button is almost useless and annoying

### ISSUE THREAD

**Issue by sldx** [webtorrent/webtorrent-desktop#1568]
When a playback fails there's a popup that by design can be useful only once per user. So not the best UX.

Seeing the type of users you have, I suggest to at least add a button for Locate File, since that's what you're actually supposed to do if you already have VLC. 
IMO it can be the "main" action, and have the _Install VLC_ text as a small link. 

Keep up the good work 👏

**Comment by feross** [comment]
@sldx The popup you see is supposed to recommend that you open VLC if it is already installed on your system. The fact that you see "Install VLC" every time means that we're not detecting VLC on your system.

Can you share the path to VLC on your system?

**Comment by sldx** [comment]
Yeah, it's not in the usual location. It's in Applications/Others/Video/VLC

**Comment by feross** [comment]
@sldx Some questions:

- Is this a location that is typically used by your OS?
- Or is this just the place that you chose to install it?
- Have you tried selecting an external player manually? In preferences, find the panel that looks like this:

<img width="591" alt="Screen Shot 2019-07-29 at 10 15 20 AM" src="https://user-images.githubusercontent.com/121766/62067951-d32dc800-b1e9-11e9-9739-d9b8db84f98d.png">

**Comment by sldx** [comment]
It's not a default location for installing apps, it's a subfolder of the default location (Applications/), because I like to keep the apps organised.

Didn't know about choosing an external player, just changed it now. I'll see how it works the next time. Thx, didn't know about that

**Comment by feross** [comment]
I'm closing this issue since there's no bug to fix here, but feel free to continue discussion! ✨
