### ISSUE TITLE
Why is sound faster than light?

### ISSUE THREAD

**Issue by shauryasehgal** [webtorrent/webtorrent-desktop#1571]
About 2 months ago , i downloaded webtorrent. After using it for sometime, i noticed that some popular downloads were downloading at 6 times my internet speed. That was awesome. And few days ago, i formatted my pc and reinstalled it. But now that feature is gone for the same downloads. Can anyone suggest why did they download at such high speed , and what can i do to fix them ?

**Comment by jimmywarting** [comment]
what a grate title summarize

**Comment by Borewit** [comment]
@shauryasehgal, I adjusted the layout of your issue a bit. I hope you are okay with that.

Webtorrent-desktop is indeed a great application, but I don't think it will surpass the maximum bandwidth of your Internet connection. 

Maybe you had multiple torrent clients running? Maybe some cached data already in your download folder? Was it really the first time you downloaded that torrent?

**Comment by shauryasehgal** [comment]
No multiple clients , no cached data and yes all of those were first time
downloads. It did surpass the internet limit by a LOT and I downloaded a
whole lot of torrents. It only did this for popular torrents. One thing
that i have noticed , is that i still get the same high speed ( 6 times )
for downloads only from google servers ( youtube , Gdrive etc ) .  Is there
some kind of relation there ?

**Comment by jimmywarting** [comment]
You can't surpass your internet speed limit. 

Recommend that you do a internet speed test. tell us what
- your ISP provider limit is
- tell us what the speed test shows
- tell us what download speed you had before/after you formatted your pc

> Some Internet service providers slow down certain types of traffic, like BitTorrent traffic. 

You could have used WebRTC that is another type of traffic, something of which your ISP provider did not block before (b/c they didn't know what it was)

> Other ISPs slow down their customers’ connections if they download too much data in a month. 

...Too bad.

https://www.howtogeek.com/165481/how-to-test-if-your-isp-is-throttling-your-internet-connection/

If the download speed is faster than what you are actually writing to the disk<br>
or that the average speed says 10mb/s for a 100 mb torrent file, and the time to finish it was still longer then what it should have been. Then it means speedometer have lost a few [tick counts](https://github.com/mafintosh/speedometer/blob/a7b53aca2cf17c1bfd4daeadcba99881fb5dc09e/index.js#L6)

Could be that you have used a older version of electron+webtorrent that could have affected the setInterval to have drifted off. heavy javascript execution, slow computers and [strangled](https://stackoverflow.com/questions/6032429/chrome-timeouts-interval-suspended-in-background-tabs) background timers may case the setInterval to drift off and show fewer tick counts.

Having formatted your pc (to be faster) and used a newer electron version might have made the setInterval more accurate too (showing you <s>slower</s> more accurate speed/s) 

lost count over longer  period shows higher speed/sec. I did notice this before when doing performances testing when the thread became unresponsive (blocked) 

this is noticeable with instant.io too when the timers becomes suspended while it's in the background
https://instant.io/#08ada5a7a6183aae1e09d831df6748d566095a10

(go to another tab, go back, see the speed drop back to normal)

**Comment by shauryasehgal** [comment]
I have bought a 10 Mbps internet connection ( speed limit ) . Speedtest
shows me 10 Mbps. Webtorrent gave me a speed of 60 Mbps on the popular
torrents. I could literally see 6 MBs added per second. What took around 1
hour , took 10 minutes. I am not joking , this is really true. BitTorrent
still worked at 10 Mbps for the same downloads.

But now , the speed is again 10 Mbps for the same popular downloads!  This
version of webtorrent is the same , I guess some setting must have changed.
I really don't think my ISP is blocking high speed traffic.

Please Help ! Thank you.

**Comment by Borewit** [comment]
First download one of your popular torrents with BitTorrent. Give it good head start.
Then startup Webtorrent, and download the same torrents, you may see it will exceed 10 Mbps again just like in the good old days.

If that doesn't give you the extra punch you are looking, we are running out of options. 
Maybe [Thio Joe can help you to quadruple you Internet speed](https://www.youtube.com/watch?v=UqLHE0_NRFo). It may not be as good as your previous boost, but hey, 4 times is better than sticking with the 10 Mbps. 

Send Thio our regards.
