### ISSUE TITLE
External player (vlc) configuration, does not work in Linux Mint

### ISSUE THREAD

**Issue by conradopsa** [webtorrent/webtorrent-desktop#1575]
**What version of WebTorrent Desktop?** 
Version 0.20.0 (0.99.3) (64-bit)

**What operating system and version?**
Linux Mint 19.1 Cinnamon 64-bit

**What did you do?**
I configured to play torrent media using external player (VLC) and i tryed to play

**What did you expect to happen?**
Open vlc and display media.

**What actually happened?**
When i click to watch video, vlc does not open.

**Comment by feross** [comment]
Can you try to reproduce this error once more? But this time when it happens, click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

If you don't see any errors, then please check in one more place! Click View > Developer > Show WebTorrent Process, select the Console tab and copy-paste all the text.

Being able to see that output would help us out very much. Thanks.
