### ISSUE TITLE
cast to chromecast with subtitles

### ISSUE THREAD

**Issue by amitrahav** [webtorrent/webtorrent-desktop#1577]
**What version of WebTorrent Desktop?**  0.20.0 ‏(0.99.3)
**What operating system and version?** macOS Mojave 10.14.2

**What did you do?** cast to chromecast within desktop app.

**What did you expect to happen?** cast with subtitles.

**What actually happened?** cast video without titles.

**Comment by marcosdipaolo** [comment]
noboody?

**Comment by feross** [comment]
I believe this issue is already resolved. It will go out when we release a new version of WebTorrent Desktop.
