### ISSUE TITLE
Torrents only begin if I close/reopen the app

### ISSUE THREAD

**Issue by robliberty** [webtorrent/webtorrent-desktop#1578]
Version 0.20.0 (0.98.21) (64-bit) on Windows 10

When using magnet links, the torrent gets added to the list but never connects to peers or starts the "Loading..." dialogue. These are popular torrents too.

If I quit and restart the app the torrents connect immediately and function as expected.

**Comment by MeowTheCat** [comment]
similar issues here.  Magnet links sometimes work sometime don't for the same torrent.
I'm the one who is also seeding the file from seedbox , so it should work 24*7

**Comment by feross** [comment]
Can you try to reproduce this error once more? But this time when it happens, click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

If you don't see any errors, then please check in one more place! Click View > Developer > Show WebTorrent Process, select the Console tab and copy-paste all the text.

Being able to see that output would help us out very much. Thanks.
