### ISSUE TITLE
Re-downloading completed torrents

### ISSUE THREAD

**Issue by WaffleJim** [webtorrent/webtorrent-desktop#1586]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.20.0 (0.99.3)

**What operating system and version?**
Mac OS 10.14.4 (18E226)

**What did you do?**
open webtorrents

**What did you expect to happen?**
continue uploads/download

**What actually happened?**
completed torrents started from the beginning.

**Comment by ShGKme** [comment]
Same problem on Windows 10x64.  
Any torrents (both completed and in-process) starts from the beginning after restart the application.   
It doesn't really restart downloading, it downloads super fast all parts have being downloaded previously, but load CPU as much as possible...

**Comment by pro-src** [comment]
It rechecks the downloaded torrents for missing files and verifies the SHA1 checksums at startup. This integrity check is so WebTorrent will know how to fix partial downloads aka resume downloads. This is a UX design bug but I don't think it's a functional bug. I doubt it was designed deliberately to be misleading but it should say what it is actually doing...

**Comment by CoVoCre** [comment]
@ShGKme I think pro-src's answer explains your issue right ? What about you @WaffleJim was your problem the same ?

**Comment by williamgh2019** [comment]
I use version 0.20.0 (0.98.21) it no issue.
