### ISSUE TITLE
If torrents has single file, it does not download in target location

### ISSUE THREAD

**Issue by chanonly123** [webtorrent/webtorrent-desktop#1587]
**What version of WebTorrent Desktop?**
WebTorrent Desktop 0.20.0

**What operating system and version?**
Mac OS Mojave 10.14.4

**What did you do?**
Trying to download a torrent

**What did you expect to happen?**
Should start downloading and a file should create in target location

**What actually happened?**
Started successfully but file not created in target location. 100% reproducible if torrent has only single file. here is the link for reproducing [link](https://www.1377x.to/torrent/3716405/Captain-Marvel-2019-English-720p-HDTC-x264-900MB-MB/)

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement. No one will be able to assist you.
