### ISSUE TITLE
Can't play file from target folder

### ISSUE THREAD

**Issue by JustCallBen** [webtorrent/webtorrent-desktop#1588]
D/ld x265.mkv file to default target folder (D:/Downloads).  File completed normally.  Opened explorer and double-clicked file.  MPC-HC opened and reported "File not found".  Went back to WebTorrent Desktop App and clicked "Play" button.  WebTorrent brought up VLC screen which was seemingly unresponsive.  Went to Preferences and tried to change external app to MPC-HC.  App ignored me.
Clicked Play again and player window opened with error "Sorry, we can't play that file". "Video codec unsupported.  Blue button says "Play in MPC-HC".  Clicked and video played.

**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.20.0 (0.98.21) (64-bit)
**What operating system and version?**
Windows 8.0
**What did you do?**
See above
**What did you expect to happen?**
Play from target folder without needing to play through WebTorrent app.
**What actually happened?**
See above.

**Comment by feross** [comment]
I'm a little confused how this could happen. You said the file downloaded completely, but then when you went to the file in Windows Explorer and opened it it didn't play. This sounds like it can't be a WebTorrent bug (unless we're downloading and saving invalid data to disk, which has never been an issue in the history of WebTorrent as far as I'm aware).

> Went to Preferences and tried to change external app to MPC-HC. App ignored me.

This sounds like a bug. Can you try to reproduce this error once more? But this time when it happens, click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

If you don't see any errors, then please check in one more place! Click View > Developer > Show WebTorrent Process, select the Console tab and copy-paste all the text.

Being able to see that output would help us out very much. Thanks.

**Comment by JustCallBen** [comment]
I figured out half of the problem.  I migrated from Vuze and although all
my settings were retained, BBT ignored or confused them.  I went in and
disabled move on completion, tested good.  I re-enable move on completion
and now it works as before.

Same situation on moving data files.  I had previously selected move/delete
in one operation but it was ignoring that.  I disabled that, saved,
re-enabled, saved and tested good.

Not sure if this is my personal anomaly or what.

Cheers,

Ben Maurer
Just Call Ben, General Contractor
619 820 2905

**Comment by feross** [comment]
What is BBT?

**Comment by JustCallBen** [comment]
**B**igly**BT**

**Comment by feross** [comment]
You are posting on the wrong issue tracker. We have nothing to do with the app you mentioned. This place is for issues related to [WebTorrent Desktop](https://webtorrent.io/desktop/).
