### ISSUE TITLE
300% CPU usage by web torrent helper

### ISSUE THREAD

**Issue by parth-verma** [webtorrent/webtorrent-desktop#1589]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.20.0 (0.99.3)

**What operating system and version?**
macOS Mojave 10.14.4

**What did you do?**
Download Torrent

**What did you expect to happen?**
Low CPU Usage

**What actually happened?**
High CPU Usage
![image](https://user-images.githubusercontent.com/22412980/57784489-99523700-774d-11e9-870d-68313fe02926.png)

**Comment by MattTunny** [comment]
i'm not 100% with mac but i've seen this on windows when I had to many torrents for the hard drive to keep up and it would just lock up the cpu. Might not be related thought

Does it use that much % when running say 1 or 2 torrents?

**Comment by udiNur** [comment]
same with me, using Mac 
![image](https://user-images.githubusercontent.com/13526747/59415361-ffbd8a00-8dcb-11e9-8558-b9f259ec0f09.png)

the CPU:
![image](https://user-images.githubusercontent.com/13526747/59416490-2381cf80-8dce-11e9-9f6b-fa0b5735cc75.png)


the torrents that I download (only 2, not too much speed):
<img width="1276" alt="torrents2dl" src="https://user-images.githubusercontent.com/13526747/59417902-bde31280-8dd0-11e9-81d9-c498e6d27803.png">


Sometimes it's even crazier.. my computer gets really hot, and the funs starts to activate in full speed) even more then when I using tow virtual machines

**Comment by feross** [comment]
This is a known issue. You can follow this issue: https://github.com/webtorrent/webtorrent/issues/1026
