### ISSUE TITLE
VirusTotal

### ISSUE THREAD

**Issue by direkte** [webtorrent/webtorrent-desktop#1591]
-WebTorrentSetup-v0.20.0

VirusTotal report Yandex Trojan.DR.Agent!9laIEHGpSGs

![webtorrent](https://user-images.githubusercontent.com/29358278/57866540-ceb75d00-77ff-11e9-9102-6b09a5ce3c65.PNG)

**Comment by jimmywarting** [comment]
"Attach files by dragging & dropping, selecting or pasting them."
Says so under the textarea 

![webtorrent](https://user-images.githubusercontent.com/1148376/57861263-8c3d5280-77f6-11e9-9333-ca19fe9b4de0.png)

**Comment by feross** [comment]
I just tested the Windows installer and it's no longer being reported on VirusTotal. It looks like this must have just been a temporary mistake.

<img width="1279" alt="Screen Shot 2019-07-10 at 3 23 38 PM" src="https://user-images.githubusercontent.com/121766/61009189-bdce2800-a326-11e9-967a-7ba693c7183f.png">
