### ISSUE TITLE
Webtorrent Space Hogging.

### ISSUE THREAD

**Issue by thegeekybaniya** [webtorrent/webtorrent-desktop#1594]
**Version 0.20.0**

**Windows 10 Pro**

**What did you do?**
Deleted a torrent using delete data file option. The torrent size was 1.3GB.
**What did you expect to happen?**
Free space increase of 1.3GB.
**What actually happened?**
No increase in free space.

Also how to get back this space.

**Comment by CoVoCre** [comment]
What do you mean by this ? Free space as reported by what program ? And were the files deleted after you used the delete data option ? Did you empty the trash ?

**Comment by feross** [comment]
It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.
