### ISSUE TITLE
Error when creating a Torrent from a folder

### ISSUE THREAD

**Issue by marcschuler** [webtorrent/webtorrent-desktop#1595]
**What version of WebTorrent Desktop?**
**What operating system and version?**
Windows 10: Version 0.20.0 (0.98.21) (64-bit) 
Ubuntu 19.04:  0.20.0 (0.99.3) (64-bit)

**What did you do?**
File -> Create new Torrent from Folder
I selected a folder of my choice containing a few subdirectories and files inside of it. Total of a few subfolders, ~50 files and ~20GB filesize total. 

**What did you expect to happen?**
I expected a dialog to open something like the dialog from the "Create new Torrent from File"

**What actually happened?**
Nothing in the GUI, just back to the main view. No error message.

In the developer console the error below is shown. This happens on every folder I've tried.
```

Uncaught TypeError: path must be a string or Buffer
    at fs.stat (fs.js:893)
    at Object.fs.stat (ELECTRON_ASAR.js:291)
    at findFilesRecursive (C:\Users\Marc\AppData\Local\WebTorrent\app-0.20.0\resources\app.asar\build\renderer\controllers\tor…:347)
    at C:\Users\Marc\AppData\Local\WebTorrent\app-0.20.0\resources\app.asar\build\renderer\controllers\tor…:365
    at FSReqWrap.oncomplete (fs.js:112)


fs.stat @ fs.js:893
fs.stat @ ELECTRON_ASAR.js:291
findFilesRecursive @ C:\Users\Marc\AppData\Local\WebTorrent\app-0.20.0\resources\app.asar\build\renderer\controllers\tor…:347
(anonymous) @ C:\Users\Marc\AppData\Local\WebTorrent\app-0.20.0\resources\app.asar\build\renderer\controllers\tor…:365
(anonymous) @ fs.js:112

```

**Comment by KarlTheBee** [comment]
Same error on Version 0.19.0 (0.98.21) (64-bit) (Win10)

**Comment by feross** [comment]
This sounds like a bug, but I haven't attempted to reproduce it.
