### ISSUE TITLE
The status bar (window name) is light when the application uses a dark theme

### ISSUE THREAD

**Issue by Rakleed** [webtorrent/webtorrent-desktop#1598]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.20.0 (0.98.21) (64-bit)
**What operating system and version?**
Windows 10, v. 1903
**What did you do?**
Open the application.
**What did you expect to happen?**
The status bar (window name) is dark.
**What actually happened?**
The status bar (window name) is light.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/19418601/58955495-d6d23f00-87a4-11e9-9971-b42b03e18e22.png)

</details>

**Comment by Iffabled** [comment]
Windows doesn't allow Win32 apps to change this (only UWP apps can), so changing its color would require either using some package ([some popular ones](https://www.npmjs.com/search?q=electron%20titlebar)) or making a custom title bar using a borderless window (like VS Code did).

**Comment by feross** [comment]
I don't want to make a custom titlebar -- that's a lot of complexity and the OS titlebar will always work more consistently and better. I think we can't fix this until there's some kind of workaround on the Electron or Windows side.
