### ISSUE TITLE
`npm start` does not start on Debian Node v11

### ISSUE THREAD

**Issue by jcalfee** [webtorrent/webtorrent-desktop#1600]
`npm start` on master does not produce any UI and gives me an error.

**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
* master

**What operating system and version?**
Debian Stretch
$ node -v
v11.6.0

**What did you do?**
`npm start`

**What actually happened?**
```bash
$ npm start

> webtorrent-desktop@0.20.0 start /home/james/opt/webtorrent-desktop
> npm run build && electron .


> webtorrent-desktop@0.20.0 build /home/james/opt/webtorrent-desktop
> buble src --output build

Missing config file: Creating new one
A JavaScript error occurred in the main process
Uncaught Exception:
/home/james/opt/webtorrent-desktop/node_modules/cp-file/index.js:60
		...options
		^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at setupStateSaved (/home/james/opt/webtorrent-desktop/build/renderer/lib/state.js:114:16)
```

Node kept running but the UI did not show up.

Maybe package.json needs some babel-polyfill?

**Comment by Muhnad** [comment]
same on Mac

**Comment by Muhnad** [comment]
Okay, I just fixed it by downloading the Production app and open it :D 

I don't know why this happening but I think its something related by configuration checks the `state.js` file on render folder line `60` there is a long comment talking about that.

**Comment by skpulipaka26** [comment]
I am facing the same issue on mac
@Muhnad
Can you please explain what you mean by production app? Is it on a different branch?

**Comment by Muhnad** [comment]
Just download the app from website and run it.

Then run the code. That's what I did and worked with me.

**Comment by skpulipaka26** [comment]
Thank you, that works

**Comment by Siilwyn** [comment]
Same on Ubuntu 19.04!

**Comment by jcalfee** [comment]
Also tried `yarn install` with node v11.  Sometimes electronjs does better under yarn.  Did not work though..  Same error under node v9 and v10..

**Comment by jcalfee** [comment]
Got it working under node v11 .. I went to the latest release tag..
```bash
$ git checkout tags/v0.20.0
HEAD is now at fbb3fa6... 0.20.0
$ npm install
...
$ npm start
```

This is still an issue on **master**.

**Comment by hicom150** [comment]
For me `master` work great in this scenarios

- OSX Yosemite 10.10.5 
  - [x] node 8
  - [x] node 10
  - [x] node 12
- Ubuntu 18.04.02 LTS
  - [x] node 8
  - [x] node 10
  - [x] node 12

Giving that node 8 and node 10 are the stable LTS versions and node 12 the current one, could you try with this releases of node in case of we can recover more info... 😉

**Comment by jcalfee** [comment]
Same error under node v10..

**Comment by feross** [comment]
@jcalfee Are you sure that you're running Node 10? And error parsing `...options` indicates that you're using an old version of Node.js (likely older than Node 8). You can check the version you're using with:

```
which node
node --version
```

**Comment by feross** [comment]
Nevermind. The issue is coming from Electron. You may be using an outdated electron version. What do you get when you run this:

```
npm ls electron
```

You might also want to try once more using the latest code from the `master` branch as we've just updated to Electron 4. But it worked for me with electron@1.8.8 before updating too.

**Comment by jcalfee** [comment]
```bash
$ npm ls electron
webtorrent-desktop@0.20.0 /home/james/opt/webtorrent-desktop
└── electron@1.8.8 
```

**Comment by jcalfee** [comment]
I did a pull on master and although `npm ls electron` still reports `electron@1.8.8`, `npm start` works now.   Thank you..

**Comment by feross** [comment]
Great. Glad you got it figured out!
