### ISSUE TITLE
magnet link (for large files) doesn't work in WebTorrent but works in other BT client software

### ISSUE THREAD

**Issue by MeowTheCat** [webtorrent/webtorrent-desktop#1601]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.20.0 (0.98.21) (64-bit)

**What operating system and version?**
windows 10 Home

**What did you do?**
open a magnet link in WebTorrent Desktop
magnet:?xt=urn:btih:a7be34c1208973605628d27dba03f71d01200fe0&dn=%E3%80%90%E8%99%8E%E7%9C%8B%E7%BD%91www.hukandy.com%E3%80%91%E6%88%91%E4%BB%AC%E4%B8%8E%E6%81%B6%E7%9A%84%E8%B7%9D%E7%A6%BB08.mp4&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337

actually, I'm the one seeding this file from a cloud seedbox. So it should be work 24*7
[torrent.zip](https://github.com/webtorrent/webtorrent-desktop/files/3268435/torrent.zip)

**What did you expect to happen?**
Webtorrent starts downloading the files.

**What actually happened?**
The UI shows it found 1 peer but not downloading.  If I open the magnet link from any other bittorrent client (like qBittorent),  the file will be downloaded.

What make things more strange is if I provide the .torrent file (instead of the magnet link) to Webtorrent desktop, the file will be downloaded.

**Comment by MeowTheCat** [comment]
After further testing, I found that this is especially the cast for large file.
For example, the following 290M file magnet link doesn't work on Webtorrent, but works in other BT client like qbittorrent.

magnet:?xt=urn:btih:3319fd82243bd1d9ddaef10bdf098ccc056b77d0&dn=video1.mp4&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337&tr=udp%3a%2f%2ftracker.coppersurfer.tk%3a6969&tr=udp%3a%2f%2ftracker.leechers-paradise.org%3a6969&tr=udp%3a%2f%2fexplodie.org%3a6969

When I tested a smaller file, it works in both Webtorrent Desktop and qbittorent
magnet:?xt=urn:btih:e989e1d35c0a6952e318c872cc2e84f90e77ebb2&dn=testfile.zip&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337&tr=udp%3a%2f%2ftracker.leechers-paradise.org%3a6969&tr=udp%3a%2f%2ftracker.coppersurfer.tk%3a6969&tr=udp%3a%2f%2fexplodie.org%3a6969

**Comment by MeowTheCat** [comment]
in all above cases, I'm seeding those files from cloud seed box so they should work 24*7

**Comment by fusir** [comment]
I've recently had a 30G start tested in multiple webtorrent based clients.  All of these were tested in linux or on web.
