### ISSUE TITLE
[Feature] Support i2p

### ISSUE THREAD

**Issue by oijkhg** [webtorrent/webtorrent-desktop#1606]
**Feature**: Add i2p support to Webtorrent-Desktop
**Why?**: Mainly for privacy and security but also to support decentralized web communications.
**How?**: BitTorrent already has wide usage of i2p thank to i2p-snarks and [XD](https://xd-torrent.github.io/).

_____________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/75655240-feature-support-i2p)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=75655240)](https://www.bountysource.com/issues/75655240-feature-support-i2p)

**Comment by fearghasmr** [comment]
This would be great.

**Comment by feross** [comment]
Thanks for the feature request!

WebTorrent Desktop values simplicity more than most torrent apps. This sometimes means saying 'No' to good ideas. We try to implement only the most important features that a torrent app needs and make those features as good as possible. We generally don't accept features that may benefit a small percentage of users.

Sorry that this isn't what you wanted to hear. Thank for you understanding!
