### ISSUE TITLE
Any change to document all tools and plugins needed to debug?

### ISSUE THREAD

**Issue by PaTiToMaSteR** [webtorrent/webtorrent-desktop#1616]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
latest
**What operating system and version?**
Windows 10
**What did you do?**
Try to build and debug with vsCode
**What did you expect to happen?**
Press F5 and debug!

**What actually happened?**
Impossible, stuck after hours. Looks like buble don't like me:

> buble src --output build

---
4 : 
5 : module.exports = class CreateTorrentErrorPage extends React.Component {
6 :   render () {
7 :     return (
8 :       <div className='create-torrent'>

Any change guys to include a standard launch.json, document it maybe if you don't want to include it, or which npm and node version to use, how to build and run the program?

-> I would like to try to implement uPnP and try different things around, but a noob like me with NodeJS will have a really hard time. I googled all possible combinations with not much luck atm. Yesterday I run it from vsCode but today with the repo clone I'm having problems. So I guess the best it includes like a little documentation.

Thanks! Appreciate your work.

**Comment by PaTiToMaSteR** [comment]
buble 0.19.8 doesn't solve the problem, nor jump to the branch related with that update. the master version :
Commit: 9a0a2111d3b80bb986df80686305e897e9f48b53 [9a0a211]
Parents: d0053dc2f4, c990738c57
Author: Borewit <Borewit@users.noreply.github.com>
Date: 12 May 2019 20:18:20
Committer: GitHub

Works out of the box.

**Comment by feross** [comment]
Use any modern version of Node.js (10 or higher) and you should have no issues getting things up and running. The contributor guide is here: https://github.com/webtorrent/webtorrent-desktop#how-to-contribute

What is `launch.json`? Never heard of it before.

I'm closing this issue since there's no bug to fix here, but feel free to continue discussion! ✨
