### ISSUE TITLE
Subtitles in chromecast

### ISSUE THREAD

**Issue by marcosdipaolo** [webtorrent/webtorrent-desktop#1619]
It's been posted before but i couldn't find a solution. 
I'm using webtorrent desktop  and i'm not able to cast to Chromecast 2 with subtitles, even with vtt format. 
Is there a solution?
macos sierra here.

**Comment by feross** [comment]
This should already be fixed. See: https://github.com/webtorrent/webtorrent-desktop/pull/1165

**Comment by dev-myatminsoe** [comment]
I'm using WebTorrent 0.20.0 on macOS Mojave with Chromecast 3rd gen. Subtitles are not working.

**Comment by feross** [comment]
We need to release a new version and then you'll see the fix. You can follow https://github.com/webtorrent/webtorrent-desktop/issues/1674
