### ISSUE TITLE
some bitchute pages consistently fail

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [webtorrent/webtorrent-desktop#1621]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.20.0 (0.99.3) 64 bit linux
**What operating system and version?**
homerolled Ubuntu 18.04 made from mini.iso with X, lightdm, & openbox,  like a lighter Lubuntu.

**What did you do?**

With webtorrent-desktop already running normally in a window, from script or terminal:
nohup webtorrent-desktop "$mag_link" &
sleep 5
with this value for mag_link:
magnet:?xt=urn:btih:a1c0e0c986b2e134835c428d478824794f92ae7d&dn=h77v1dKCXF8F.mp4&tr=udp://explodie.org:6969&tr=udp://tracker.coppersurfer.tk:6969&tr=udp://tracker.empire-js.us:1337&tr=udp://tracker.leechers-paradise.org:6969&tr=udp://tracker.opentrackr.org:1337&tr=wss://tracker.openwebtorrent.com&as=https://seed41.bitchute.com/9c7qJvwx7YQT/h77v1dKCXF8F.mp4&xs=https://www.bitchute.com/torrent/9c7qJvwx7YQT/h77v1dKCXF8F.webtorrent

This was extracted from a regular bitchute page and looks just like any other magnet link extracted from any other bitchute page in the same manner.  It's a good page, because it plays fine in palemoon.
There are no copyright issues here, btw, because the publisher frequently  encourages viewers to copy his material, edit it at will and repost it.
**What did you expect to happen?**
For that video to start downloading, like 95% of similar links do.

**What actually happened?**
Stays at 0% with message "Downloading torrent info . . ."

I've seen this before. It doesn't like particular pages.

**Comment by feross** [comment]
The magnet link you have shared has a broken `xs` (exact source) parameter. You can see that the URL https://www.bitchute.com/torrent/9c7qJvwx7YQT/h77v1dKCXF8F.webtorrent returns a 404 page. That means if there are no active peers, then WebTorrent Desktop will be unable to obtain the `.torrent` file and proceed with the download even if the `as` parameter points to a valid web seed URL.
