### ISSUE TITLE
Doesnt work with VLC Flatpak and Snap

### ISSUE THREAD

**Issue by danrobi11** [webtorrent/webtorrent-desktop#1623]
Doesnt work with VLC Flatpak nor Snap
Is there another video player i could use?
VLC Snap version: 3.0.7.1 Vetinari
VLC Flatpak version 3.0.7.1 Vetinari
Version of WebTorrent Desktop: 0.20.0 (0.99.3) (64-bit)
Operating system and version: Ubuntu 18.04 LTS

**Comment by feross** [comment]
Can you share where is VLC installed with each of these versions? That would help us ensure that we properly detect VLC in these locations. Thanks!
