### ISSUE TITLE
It just doesn't work properly

### ISSUE THREAD

**Issue by Lyoxxo** [webtorrent/webtorrent-desktop#1624]
It just doesn't work properly
The downloads freezes. The time left, the speed... just freeze. I have to restart the software
While streaming, it stops, for no reason, because the download is well advanced...
The audio is not synchronised. I have to press to pause and depause, to synchronise it.
I use it with vlc.
It simply doesn't work. It suppose to stream, but there are many problems that interupt me watching my stuff.

**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
last one
**What operating system and version?**
windows 10 pro
**What did you do?**
nothing, i tried to stream
**What did you expect to happen?**
to work
**What actually happened?**
it didn't

**Comment by Plasmoxy** [comment]
same here, it just freezes randomly and my pc is turned on during the whole night for nothing

**Comment by feross** [comment]
Sorry that WebTorrent Desktop is not working for you. We're aware of lots of issue and future versions will hopefully be better. If you frequently get freezes, I recommend you only add one torrent at a time until we are able to improve the resource management of the core torrent engine.

**Comment by Lyoxxo** [comment]
I never downloaded/streamed more than one at a time.

**Comment by feross** [comment]
Can you check your CPU utilization when you notice the app freezing? Please let us know if you see that it's at 100% CPU.
