### ISSUE TITLE
Abruptly Stopped Working

### ISSUE THREAD

**Issue by Reznor9** [webtorrent/webtorrent-desktop#1625]
Version 0.20.0 (0.98.21) (64-bit) on Win10

I have files that I have downloaded previously, files that are currently downloading, and files I want to add. Nothing has changed on my comp except now nothing is downloading and when I try to add new files, they just get stuck on "Loading torrent...", even if there are a large number of sources.

Tried restarting desktop app, then computer, nothing makes it work.

**Comment by vikz95** [comment]
The same thing happened to me, I reinstalled the app and now it works again.

**Comment by feross** [comment]
@Reznor9 Sorry to hear this happened to your WebTorrent Desktop app.

Can you try to reproduce this error once more? But this time when it happens, click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

If you don't see any errors, then please check in one more place! Click View > Developer > Show WebTorrent Process, select the Console tab and copy-paste all the text.

Being able to see that output would help us out very much. Thanks.
