### ISSUE TITLE
Play buttons no longer work after coming back from streaming mode

### ISSUE THREAD

**Issue by roywilkie** [webtorrent/webtorrent-desktop#1629]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.20.0 (0.99.3)

**What operating system and version?**
macOS 10.14.4 (18E226)

**What did you do?**
Stream torrent, then use back button, then try to play (any file) using play buttons

**What did you expect to happen?**
The play buttons would continue to function

**What actually happened?**
They don't, zero response when clicked - no color change, etc. You have to quit and restart webtorrent - then they work again.

**Comment by feross** [comment]
Does this happen consistently? If you can get it to happen again, can you look at the CPU utilization of WebTorrent and let us know if it's at 100%? If that's the case, then it's a known issue. 

Can you try to reproduce this error once more? But this time when it happens, click View > Developer > Developer Tools, select the Console tab and copy-paste all the text into a new comment here.

If you don't see any errors, then please check in one more place! Click View > Developer > Show WebTorrent Process, select the Console tab and copy-paste all the text.

Being able to see that output would help us out very much. Thanks.

**Comment by roywilkie** [comment]
On Sat, Aug 3, 2019, at 21:19, Feross Aboukhadijeh wrote:
> Does this happen consistently? If you can get it to happen again, can 
> you look at the CPU utilization of WebTorrent and let us know if it's 
> at 100%? If that's the case, then it's a known issue.

Yes, very. Activity Monitor says the CPU usage is 0% after, then 0-10% or so when I click on stuff (behaves normally).

> 
> Can you try to reproduce this error once more? But this time when it 
> happens, click View > Developer > Developer Tools, select the Console 
> tab and copy-paste all the text into a new comment here.
> 

There's no way to copy text from the console (can't even right-click or anything), but I'll attach a screenshot of what looks to be what happened after I returned from playing the video - in red. If you can't see it; the line above where the error seems to have occurred is "Playback Priority : resuming paused torrents...", then directly below in red is "Uncaught TypeError: Cannot read Property 'status' of undefined' at TorrentListController.toggleTorrent ... ", then several more lines of 'at ...'

**Comment by akvadrako** [comment]
I consistently experience this behaviour, first on macOS, now on Linux. Both when using the built-in player and when using VLC. I don't see 100% CPU usage.

**Comment by jj970** [comment]
I have the same issue.

has been an issue for months. 
Recently switched to Catalina macOS 10.15.1
have most recent webtorrent build.  0.21.0

I can stream one torrent using the play button.
Once that is done and closed out, the play buttons no longer function.
If I close and reopen, it will reset and work one more time.

Strange.

**Comment by feross** [comment]
Has anyone been able to reproduce this issue on the latest versions of WebTorrent? For example, v0.24.0 or later?

**Comment by michaeldelhaye** [comment]
I have this issue v0.24.0 (0.108.6), macOS 11.5.2
See also #1915
