### ISSUE TITLE
Doesn't work on macosx properly

### ISSUE THREAD

**Issue by vraj6198** [webtorrent/webtorrent-desktop#1631]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

**What operating system and version?**

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by vraj6198** [comment]
not working properly in the macosX

**Comment by feross** [comment]
It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.
