### ISSUE TITLE
Stop shipping 32-bit binaries

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent-desktop#1637]
We currently offer 32-bit binaries on Windows and Linux. I'd like to stop shipping these and go 64-bit only. It'll mean less work for us. And the 32-bit builds have always had a higher chance of fatal errors due to running out of the limited memory address space available to 32-bit processes.

The [latest OS stats](https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam) indicate that 32-bit OSs are almost completely gone.

<img width="395" alt="Screen Shot 2019-08-04 at 10 30 54 AM" src="https://user-images.githubusercontent.com/121766/62427132-38c6fc00-b6a3-11e9-9f4f-d7a59f63356d.png">

Windows 7 32-bit is 1.06% and Windows 10 32-bit is 0.19% of overall usage. Linux 32-bit doesn't even show up on the list. Users on 32-bit systems can continue to use the current version of WebTorrent Desktop which will continue working just fine. Or they can build WebTorrent Desktop from source.

Feedback welcome.

**Comment by hicom150** [comment]
I think it is a good decision to go forward and more given that electron is [discontinuing support for 32-bit Linux](https://electronjs.org/blog/linux-32bit-support)

**Comment by feross** [comment]
> I think it is a good decision to go forward and more given that electron is [discontinuing support for 32-bit Linux](https://electronjs.org/blog/linux-32bit-support)

Well, looks like our decision has been made for us, at least on Linux. We use Electron 4 at the moment.

**Comment by Borewit** [comment]
I agree with dropping support for 32-bit Linux, but I would give issue #1584 another tought.

Unless you only want support Debian Linux, I don't think a zip is sufficient to satisfy the non-Debian part of Linux community. A "simple user" does not accept a zip file, he wan't something which installs like an app, and he can rid with same speed. As simple as the app store on your iPhone.

I think that is in line with your vision keeping webtorrent-desktop a simple no-nonse torrent client accessible for every user (users which do hang around on GitHub).

**Comment by feross** [comment]
> Unless you only want support Debian Linux, I don't think a zip is sufficient to satisfy the non-Debian part of Linux community. A "simple user" does not accept a zip file, he want something which installs like an app, and he can rid with same speed. As simple as the app store on your iPhone.

Happy to consider other packaging formats for Linux. I know there are many and I'm definitely not an expert on the pros and cons of each. Those issues you linked look like the right place to have that discussion.

**Comment by thevirajshelke** [comment]
Considering that Web Torrent is a hybrid desktop application made on top of electron framework, I think the move of not shipping 32-bit binaries is perfect.

As @hicom150 said even Electron has stopped support for 32-bit Linux starting with electron v4.0

@feross The package.json of the master branch is already using electron 6.0 right? When can we expect v0.21.0 & what electron version will be shipped with this version?

**Comment by feross** [comment]
@thevirajshelke v0.21.0 will ship with Electron 6.0. You can follow the progress here: https://github.com/webtorrent/webtorrent-desktop/issues/1674

**Comment by thevirajshelke** [comment]
@feross Awsome! The milestone seems to be 75% complete. Only 2 issues are open as of now one is this and the other one is #1430 after that release seems to be good to go :)

**Comment by feross** [comment]
This is completed and WebTorrent Desktop 0.21.0 is released.

**Comment by thevirajshelke** [comment]
Superb! :+1:
