### ISSUE TITLE
Refreex Playlists integration (shareable playlists with torrents)

### ISSUE THREAD

**Issue by RecoX** [webtorrent/webtorrent-desktop#1639]
Hi guys after work a couple months in this idea I have something that perhaps can be useful
Consume multimedia from torrents is awesome as all you already know but services like `spotify` offers some advantages, like creating playlists from infinite albums, share it with friends, etc.

I been working on a fork of `WebTorrent` called `Refreex` (is in a super early stage, better said is just a prototype to make this idea real.)
But the basics ideas around the Refreex Playlists (is the name of this kind of playlists, just to avoid confusions)

Now is in the point that the basic stuff like:
- Create a Refreex Playlist
- Add Song to the Refreex Playlist
- Add Full Album to the Refreex Playlist
- Remove Song from the Refreex Playlist
- Select Current Refreex Playlist
- Share button to share the Refreex Playlist ( atm is just coping it in plain text but could be a good idea in the future implement DAT protocol for this )
- Paste, Drag and Drop or select Refreex Playlist from selector file, and the app will load all the torrents and files in the Refreex Playlists.
- Modifications in the UI to make it more usable as a music program, a spotify like interface (but ugliest XD)

Pretty much that are all the changes made it

I was wondering if these kind of changes can be implemented somehow in WebTorrent as if this is possible there is no necessity of continue working on the Fork and all the effort can be implemented on here.

Here you can find more info about those Refreex Playlists
https://github.com/refreex/refreex-webtorrent-desktop

**Comment by feross** [comment]
Can you share screenshots of what this looks like?

While this sounds cool, to be honest this sounds like it's a bit too specific of a feature for WebTorrent Desktop. I would prefer if we didn't change the current model where torrents are the top-level item in the app that users interact with. It sounds like you allow users to make audio playlists from individual files in a torrent. While this is cool, I expect only a small number of WebTorrent Desktop users would use it and we generally only add features that benefit most users.

**Comment by RecoX** [comment]
Hi thanks for the quick reply.

The idea was with music in mind, but it will work at all the levels, as the format of the `Refreex Playlists` is simple and is not attached to a media type:

**Refreex Playlists (JSON properties definitions):**
The first one is `id` this one must be unique and we cannot have two Refreex Playlist with the same id in the App. Is the name of the playlist.

The second one is `torrents` this one is an array of objects. Those objects are the torrents indeed and they are composed by two properties the `infoHash` of a torrent and the `files` that you want to add to the playlist

<sub><sup>For the future / ideas: We can share at the moment the playlists in plain text, json files and the app will know how to read it parse it and download it. I been thinking for the future that the Refreex Playlists should be created using DAT protocol to allow mutation of the playlist (torrents are immutables).</sup></sub>
```
{
  "id": "NameOfThePlaylist",
  "torrents": [
    {
      "infoHash": "a80fda124873fa7d93937d9c607f206e00559269",
      "files": [
        "Dexter_Britain_-_03_-_In_The_Electric_Fields.mp3",
        "Dexter_Britain_-_01_-_The_Time_To_Run_Finale.ogg"
      ]
    },
    {
      "infoHash": "4b53bd8f85a653adcc9cc66aaa7500b946ab06b9",
      "files": [
        "Cloudkicker_-_10_-_You_and_yours.ogg",
        "Cloudkicker_-_10_-_You_and_yours.mp3",
        "NeZoomie_-_04_-_Heavy_Phat_Gun.mp3"
      ]
    },
    {
      "infoHash": "1c4bfb44845f584fc0cf343edb4fc67bc177bb1b",
      "files": [
        "art_of_war_01-02_sun_tzu.mp3"
      ]
    },
    {
      "infoHash": "a88fda5954e89178c372716a6a78b8180ed4dad3",
      "files": [
        "05 - Spoon - Revenge!.mp3",
        "16 - Matmos - Action At A Distance.mp3"
      ]
    }
  ]
}
```
Said that, this can work with:

Video / Movies / Series, people can have his own playlists for Movies Collection, TV Series seasons, from differents torrents

Music, well there is not much to say here, but from random playlists with mix music to discographies of an single artists with multiples torrents.

PDF, Books, someone can use this to create "book-shelfs" and again, from random titles to the complete collection from a single artist from different torrents files

Backups/Share all torrents downloaded (??) I just imagine another kind of uses that we can do with this.

Here are some pictures, this is not the final result of course and it will change, but is enough to show you the concept/idea in action.

![Screen Shot 2019-08-06 at 11 01 27 AM](https://user-images.githubusercontent.com/5874806/62500642-9a21d300-b83b-11e9-8046-143c8b0a1537.png)
![Screen Shot 2019-08-06 at 11 02 11 AM](https://user-images.githubusercontent.com/5874806/62500643-9aba6980-b83b-11e9-9927-c79d22af4ff8.png)
![Screen Shot 2019-08-06 at 11 13 40 AM](https://user-images.githubusercontent.com/5874806/62500644-9aba6980-b83b-11e9-991b-9e0a5085d268.png)

Thanks for your attention
Lucas.
