### ISSUE TITLE
Segfault on launch Arch Linux

### ISSUE THREAD

**Issue by aurabindo** [webtorrent/webtorrent-desktop#1644]
**What version of WebTorrent Desktop?** 0.20.0

**What operating system and version?** Arch Linux, x86_64

**What did you do?** Open webtorrent-desktop in command line

**What did you expect to happen?** Open normally

**What actually happened?** `Segmentation fault (core dumped)`

Backtrace:

```
#0  0x0000000002175b8e in hb_face_reference_table ()

```

Full: https://paste.ubuntu.com/p/7vNfd6CtWP/

It was all working fine, but all of a sudden this happened. I dont quite remember doing anything particular that might make webtorrent crash. I did delete some cache, but dont quite remember which files.

**Comment by feross** [comment]
If you `git clone` this repo then you can run `npm run clean` to delete all settings files uses by WebTorrent Desktop. This may fix your issue. 

We're also updating the version of Electron we use internally, which may fix crash errors like this one. If you wait until the next version of the app is released and give it a shot, your issue may be resolved. 

In the meantime, since Arch is not one of the Linux variants that we officially support, I'm going to close this issue.

**Comment by aurabindo** [comment]
Thanks. I do not have the crash when building from master. Nevertheless there is an error when I do npm clean, likely related to https://github.com/isaacs/rimraf/issues/111

**Comment by TeknoMobil** [comment]
Hello there
when will the next release be released?

**Comment by boskote** [comment]
I found that downgrading the pango package in arch linux to version 1.43 is a workaround for this error with segfault at launch. 

It seems that the error is related to the change in version 1.44 of pango to the HarfBuzz font loader - more info here: https://wiki.archlinux.org/index.php/Fonts#Bitmap

**Comment by TeknoMobil** [comment]
> I found that downgrading the pango package in arch linux to version 1.43 is a workaround for this error with segfault at launch.
> 
> It seems that the error is related to the change in version 1.44 of pango to the HarfBuzz font loader - more info here: https://wiki.archlinux.org/index.php/Fonts#Bitmap

Thank you very much was in the end

**Comment by feross** [comment]
@boskote @TeknoMobil I'm happy that you found a workaround to your issue. If you're able to help out the project a bit more, could I ask you to try upgrading to 1.44 again and testing with the version of WebTorrent Desktop that is in this GitHub repo? This is going to be released as the next version very soon, so it would be good to know if the updated version of Electron we are using resolves this issue. Thanks!

**Comment by TeknoMobil** [comment]
> @boskote @TeknoMobil I'm happy that you found a workaround to your issue. If you're able to help out the project a bit more, could I ask you to try upgrading to 1.44 again and testing with the version of WebTorrent Desktop that is in this GitHub repo? This is going to be released as the next version very soon, so it would be good to know if the updated version of Electron we are using resolves this issue. Thanks!

Sorry I don't know the source code setup :S

**Comment by TeknoMobil** [comment]
> @boskote @TeknoMobil I'm happy that you found a workaround to your issue. If you're able to help out the project a bit more, could I ask you to try upgrading to 1.44 again and testing with the version of WebTorrent Desktop that is in this GitHub repo? This is going to be released as the next version very soon, so it would be good to know if the updated version of Electron we are using resolves this issue. Thanks!

Yes git version works, latest version packages :+1: 
Electron: 6.0.7
Pango: 1:1.44.6

Test: Arch Linux

![DeepinScreenshot_20190907151236](https://user-images.githubusercontent.com/42881121/64474774-0026b080-d182-11e9-9eca-62a01eb7fdb8.png)

**Comment by feross** [comment]
@TeknoMobil Thank you so much for testing this for us. ❤️ You can follow the progress toward releasing the next version here: https://github.com/webtorrent/webtorrent-desktop/issues/1674

**Comment by delthas** [comment]
To downgrade to Pango 1.43 on Ubuntu 20.04:
```shell
curl -O http://archive.ubuntu.com/ubuntu/pool/main/p/pango1.0/libpango-1.0-0_1.42.4-7_amd64.deb
curl -O http://archive.ubuntu.com/ubuntu/pool/main/p/pango1.0/libpangocairo-1.0-0_1.42.4-7_amd64.deb
curl -O http://archive.ubuntu.com/ubuntu/pool/main/p/pango1.0/libpangoft2-1.0-0_1.42.4-7_amd64.deb
sudo apt-get install -y -q ./*.deb
```
