### ISSUE TITLE
Setup an alternative chat channel

### ISSUE THREAD

**Issue by Borewit** [webtorrent/webtorrent-desktop#1656]
In my opinion the current [Gitter](https://gitter.im/webtorrent/webtorrent) channel doesn't work.

What about setting up a [Discord](https://discordapp.com/) chat channel?

**Comment by Borewit** [comment]
I took the liberty to setup a trial: [![Discord](https://img.shields.io/discord/612575111718895616.svg)](https://discord.gg/mEAWTKv), feel free to join.

**Comment by Borewit** [comment]
Channel accepted and handed over to @feross, we hope to see you around.

**Comment by feross** [comment]
I just added links to the `webtorrent` and `webtorrent-desktop` readme files, replacing the Gitter links.
