### ISSUE TITLE
If I donate for BiglyBT, will the pop-up stop?  

### ISSUE THREAD

**Issue by JustCallBen** [webtorrent/webtorrent-desktop#1659]
When I click on magnet links, the trackers begin to look for the metadata.  Once that is found, BiglyBT pops up a dialog box asking for a donation.  This does two things: it pauses the download waiting for a click on one of the donation links or "Close".  Further, while this dialog box is open, if other magnets have been clicked, the process completely stops.

I must click on one magnet, wait for the pop-up, close it and then I can find another magnet.  Clicking on multiple magnets causes all subsequent metadata downloads to freeze and fail.

I don't mind donating but will this behavior - and the begging for money - stop after I donate?

**Comment by feross** [comment]
You are posting on the wrong issue tracker. We have nothing to do with the app you mentioned. This place is for issues related to [WebTorrent Desktop](https://webtorrent.io/desktop/).
