### ISSUE TITLE
Got an "Audio codec unsupported" from time to time

### ISSUE THREAD

**Issue by Borewit** [webtorrent/webtorrent-desktop#1668]
**What version of this package are you using?**
PR: #1666, but I have seen it before.

**What operating system, Node.js, and npm version?**
OS: Windows 10
Node: v10.13.0
NPM: 6.9.0

**What happened?**
I cannot play a FLAC file from time to time. Got an error an error: 'Audio codec unsupported'
![image](https://user-images.githubusercontent.com/23255260/64317582-75468a00-cfb8-11e9-8ded-8841b06b52ad.png)

**What did you expect to happen?**
My computer to explode, thank goodness that was not the case.

**Are you willing to submit a pull request to fix this bug?**
I will have a look

**Reproduce**
Torrent: [Various Artists - 2008 - netBloc Vol 13 (color in a world of monochrome) {BSCOMP0013} [FLAC].zip](https://github.com/webtorrent/webtorrent-desktop/files/3577804/Various.Artists.-.2008.-.netBloc.Vol.13.color.in.a.world.of.monochrome.BSCOMP0013.FLAC.zip)

Click on playing tracks nervously.

**Comment by feross** [comment]
The way that we detect unplayable media seems error prone, but it's unclear how to improve it. This seems like a false positive maybe caused by timing?

**Comment by Borewit** [comment]
> This seems like a false positive maybe caused by timing?

It does seems to be related to timing indeed.

**Comment by hicom150** [comment]
I haven't been able to reproduce this issue 😓

> The way that we detect unplayable media seems error prone, but it's unclear how to improve it.

Maybe we can do some experiment with `HTMLMediaElement.play() Promise` based on what it is explained in [this](https://developers.google.com/web/updates/2016/03/play-returns-promise) article.

**Comment by hicom150** [comment]
I add #1711 to try to fix this issue 😉
