### ISSUE TITLE
Add a "Release Notes" link to the Help menu

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent-desktop#1671]
It should link to https://github.com/webtorrent/webtorrent-desktop/releases

This should be relatively easy to do. Good task for someone newer to the WebTorrent Desktop project :)

**Comment by SingularReza** [comment]
This and #1670 can be closed

**Comment by Borewit** [comment]
Released in [v0.21.0](https://github.com/webtorrent/webtorrent-desktop/releases/tag/v0.21.0)
