### ISSUE TITLE
Release WebTorrent Desktop 0.21.0

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent-desktop#1674]
I'll share updates about my progress making this release. Haven't done a release in a while, so there's bound to be hiccups. 😉

**Comment by feross** [comment]
Located backup drive with signing keys and certificates. They're in the name "Feross Aboukhadijeh". I already switched the developer account to "WebTorrent, LLC" so could generate new certs but concerned that this cause issues with the autoupdate (would need to do more testing) or issues with new Mac app notarization requirements (see https://github.com/webtorrent/webtorrent-desktop/issues/1675, but old certificates don't have as strict of requirements, for now)

**Comment by feross** [comment]
Able to build the Mac app without issues. Tested it and it's properly signed! Hooray!

```
check-signature dist/WebTorrent.app
(c) 2014 Apple Inc.  All rights reserved.
YES
```

**Comment by feross** [comment]
Downloaded the app from a browser so the Quarantine bit is set and confirmed that it opens without the need to Right Click > Open. Though, there's a scarier first-run dialog than there is for older versions of WebTorrent.

Old:

<img width="532" alt="Screen Shot 2019-09-05 at 11 00 45 PM" src="https://user-images.githubusercontent.com/121766/64404535-1d983500-d031-11e9-9b38-7318c93c22ed.png">

New:

<img width="532" alt="Screen Shot 2019-09-05 at 11 01 29 PM" src="https://user-images.githubusercontent.com/121766/64404540-20932580-d031-11e9-8a9d-700170b5c177.png">

The fact that Apple supposedly analyzed the old version makes me think they're scraping binaries that Safari users download and checking them for malware. And they've added the old WebTorrent binaries to their database as safe even though they are only signed, **not** notarized. Fascinating.

**Comment by feross** [comment]
The `nobin-debian-installer` package doesn't work on Node 10 due to calling a function without a callback. So I forked it, pulled in the PRs from @hicom150, and we're now using it (https://github.com/webtorrent/webtorrent-desktop/issues/1676). 

Tested the .deb file on Ubuntu. Seems to work.

**Comment by feross** [comment]
Booting my Windows 10 VM. Loaded signing keys. Updated to latest Node.js and Git. Ready to try building and signing the app.

**Comment by feross** [comment]
Ran into a snag. Running the app on Windows, I currently get:

```
(node:8156) UnhandledPromiseRejectionWarning: NestedError: Cannot write to `C:\Users\Feross Aboukhadijeh\AppData\Local\WebTorrent\Posters\88594aaacbde40ef3e2510c47374ec0aa396c08e.jpg`: EPERM: operation not permitted, open 'C:\Users\Feross Aboukhadijeh\AppData\Local\WebTorrent\Posters\88594aaacbde40ef3e2510c47374ec0aa396c08e.jpg'
    at cpFileAsync (C:\Users\Feross Aboukhadijeh\code\webtorrent-desktop\node_modules\cp-file\index.js:34:10)
Caused By: Error: EPERM: operation not permitted, open 'C:\Users\Feross Aboukhadijeh\AppData\Local\WebTorrent\Posters\88594aaacbde40ef3e2510c47374ec0aa396c08e.jpg'
(node:8156) UnhandledPromiseRejectionWarning: NestedError: Cannot write to `C:\Users\Feross Aboukhadijeh\AppData\Local\WebTorrent\Posters\88594aaacbde40ef3e2510c47374ec0aa396c08e.jpg`: EPERM: operation not permitted, open 'C:\Users\Feross Aboukhadijeh\AppData\Local\WebTorrent\Posters\88594aaacbde40ef3e2510c47374ec0aa396c08e.jpg'
    at cpFileAsync (C:\Users\Feross Aboukhadijeh\code\webtorrent-desktop\node_modules\cp-file\index.js:34:10)
Caused By: Error: EPERM: operation not permitted, open 'C:\Users\Feross Aboukhadijeh\AppData\Local\WebTorrent\Posters\88594aaacbde40ef3e2510c47374ec0aa396c08e.jpg'
```

Anyone have an idea why I wouldn't have permission to write to `C:\Users\Feross Aboukhadijeh\AppData\Local\WebTorrent\Posters\`? Oddly, when I open that folder up, the poster images are actually there, seemingly with no problem.

Help wanted.

**Comment by Borewit** [comment]
> Anyone have an idea why I wouldn't have permission to write

Cannot reproduce the issue, posters are added without an error on my Windows 10 system.

**Comment by feross** [comment]
@Borewit Are you running the very latest version of Windows 10, with all updates applied? I wonder if something changed in a recent version?

**Comment by bit-for-byte** [comment]
@feross How can I build this myself on macOS? I tried to build it in the past, but ran into some kinds of strange security errors. Specifically, I had used the instructions on the README file. If you could give some more solid or specific commands to run, that would be very helpful. I've been suffering a lot from [this issue](https://github.com/webtorrent/webtorrent-desktop/issues/353) lately and it would be great if I could finally run Webtorrent without the CPU flying to the moon.

**Comment by feross** [comment]
@bit-for-byte You just need to run `npm run package -- darwin`. Best of luck!

**Comment by feross** [comment]
WebTorrent Desktop 0.21.0 is released!

**Comment by feross** [comment]
Announcement tweet: https://twitter.com/WebTorrentApp/status/1173034415414480896

**Comment by Borewit** [comment]
That is great news!

**Comment by conorseed** [comment]
Fantastic :) Thanks for the hard work @feross!

**Comment by feross** [comment]
Thanks everyone :)
