### ISSUE TITLE
Consider replacing `nobin-debian-installer`

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent-desktop#1676]
`nobin-debian-installer` seems abandoned by @grunjol. So I made a fork here (https://github.com/webtorrent/nobin-debian-installer) with the following fixes: 

- https://github.com/grunjol/nobin-debian-installer/pull/8 (thanks @hicom150)
- https://github.com/grunjol/nobin-debian-installer/pull/7 (thanks @hicom150)
- https://github.com/grunjol/nobin-debian-installer/pull/4 (my PR from 2017 that still hasn't made it into a release)

If @grunjol doesn't respond soon, we should probably replace this package with an alternative so we don't have to maintain our own fork.

**Comment by hicom150** [comment]
https://github.com/webtorrent/webtorrent-desktop/pull/1682 is a PR to try to replace `nobin-debian-installer` with `electron-installer-debian`.

Hope that it would help to make a step forward for more linux distribution support 😉

**Comment by grunjol** [comment]
Hi there!
I just checked your mention.
For some reason I didn't get the PRs notification. I will be glad to merge them and make a release this week.

Regarding the `electron-installer-debian`,  is the package cross-platform? or is *nix only?

**Comment by feross** [comment]
Thanks for responding @grunjol. What do you think of @hicom150's PR? It seems useful to be able to just add in other `electron-installer-*` packages following the same style and get support for more platforms, I think.

**Comment by hicom150** [comment]
> I will be glad to merge them and make a release this week.

That would be awesome! 👍

> Regarding the electron-installer-debian, is the package cross-platform? or is *nix only?

As far as it says in the [documentation](https://github.com/electron-userland/electron-installer-debian#requirements) this seems to support OSX and Linux.

**Comment by feross** [comment]
Yep, it worked on macOS for me. Since this is merged now and we can rely on the electron community to maintain it for us in the future, I think it was right call. Closing this now.
