### ISSUE TITLE
Delete downloaded files after watching

### ISSUE THREAD

**Issue by SingularReza** [webtorrent/webtorrent-desktop#1684]
**What version of this package are you using?**
Version 0.20.0 (0.98.21) (64-bit)

**What problem do you want to solve?**
There is no option to auto delete files after done watching. This was already requested in Issue #1401 and #1508 but I couldn't find any option in the application

**What do you think is the correct solution to this problem?**
Add an option to auto delete watched files

**Are you willing to submit a pull request to implement this change?**
Yes

**Comment by zakariyasattar** [comment]
How can I accept this feature request? Sorry, new to open source...

**Comment by subins2000** [comment]
How can the software know it it has been finished watching :thinking: ? Ask a prompt to delete when the playback reach the end ?
