### ISSUE TITLE
npm run package not working

### ISSUE THREAD

**Issue by RecoX** [webtorrent/webtorrent-desktop#1689]
**What version of this package are you using?**

**What operating system, Node.js, and npm version?**
node 8.16
npm 6.4

**What happened?**
When I run ` #npm run package` i get this error:

```
```
Windows: Creating installer...
spawn mono ENOENT
Linux: Packaging electron...
Packaging app for platform linux x64 using electron v6.0.9
Linux: Packaged electron. /Users/lucasrecoaro/webtorrent-desktop/dist/WebTorrent-linux-x64
Linux: Creating deb...
Error executing command (Exited with status 127):
fakeroot dpkg-deb --build /var/folders/c3/zjfb46q560jgk6l6c86x3w880000gr/T/electron-installer-62005ZSwE45ZFVWDV/webtorrent-desktop_0.20.0_amd64
/usr/local/bin/fakeroot: line 176: dpkg-deb: command not found
```

**Comment by shreyasborse** [comment]
You are not able to generate  .deb packages, Please try installing dpkg using

```brew install dpkg```

**Comment by hicom150** [comment]
As we have switched to https://github.com/electron-userland/electron-installer-debian for debian package creation, now we need this [requirements](https://github.com/electron-userland/electron-installer-debian#requirements) 😉

- `node` 8 or greater
- `fakeroot`
- `dpkg`

**Comment by feross** [comment]
I added a note to the readme about this: https://github.com/webtorrent/webtorrent-desktop/commit/6989484e7c0ed1ceab545c52ebbedaa9419a306d
