### ISSUE TITLE
UI not revealing on ubuntu 19.04

### ISSUE THREAD

**Issue by mahmed0715** [webtorrent/webtorrent-desktop#1691]
**What version of this package are you using?** latest on Sep19

**What operating system, Node.js, and npm version?** nodejs:10 and 6.9.0

**What happened?** Never comes the UI after installed

**What did you expect to happen?** UI should come

**Are you willing to submit a pull request to fix this bug?**

**Comment by feross** [comment]
This issue will likely be resolved when WebTorrent Desktop 0.21.0 is released: https://github.com/webtorrent/webtorrent-desktop/issues/1674
