### ISSUE TITLE
Add hicom150 to the WebTorrent organization

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent-desktop#1697]
Hey all!

I've been super impressed with the PRs from @hicom150 to WebTorrent Desktop. I'd like to add them to the WebTorrent GitHub organization to recognize their great work! What do folks think?

Also, @hicom150, is this something that you'd like?

**Comment by hicom150** [comment]
Wow, I'm flattered 😊
It would be a honor to be part of this awesome project! 😉

**Comment by feross** [comment]
Okay, I just added you. Welcome!

**Comment by Borewit** [comment]
Yes, very nice work @hicom150!
I am very happy to see you on board.
