### ISSUE TITLE
Support for extensions

### ISSUE THREAD

**Issue by SingularReza** [webtorrent/webtorrent-desktop#1700]
**What version of this package are you using?**
v0.21.0

**What problem do you want to solve?**
I feel like the ability to stream isn't that useful  without a ready source of content to browse and stream from.

**What do you think is the correct solution to this problem?**
Streaming functionality of this application can be used much better if we include support for extensions. For example, someone can make a bitchute extension which will allow the user to browse and watch bitchute videos directly from the application. This makes it more convenient and useful

**Are you willing to submit a pull request to implement this change?**
Yes.

**Comment by hicom150** [comment]
Related with https://github.com/webtorrent/webtorrent-desktop/issues/664

https://github.com/webtorrent/webtorrent-desktop/pull/1125 could be a good starting point 😉

**Comment by resession** [comment]
sounds like a nice feature
