### ISSUE TITLE
v0.21.0 "Error no version information available"

### ISSUE THREAD

**Issue by Francewhoa** [webtorrent/webtorrent-desktop#1705]
**What version of this package are you using?**
v0.21.0 from https://github.com/webtorrent/webtorrent-desktop/releases/tag/v0.21.0
webtorrent-desktop_0.21.0_amd64.deb

**What operating system, Node.js, and npm version?**
Debian 8 Jessie

**What happened?**

Steps to reproduce:
1. Using GNOME open WebTorrent
1. Nothing happens. It does not open.

**What did you expect to happen?**
1. WebTorrent to open

This challenge can't be reproduce with webtorrent-desktop_0.20.0-1_amd64.deb

**What happened?**
Steps to reproduce:

1. Using Terminal run this command `webtorrent-desktop`
1. Terminal return this error message

> webtorrent-desktop: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by webtorrent-desktop)
> [8315:0918/132724.215590:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /usr/lib/webtorrent-desktop/chrome-sandbox is owned by root and has mode 4755.
> Trace/breakpoint trap

**What did you expect to happen?**
1. WebTorrent to open without error message

This challenge can't be reproduce with [webtorrent-desktop_0.20.0-1_amd64.deb](https://github.com/webtorrent/webtorrent-desktop/releases/tag/v0.20.0)

**What I tried but did not work**

* Set all required permissions per the Terminal error message above
* Installed WebTorrent 0.21.0 over 0.20.0-1
* Fully removed WebTorrent 0.21.0. Then reinstall 0.21.0.

**Are you willing to submit a pull request to fix this bug?**
I'm not a developer. But I'm happy to contribute testing or documentation.

**Workaround**

1. Fully removed 0.21
1. Re-installed [webtorrent-desktop_0.20.0-1_amd64.deb](https://github.com/webtorrent/webtorrent-desktop/releases/tag/v0.20.0)
1. This work. But WT prompts user to update to 0.21.

0.20 works. But prompt me to update to 0.21

**Comment by Francewhoa** [comment]
Maybe a related ticket at https://github.com/webtorrent/webtorrent-desktop/issues/1699

**Comment by feross** [comment]
Thanks for opening this issue. Let's move the discussion to https://github.com/webtorrent/webtorrent-desktop/issues/1703
