### ISSUE TITLE
VLC closes when going back in WebTorrent

### ISSUE THREAD

**Issue by StructByLightning** [webtorrent/webtorrent-desktop#1708]
**What version of this package are you using?**
0.21.0 (0.107.16)

**What operating system, Node.js, and npm version?**
OS: Linux
Node: 8.10.0
NPM: 6.10.2

**What happened?**
Clicking the play icon sends WebTorrent to a black screen and opens VLC. Clicking the < arrow in that screen closes VLC.

**What did you expect to happen?**
WebTorrent shouldn't go to a black screen. Additionally, it should not close VLC, since they are separate programs.

**Reproduction**
1. Uncheck the "Play torrent media files using WebTorrent" checkbox in the preferences.
2. Click the play icon on a torrent
3. The app goes to a black screen and a VLC window opens.
4. Click the < arrow in WebTorrent. VLC closes.

**Are you willing to submit a pull request to fix this bug?**
Maybe? Is that something that would be welcomed?

**Comment by feross** [comment]
This is intentional. When you go back to the main screen the HTTP server is stopped, so there's no way for VLC to continue streaming the content.

**Comment by StructByLightning** [comment]
Why doesn't WebTorrent open the file in VLC normally? VLC can play a partially downloaded file if the first and last pieces are downloaded first.

**Comment by feross** [comment]
We need to see which part of the video you are trying to play if e.g. you seek the middle where the file is not downloaded. With an HTTP server, when VLC requests pieces from the middle of the file we can prioritize getting those pieces next from the torrent network.

**Comment by StructByLightning** [comment]
Ah, I see. That makes sense. I'm going to go ahead and close this -- you can still open the file manually in VLC and it would be silly to spend a lot of work on such a minor QOL improvement.

**Comment by feross** [comment]
You're most welcome.
