### ISSUE TITLE
Percentage complete display rounding issue

### ISSUE THREAD

**Issue by pR0Ps** [webtorrent/webtorrent-desktop#1713]
**What version of this package are you using?**
v0.21.0

**What operating system, Node.js, and npm version?**
macOS 10.14.6 (desktop application)

**What happened?**
The screenshot attached below shows a torrent at 99% downloaded. However, the completion percentage of each individual file has been rounded up to 100%. This makes it impossible to tell which of the file(s) is incomplete. In this specific case, I verified with another client that the torrent is 99.96% complete overall and one of the files is 99.71% complete.

**What did you expect to happen?**
I would expect that if a file is not fully complete, that it would not state "100%".

**Possible solutions:**
- Always round percentages down: Since percentages measure "completeness", it's generally not that bad if 0.99999% is displayed as 0% instead of 1%, as both clearly communicate "nowhere near done". It's a bit more critical that 99.99999% is clearly communicated to mean "not fully complete". This is already done for the total completion percentage.
- Special cases: If it's important to communicate the "has started" aspect of the 0.99999% case, special cases for 99% and 1% could be added (ie. show "1%" if >0% and <1%, show "99%" if >99% and <100%, otherwise round normally).

Personally, I'd also like if the percentages could be a bit more accurate (1 decimal place? 2?) but I understand that's more of a look-and-feel choice, not a bug (see #50)

**Are you willing to submit a pull request to fix this bug?**
Yes. I'll have a PR submitted in a few days that floors the percentage for the individual files before displaying them.

Screenshot (irrelevant information redacted):
![Screen Shot 2019-09-26 at 6 56 33 PM](https://user-images.githubusercontent.com/466941/65731520-febb1a80-e093-11e9-94fe-20116ca0d7e4.png)

**Comment by feross** [comment]
These changes sound great and I agree this should be fixed. Thank you for your attention to detail. Looking forward to your pull request.
