### ISSUE TITLE
Multi-language implementation

### ISSUE THREAD

**Issue by RecoX** [webtorrent/webtorrent-desktop#1718]
**What problem do you want to solve?**
I'm working on refreex.io a fork of webtorrent-desktop and people likes it, but some of them does not know what to do as the software is in english

I want to implement Multi-language on webtorrent-desktop so we can use the software in many languages.

**What do you think is the correct solution to this problem?**
Create some files under `Languages` folder for each language like `english.json`, `spanish.json`, etc and every file have in it all the texts required like

```
{
     MAIN_WINDOW_CREATE_TORRENT: 'Create Torrent',
     MAIN_WINDOW_DELETE_TORRENT: 'Delete Torrent',
}

```

Then thanks to this webpage:
https://www.logisticinfotech.com/translate-language-files-online-json/

with the json generated we can translated straight away to the language we want

We need to create a select input in the options menu with all the available languages in the application and that's it I think for now.

**Are you willing to submit a pull request to implement this change?**

Yes

**Comment by hicom150** [comment]
This is an interesting topic that already was discussing in #371
Could we continue talking about this implementation there? 😉
