### ISSUE TITLE
Could not calling the desktop from browser by visit the magnet link

### ISSUE THREAD

**Issue by xuhuanfeng** [webtorrent/webtorrent-desktop#1721]
**v0.21.0**

**Windows 10**

**What happened?**

I'm trying to visit the [magnet link](magnet:?xt=urn:btih:77C758F508765A133F763CACEF1AA75F40F5CA28&dn=%e9%ab%98%e8%8d%89%e4%b8%9b%e4%b8%ad.In.the.Tall.Grass.2019.HD720P.%e8%8b%b1%e8%af%ad%e4%b8%ad%e5%ad%97.BTDX8&tr=udp%3a%2f%2fexplodie.org%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.internetwarriors.net%3a1337%2fannounce&tr=https%3a%2f%2ftracker.vectahosting.eu%3a2053%2fannounce&tr=udp%3a%2f%2ftracker.supertracker.net%3a1337%2fannounce&tr=udp%3a%2f%2ftorrentclub.tech%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.msm8916.com%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.coppersurfer.tk%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.uw0.xyz%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.filepit.to%3a6969%2fannounce&tr=http%3a%2f%2ftracker.torrentyorg.pl%3a80%2fannounce&tr=https%3a%2f%2ftracker.fastdownload.xyz%3a443%2fannounce&tr=udp%3a%2f%2fbt.xxx-tracker.com%3a2710%2fannounce&tr=udp%3a%2f%2fretracker.lanta-net.ru%3a2710%2fannounce&tr=http%3a%2f%2fgwp2-v19.rinet.ru%3a80%2fannounce&tr=udp%3a%2f%2ftracker.gbitt.info%3a80%2fannounce&tr=udp%3a%2f%2ftracker.leechers-paradise.org%3a6969%2fannounce&tr=udp%3a%2f%2fretracker.baikal-telecom.net%3a2710%2fannounce&tr=udp%3a%2f%2fopen.demonii.si%3a1337%2fannounce&tr=http%3a%2f%2ftracker.gbitt.info%3a80%2fannounce&tr=http%3a%2f%2fopen.acgtracker.com%3a1096%2fannounce&tr=udp%3a%2f%2fretracker.akado-ural.ru%3a80%2fannounce&tr=udp%3a%2f%2ftracker01.loveapp.com%3a6789%2fannounce) throuhgt the chrome browser in my pc and I thought it can wake up the descktop app and continute to download, but nothing happened.

After reading the source code of the register-protocol-handler.js, I found that there may just an simple callback function without handling any business logic

So, is it possible to open the desktop app just via visit the magnet  link?

Best wish :)

**Comment by feross** [comment]
Yes, this feature should be possible. Make sure to click this button in the preferences:

<img width="436" alt="Screen Shot 2020-11-17 at 4 49 27 PM" src="https://user-images.githubusercontent.com/121766/99476570-a84b1400-2905-11eb-992b-d6ee20947fe2.png">
