### ISSUE TITLE
Unable to change external player

### ISSUE THREAD

**Issue by pgram1** [webtorrent/webtorrent-desktop#1722]
**What version of this package are you using?**

v0.21.0

**What operating system, Node.js, and npm version?**

Windows 10, the others are probably packaged with the software so I am not aware

**What happened?**

Trying to choose the external player, I opened the settings and clicked on the "change" button, and a file picker does not come up to do so. Then I tried to type the path of the binary in the field, in the settings section, but that field is not editable. Then I tried to open the config.json file in webtorrent's directory to track down where the path of the external player binary should be put, but did not manage to find it.

**What did you expect to happen?**

I expected to either get a Windows explorer.exe file picker window to pick the binary of the external player when pressing the "change" button, or be able to edit the path field in the settings section, or find the path section in the config.json file easily to edit it there.

**Are you willing to submit a pull request to fix this bug?**

I have not looked into the codebase at all, probably not.

**Comment by hicom150** [comment]
This issue is already fixed in #1702 but we didn't make a release yet 😓

Maybe @feross it could be a good time to prepare the release of  `0.21.1` given that all the issue in this  [milestone](https://github.com/webtorrent/webtorrent-desktop/milestone/18) are already fixed?

**Comment by Borewit** [comment]
> This issue is already fixed in #1702

Maybe close this issue?

**Comment by vladshcherbin** [comment]
Can this one get a release please? It's impossible to watch video if you don't have VLC and internal player has no needed audio codec.

**Comment by mathiasvr** [comment]
@vladshcherbin Hopefully, we can do a release soon.

For now you can fix it by opening Developer Tools: `View > Developer > Developer Tools`, press the `Console` tab, and enter the following command:
```js
state.saved.prefs.externalPlayerPath = ''
```

**Comment by vladshcherbin** [comment]
@mathiasvr wow, thanks, this lifehack is working even after a restart! 🎉

**Comment by leogallego** [comment]
I was about to create a new issue reporting a part of my problem but decided to look for closed issues just in case (by editing the default search parameters removing "is:open") and found this, that's related.

If there is no public release with a fix out (it seems 0.21.1 hasn't been released yet), I'm thinking it might be a good idea to keep it open with the workaround from the comment above:

> @vladshcherbin Hopefully, we can do a release soon.
> 
> For now you can fix it by opening Developer Tools: `View > Developer > Developer Tools`, press the `Console` tab, and enter the following command:
> 
> ```js
> state.saved.prefs.externalPlayerPath = ''
> ```

I'm having this same issue with Fedora Linux, using WebTorrent via Flatpak and with VLC installed.

My primary issue was that VLC wasn't detected (I think it has something to do with Flatpak sandboxing), but I wasn't able to change the external player path either. I'm still looking into this.

About this issue, I too had to run the js above to get the CHANGE button working.

**Comment by subins2000** [comment]
It would be good if the External player field is made editable.

**Comment by EchedeyLR** [comment]
Seems that even fixing it, setting a path for the player doesn't seem to be a solution for people using the Flathub version.

In NetBeans, when javadoc is used, a contextual menu is opened in the system asking for the browser to use, being the list of browsers showed installed in all the system and no only through flatpak, in order to view the generated documentation and that works in the Flathub version without the need of accessing the real path, which could be impossible.
