### ISSUE TITLE
Download path missing error prompt is displayed

### ISSUE THREAD

**Issue by Exagram** [webtorrent/webtorrent-desktop#1725]
**What version of this package are you using?**
0.20.0 (0.99.3) (64bit)
**What operating system, Node.js, and npm version?**
Linux 64bit 5.0.0-23
**What happened?**
A "Download path missing" error prompt is displayed below the file menu on program launch. Second I tried to locate "Downloads" but my sym-linked secondary hard drive could not display any files. Weird. My file explorer (gnome nemo) can view/access ALL files in my sym-linked secondary hard drive.
**What did you expect to happen?**
No error prompts should be displayed.
**Are you willing to submit a pull request to fix this bug?**
No - unless my Java/C# skills can be useful ;P.

**Comment by martinwheeler** [comment]
Hi @exagram, how did you create the sym-link so we are able to replicate this locally? I can test this on my machine to see what happens and share my findings.

**Comment by Exagram** [comment]
@martinwheeler

My files:
`/home/{username}/Downloads` <-- the sym link
`/media/{HDD name}/{username}/Downloads` <-- the hard link

Steps:
I first copied over the "Downloads" folder from my home drive to my external media storage.
I created the sym-link: `ln -s "/media/{HDD name}/{username}/Downloads" "/home/{username}/Downloads"`
