### ISSUE TITLE
Webtorrent under proprietary license?

### ISSUE THREAD

**Issue by danrobi11** [webtorrent/webtorrent-desktop#1726]
Hello. Why is webtorrent under proprietary license? Im using the flatpak version on flathub, says under free license. Although, im not sure you guys are maintaining the flatpak version.
![webtorrent proprietary license](https://user-images.githubusercontent.com/48020114/66959729-fe7dc180-f038-11e9-9942-aa7af975c905.png)

**Comment by RecoX** [comment]
https://github.com/webtorrent/webtorrent-desktop/blob/master/LICENSE
that is the license.

probably is a problem when the package is build?

**Comment by danrobi11** [comment]
> https://github.com/webtorrent/webtorrent-desktop/blob/master/LICENSE
> that is the license.
> 
> probably is a problem when the package is build?

I know about the license. Its weird and confusing. Im mostly new to linux and i want to know why its under proprietary. This should not happen. I would like to know If thats an issue coming from the software app. If so they must fix this real quick. This can push some users away.  
Same here with FreeTube[https://github.com/FreeTubeApp/FreeTube/issues/407](url)

**Comment by danrobi11** [comment]
More about this issue: https://github.com/lbryio/lbry-desktop/issues/1376#issuecomment-500421983

**Comment by hicom150** [comment]
It seems to be a `software-center package` [bug](https://bugs.launchpad.net/ubuntu/+source/software-center/+bug/435183) that does not display license properly.

As they commented on the bug report:

- "License: Open Source" for everything in main and universe
- "unknown" for things in multiverse
- "proprietary" for things in restricted

So although our package is correctly licensed we have to wait until the `software-center package` bug is fixed to see it correctly 😅

**Comment by danrobi11** [comment]
A Lubuntu dev did some digging about the license issue:

"I couldn’t found those packages in ubuntu repositories, so maybe there are some issues with the way the .deb was created. I downloaded FreeTube to look at it ( https://github.com/FreeTubeApp/FreeTube/releases/download/v0.7.1-beta/FreeTube_0.7.1_amd64.deb ) and couldn’t found a /debian folder in which, among others, the license in a machine readable format (copyright) should be placed. Maybe that’s why the system assume it is propietary. More info of copyright file: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/"

Source: https://discourse.lubuntu.me/t/deb-packages-license-issue/470/5

**Comment by hicom150** [comment]
More info in https://github.com/electron-userland/electron-builder/issues/4270

**Comment by danrobi11** [comment]
Got new comment from Lubuntu:
Source: https://discourse.lubuntu.me/t/deb-packages-license-issue/470/16

>    I don’t see that any of these packages have an appstream.xml or metainfo.xml as specified by the [AppStream specification](https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html) and their desktop entries are not readily found (another place metadata could come from). That also may be where the problem lies.

Or it could be a combination of these things. Either way, this illustrates a good point: software in the Ubuntu archives is carefully checked to ensure it meets a variety of different specifications to ensure it works properly with the whole ecosystem of applications available in the archives. When you’re using software from outside the archives, you’re bound to run into trouble. This sort of software is entirely unsupported by Ubuntu.

If you want this to work correctly, you will need to talk to the upstream developers and perhaps have them speak with the gnome-software developers to figure out the appropriate solution. Additionally, you should urge them to get their packages included into Debian. Those packages should get automatically synced to Ubuntu.
