### ISSUE TITLE
Getting Started Link for Material UI in README is broken

### ISSUE THREAD

**Issue by akaustav** [webtorrent/webtorrent-desktop#1734]
**What happened?**
The README.md file contains a broken link to Material UI (React components that implement Google's Material Design.): <https://material-ui.com/getting-started>

When I click on the link, it takes me to an error page showing:
![image](https://user-images.githubusercontent.com/11030959/67826342-6694c480-fa89-11e9-8c81-9cc5a1cef5fe.png)

**What did you expect to happen?**
Land into the Getting Started page for Material UI

**Are you willing to submit a pull request to fix this bug?**
Yes

**Comment by hicom150** [comment]
Fixed! 👍
