### ISSUE TITLE
About WebTorrent shows half window

### ISSUE THREAD

**Issue by akaustav** [webtorrent/webtorrent-desktop#1736]
**What version of WebTorrent Desktop are you using?**
0.21.0

**What operating system and version?**
Windows 10

**What happened?**
When I click on Help > About WebTorrent, I see a window which seems to display only the top half of the content. So, I can only see the application icon, but not the text (name, version number, etc) - like this:
![image](https://user-images.githubusercontent.com/11030959/67826959-83ca9280-fa8b-11e9-9bd0-84d244233a96.png)

**What did you expect to happen?**
To view the full information about the application. Similar to what was showing until the previous version [`v0.20.0`](https://github.com/webtorrent/webtorrent-desktop/releases/tag/v0.20.0).
![image](https://user-images.githubusercontent.com/11030959/67827963-e5403080-fa8e-11e9-9394-43f4e832cef0.png)

**Are you willing to submit a pull request to fix this bug?**
Not sure. I am a novice in Electron. However, it was fine in the previous version [`v0.20.0`](https://github.com/webtorrent/webtorrent-desktop/releases/tag/v0.20.0). I can try tracing the change log to find which commit(s) might have caused this.

**Comment by akaustav** [comment]
**Here is a log of what I have found so far:**

- Compared commits between `0.20.0` and `0.21.0` tags.
- From [electron documentation](https://electronjs.org/docs/api/browser-window#class-browserwindow), it looks like a window's height is controlled by the optional `height` property.
- The `height` property of the 'About' window is set at `170`.
https://github.com/webtorrent/webtorrent-desktop/blob/d7783749ca155e196cd5edbb5fae9f8c83414945/src/main/windows/about.js#L18
- That property has not changed since 2016-05-27
https://github.com/webtorrent/webtorrent-desktop/blame/d7783749ca155e196cd5edbb5fae9f8c83414945/src/main/windows/about.js#L18
- Noticed that `webtorrent-desktop@0.20.0` was using `electron@1.6.16`:
https://github.com/webtorrent/webtorrent-desktop/blob/fbb3fa6a270c4f41042ad8ce2f8c28a15d7e2007/package.json#L57
- And `webtorrent-desktop@0.21.0` is using `electron@~6.0.9`:
https://github.com/webtorrent/webtorrent-desktop/blob/d7783749ca155e196cd5edbb5fae9f8c83414945/package.json#L56
- I was able to reproduce this issue by running the app on my local Windows machine using latest (as of 2019-10-29) code in the `master` branch.
- I am attributing this bug to be one of the breaking changes during the `electron` upgrade.
- I am not sure how to check the documentation for `electron@1.6.16`.
- Tried setting the `height` property to a number greater than `170` like `220`. And it seems to make the window tall enough to display the full contents.
- At the moment, I do not have access to a machine running **Linux** or **macOS**. So, I am not sure if this is even an issue in those OS. And if my change breaks something in those OS.
- For now, I will raise a PR changing the `height` property to `220`.

**Comment by SikoSoft** [comment]
I experience the same thing, Windows 10 as well. No idea what version of WebTorrent I have since I can't see the information in the window, which is why I clicked it to begin with.

**Comment by akaustav** [comment]
@SikoSoft I am thinking you have version `0.21.0`. Here is the **the hard way** to find the information:

1. Open WebTorrent.
1. Go to Help > About WebTorrent.
1. Selecting all contents of the window, by pressing the `Ctrl + A` key combination.
1. Copy the selected contents to the clipboard, by pressing `Ctrl + C`.
1. Paste the clipboard contents on any text editor by pressing `Ctrl + V`.

**Comment by hicom150** [comment]
Fixed! 🎉
