### ISSUE TITLE
About window does not consider all supported architectures

### ISSUE THREAD

**Issue by mathiasvr** [webtorrent/webtorrent-desktop#1738]
The about window does not take other architectures than 64-bit and 32-bit into account, such as arm.
We should update the following line to properly display the supported architectures.

https://github.com/webtorrent/webtorrent-desktop/blob/d7783749ca155e196cd5edbb5fae9f8c83414945/static/about.html#L35

**Comment by mathiasvr** [comment]
I think maybe we should display the architecture more precise than just 32-/64-bit, but I’m not completely sure what’s best.

**Comment by hicom150** [comment]
I would leave the `process.arch` as is so we have can easily identify the architecture 😉

**Comment by mathiasvr** [comment]
Yeah I think the current approach is to mimic the macOS about role, but I agree with @hicom150 to display ‘process.arch’.

**Comment by hicom150** [comment]
https://github.com/webtorrent/webtorrent-desktop/pull/1752 with the proposed solution 😉

**Comment by hicom150** [comment]
Fixed! 🎉
