### ISSUE TITLE
Can't change external player

### ISSUE THREAD

**Issue by AR45H** [webtorrent/webtorrent-desktop#1753]
I just updated to 0.21 and I can't change the player.
Clicking on change doesn't do anything.
I'm on Win 10 64bit 1803.

**Comment by h0d** [comment]
Same for me on macOS 10.15.1. Fortunately, it works when I open the downloading file from the desired player.

**Comment by alxhotel** [comment]
Thanks for pointing this out @AR45H.

This issue has already been fixed in #1702.

You will see this fixed in the next release.
