### ISSUE TITLE
Choose between promise style or sync style when interacting with electron

### ISSUE THREAD

**Issue by hicom150** [webtorrent/webtorrent-desktop#1755]
After fixing some `electron@7` [bugs](https://github.com/webtorrent/webtorrent-desktop/pull/1751) related to the deprecation of [callback based version of functions](https://electronjs.org/releases/stable?version=7#breaking-changes), @alxhotel correctly bring the question of choosing to go full **promise style** or **sync style** when interacting with `electron`.

I created this issue so we can discus about it 😉

My opinion is to use **sync style** unless there is any drawback (performance, ...) 😅

What do you think?

**Comment by dsernst** [comment]
Sync definitely feels cleaner to avoid callback hell.

For UI interactions, my hunch is there shouldn’t be any detectable performance implications since it’s all bottlenecked by user interactions.

**Comment by feross** [comment]
If we're blocking to show a dialog to the user then using sync functions in the renderer seems fine!

(As long as we don't block in the webtorrent renderer – which would then cause all webtorrent work to stall.)

**Comment by feross** [comment]
Closing this issue, as I think we have consensus here
