### ISSUE TITLE
Search functionality — using trackerless (DHT) connections

### ISSUE THREAD

**Issue by heyakyra** [webtorrent/webtorrent-desktop#1756]
It would be nice to have built in search for Archive.org, Librivox, and all arbitrary torrents using trackerless (DHT-based) connections. 

There was once a cool project that did this: 
* https://web.archive.org/web/20160204020224/https://github.com/StrikeOrg/strike-search
* (mirror) https://github.com/jakop345/strike-search
* https://torrentfreak.com/strike-public-tracker-dht-searches-presented-cleanly-150321/

Now there is still https://github.com/btdig/dhtcrawler2

**Comment by feross** [comment]
This is an interesting suggestion, but we want to focus on making the core WebTorrent Desktop experience more reliable and performant before adding fancier features like this one.
