### ISSUE TITLE
VLC -- install location

### ISSUE THREAD

**Issue by JonnyTSpeed** [webtorrent/webtorrent-desktop#1761]
Unless VLC is installed in the root of /Applications on a mac, Webtorrent asks to install application rather than play content.  No option to specify VLC location.  Recommend recursive search through ~/Applications and /Applications

**Comment by hicom150** [comment]
You can specify VLC location in preferences 😉

![screenshot](https://user-images.githubusercontent.com/715354/71782415-e5523480-2fd9-11ea-9f4f-5e92b879f9ba.png)

**Comment by JonnyTSpeed** [comment]
Nothing happens when I click the button -- it just flashes.  All the rest
in preferences bring up a drop-down file browser.

**Comment by hicom150** [comment]
You are right this has been a known bug https://github.com/webtorrent/webtorrent-desktop/issues/1753 that has already been solved https://github.com/webtorrent/webtorrent-desktop/pull/1702 but not published as we are waiting for @feross to make a new release 😅

In the mean time you can use [this](https://github.com/webtorrent/webtorrent-desktop/issues/1722#issuecomment-543359517) tip to fix the problem 😉

**Comment by JonnyTSpeed** [comment]
Thank! That worked.

Thanks

A/ <adrian.jarvis@gmail.com>
