### ISSUE TITLE
Annoying volume overlay on Windows 10

### ISSUE THREAD

**Issue by pilsnerbeer** [webtorrent/webtorrent-desktop#1765]
**What version of WebTorrent Desktop are you using?**
v0.21.0
**What operating system and version?**
Windows 10
**What happened?**
Lately I have been getting this annoying volume control popup whenever webtorrent is opened.
![Screenshot_2](https://user-images.githubusercontent.com/36133540/71371010-01a0ab00-25b0-11ea-821e-b09fff4e1ac6.png)

**What did you expect to happen?**
Nothing, no extended volume overlay with playback controls
**Are you willing to submit a pull request to fix this bug?**
no

**Comment by hicom150** [comment]
Could you please add a full app screenshot so we can investigated where could it came from?

**Comment by feross** [comment]
It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.
