### ISSUE TITLE
If the app isn't opening on Linux, try this...

### ISSUE THREAD

**Issue by mrjeanp** [webtorrent/webtorrent-desktop#1766]
**What version of WebTorrent Desktop are you using?**
0.21.0

**What operating system and version?**
Parrot OS (Debian Testing [bullseye]) 64bit

**What happened?**
After installing _webtorrent-desktop_0.21.0_amd64.deb_ on my OS and then restarting. 

**The app does not open or show the GUI**... i've been using the CLI version with VLC to watch my torrents but is not very comfortable to use...

**Are you willing to submit a pull request to fix this bug?**
sure

**Comment by mrjeanp** [comment]
If the .deb isn't opening after installing, try using `dpkg -i /path/to/webtorrent.deb`

**Comment by subins2000** [comment]
This seems to be an issue with the OS than WebTorrent ? :thinking:. Perhaps the package didn't get installed correctly the first time (through GUI deb installer ?)
