### ISSUE TITLE
Minimum Windows version

### ISSUE THREAD

**Issue by Andrei746** [webtorrent/webtorrent-desktop#1767]
Please indicate the minimum required version of Windows on all of your sites where this program is available so that users do not waste time downloading, installing the program and finding out the reason for the inability to start the program. I have Windows XP and when the program starts, the message "WebTorrentSetup-v0.21.0.exe is not a Win32 application." I hardly found a similar problem here and found out that the minimum version of Windows is 7.

**Comment by DiegoRBaquero** [comment]
Windows XP 64 bit should work
