### ISSUE TITLE
Torrent file does not sow

### ISSUE THREAD

**Issue by IvanlokoBR** [webtorrent/webtorrent-desktop#1770]
guys, the .torrent file generated via web torrent desktop is not recognized by any other web torrent application or cloud is this normal? Can't sow the same common torrents in which all software share?

**Comment by hicom150** [comment]
I have no problem to open a torrent generated via `WebTorrent-Desktop ` for example in `Transmission`. This torrent files should be compatible between different torrent clients...

@IvanlokoBR Could you elaborate and add an example of your failing torrent?

**Comment by IvanlokoBR** [comment]
follow the link of a video showing what happens

https://animecine.com.br/wp-content/uploads/2020/01/2020-01-10-00-34-09.mp4

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement. No one will be able to assist you.
