### ISSUE TITLE
Drag-and-drop folder does no longer work

### ISSUE THREAD

**Issue by Borewit** [webtorrent/webtorrent-desktop#1771]
**What version of WebTorrent Desktop are you using?**
Master branch https://github.com/webtorrent/webtorrent-desktop/commit/e341367583b9efd9f2e5e6d6f7a4a9cee7cde3e8

**What operating system and version?**
Windows 10

**What happened?**
Tried to drag in a folder with audio files, nothing from happened from a user perspective.

**What did you expect to happen?**
To see my audio folder appear as a torrent entry.

**Are you willing to submit a pull request to fix this bug?**
Always

Browser process shows the following error:
```
Uncaught TypeError: Cannot read property 'readEntries' of undefined
    at readEntries (C:\Users\Borewit\code\github\drag-drop\index.js:176)
    at C:\Users\Borewit\code\github\drag-drop\index.js:179
```
Pointing to [drag-drop/index.js line 179](https://github.com/feross/drag-drop/blob/89fd6bdeb63ba19493e658b27058dca127953ef4/index.js#L179), which I think is missing the argument `reader`.

What I don't understand, why I am running in this issue now.

Blocked by: [drag-drop#52](https://github.com/feross/drag-drop/issues/52) (no worries, it's all within the familiy ;-)

**Comment by hicom150** [comment]
Fixed in [v0.23.0](https://github.com/webtorrent/webtorrent-desktop/releases/tag/v0.23.0)
