### ISSUE TITLE
0.21.0 create new torrent error

### ISSUE THREAD

**Issue by AbsordH2Odemon** [webtorrent/webtorrent-desktop#1773]
**What version of WebTorrent Desktop are you using?**
0.21.0

**What operating system and version?**
windows10 x64
**What happened?**
Create a new torrent and close the window without opening any files.
Console shows error :"TypeError: Reduce of empty array with no initial value"
GUI is blank
create new torrent Again 
Console show error: "Please go back to the torrent list before creating a new torrent"
But can't go back to the torrent list.

My English is poor, if offended, please forgive me

**Comment by hicom150** [comment]
This was a known bug which has been already fixed in https://github.com/webtorrent/webtorrent-desktop/pull/1704 so we are waiting to create a new release https://github.com/webtorrent/webtorrent-desktop/issues/1727 where all this issues are fixed 😉

Thank you for taking time to report the problem 👍
