### ISSUE TITLE
No download resume if app is closed and reopened 

### ISSUE THREAD

**Issue by arinaitwebrn** [webtorrent/webtorrent-desktop#1779]
I cant find the installation directory of the software, every time i run it ...it installs afresh, i  loose my history and partially downloaded files.
I wish it could install probably with a desktop shortcut, when i close the app and reopen it, i see my past downloads and be in a position to resume partially downloaded files that were running before i closed the app....
Otherwise, this is nice, i really like it, its a great software.

**Comment by skippdot** [comment]
What is your OS. And what are you running every time?

**Comment by arinaitwebrn** [comment]
> What is your OS. And what are you running every time?

an running windows 10 ... by the fact that i can not find the installation directory, am always running the downloaded setup.

**Comment by MomenNano** [comment]
you can find it in this path "C:\Users\[username]\AppData\Local\WebTorrent.exe", make shortcut of it on your desktop, and you won't loose your data  and history anymore.

**Comment by feross** [comment]
I believe this issue was fixed by https://github.com/webtorrent/webtorrent-desktop/pull/1754 and is in the latest release of WebTorrent Desktop.
