### ISSUE TITLE
WebTorrent Desktop App Mac Issue

### ISSUE THREAD

**Issue by techTazim3** [webtorrent/webtorrent-desktop#1783]
WebTorrent Version 0.21.0 (0.107.16)

macOS High Sierra Version 10.13.6

The app has intermittent download for me. One moment it says 2hrs 35 s remaining and then all of a sudden the statement disappears and returns after 2-3 minutes. How can this be fixed?

**Comment by brbergami** [comment]
Dude, do you even know how P2P downloads works? You depend on another peers connection. You are not downloading directly from a server with constant speed. Obviously, more people have the file, faster downloads comes to you. When peers disconnect seeding you, you will notice the time to complete will increase. Hope that helps you to understand how does this works. Cheers
