### ISSUE TITLE
Changing the default player does not work

### ISSUE THREAD

**Issue by tiotrom** [webtorrent/webtorrent-desktop#1790]
**What version of WebTorrent Desktop are you using?**
Version 0.21.0 (0.107.16) (64-bit)

**What operating system and version?**
TROMjaro (Manjaro based - Stable version).

**What happened?**
Cannot change the default player. Nothing happens after I select it.

**What did you expect to happen?**
Select another player and that to change it. It does not.

**Comment by EchedeyLR** [comment]
I confirm the issue in Debian 10 GNOME.

**Comment by EchedeyLR** [comment]
This issue seems to be a duplicated of https://github.com/webtorrent/webtorrent-desktop/issues/1722

**Comment by hicom150** [comment]
Should be already fixed in [v0.23.0](https://github.com/webtorrent/webtorrent-desktop/releases/tag/v0.23.0)
