### ISSUE TITLE
Application doesn't install, nor integrate completely within the system

### ISSUE THREAD

**Issue by lgarcia99** [webtorrent/webtorrent-desktop#1794]
**WebTorrent Version**:  v0.21.0
**Operating system**: Windows 10
**What happened?**
There's an issue about the installation process itself. The installation process finishes the program installation and then shows the graphic interface, but it doesn't have a desktop nor menu icon. It still appears in the list of installed programs in the Control Panel options, though. So, when I wanted to use the program, I actually had to open the installer and wait, till the program shows up. I don't know if its issue only for this version and maybe previous versions work but I haven't tried that.

**Comment by feross** [comment]
I believe this has been fixed by https://github.com/webtorrent/webtorrent-desktop/pull/1754 and is in the latest release of WebTorrent Desktop.
