### ISSUE TITLE
why it uses too much memory?

### ISSUE THREAD

**Issue by sandriaas** [webtorrent/webtorrent-desktop#1796]
**What version of WebTorrent Desktop are you using?**
v0.21.0
**What operating system and version?**
Windows 10 v2004
**What happened?**
it uses too much ram, 4GB? that's crazy. only 1 file downloading, 2.3GB
![Taskmgr_lBPvMJjVUX](https://user-images.githubusercontent.com/21377475/77251079-cbda9380-6c7e-11ea-805c-89c641eca0a9.png)

**Comment by Iseg** [comment]
hi, in ubuntu 18.04 the same thing, although it eats less than about 2 GB, I’ll add a screen later!

**Comment by dsernst** [comment]
Is this causing noticeable problems?

**Comment by Slender1808** [comment]
I'm also having this problem, I was downloading a 3gb ISO memory usage went to 8gb

**Comment by feross** [comment]
This isn't ideal. Does the memory utilization return to zero when you remove all torrents from the app?

If yes, then it means that WebTorrent is storing file data in memory instead of in the temp folder on the filesystem, which is a bug. If no, then perhaps a memory leak was introduced?

**Comment by Slender1808** [comment]
With me it happened during download the memory problem, when I finish the download it returned to normal

**Comment by NessDan** [comment]
Just wanted to bump this thread, I'm download only a Ubuntu ISO and my RAM is being demolished - it's currently using _**16GB of RAM**_ while it download a file that's _**2.9GB**_

![2021-03-25 15_51_07-Task Manager](https://user-images.githubusercontent.com/304269/112534960-199e4600-8d82-11eb-846f-ef0e8e36e312.png)

**Comment by ThaUnknown** [comment]
> Just wanted to bump this thread, I'm downloading only a Ubuntu ISO and my RAM is being demolished - it's currently using _**16GB of RAM**_ while it download a file that's _**2.9GB**_
> 
> ![2021-03-25 15_51_07-Task Manager](https://user-images.githubusercontent.com/304269/112534960-199e4600-8d82-11eb-846f-ef0e8e36e312.png)

this is because the store isn't keeping up with your download speeds, you're downloading at 5200 Mbit/s which are speeds that no SSDs can currently achieve without RAID, from what I know store backpressure is in the works, just as speed cap, which help with these, also there's currently an issue where partial pieces are kept in RAM https://github.com/webtorrent/webtorrent/issues/1973

if you need this fixed NOW, I recommend you re-compile webtorrent-desktop with https://github.com/webtorrent/webtorrent/pull/2000

**Comment by NessDan** [comment]
> this is because the store isn't keeping up with your download speeds, you're downloading at 5200 Mbit/s which are speeds that no SSDs can currently achieve without RAID, from what I know store backpressure is in the works, just as speed cap, which help with these, also there's currently an issue where partial pieces are kept in RAM [webtorrent/webtorrent#1973](https://github.com/webtorrent/webtorrent/issues/1973)
> 
> if you need this fixed NOW, I recommend you re-compile webtorrent-desktop with [webtorrent/webtorrent#2000](https://github.com/webtorrent/webtorrent/pull/2000)

Appreciate the response! I think there's an issue here then, my internet speed is definitely not that fast (WebTorrent said "643MB/s" almost the entire time, despite me actually only getting ~1.4Mbps (see the Task Manager)

I wish I got those kind of speeds 😂 But my peak speed was about ~300mbps (37MB/s)

So it seems maybe WebTorrent _thinks_ it's receiving way more data than it is, thus pushing it into RAM?
