### ISSUE TITLE
Doesn't recognize .m2ts

### ISSUE THREAD

**Issue by aurimus** [webtorrent/webtorrent-desktop#1799]
.. and so there is no way to stream the file.

https://en.wikipedia.org/wiki/.m2ts

**Comment by hicom150** [comment]
I've added https://github.com/webtorrent/webtorrent-desktop/pull/1859 to add support for `.m2ts` file extensions, but take into account that it will be only possible to play throw an external player like VLC.

**Comment by feross** [comment]
Fixed in #1859
