### ISSUE TITLE
Path missing for some filenames

### ISSUE THREAD

**Issue by augnustin** [webtorrent/webtorrent-desktop#1800]
**What version of WebTorrent Desktop are you using?**

Linux Version 0.21.0 (0.107.16) (64-bit)

**What operating system and version?**

Linux-4.15.0-91-generic-x86_64-with-LinuxMint-19.1-tessa

**What happened?**

With some filenames, when I add the torrent to webtorrent, it displays "downloading" but nothing happens. When I uncheck and recheck it, I get:

> Path missing.
> Fix and restart the app, or delete the torrent.
> Missing path: /home/augustin/Downloads/Le.Bureau.des.Legendes.S05E02.TRUEFRENCH.1080p.x265-CHK.mkv

**What did you expect to happen?**

Download should start. Instead I need to remove the torrent, rename it and readd it and it works. My feeling is that it happens with french torrents, so it might be filename encoding issues ...

**Are you willing to submit a pull request to fix this bug?**

Eventually.

**Comment by hicom150** [comment]
Hey @augnustin can you provide an example torrent file where this error happens?

**Comment by augnustin** [comment]
Hey,

I will, as soon as I reproduce the issue. Don't have an example with me right now.

Cheers

**Comment by Rob5555** [comment]
I am having the same problem but only with specific files, all other do not loose the path.

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement. No one will be able to assist you.
