### ISSUE TITLE
Error installing on Win 8

### ISSUE THREAD

**Issue by harrmitch** [webtorrent/webtorrent-desktop#1802]
**What version of WebTorrent Desktop are you using?**
0.21
**What operating system and version?**
Windows 8
**What happened?**
The installing wizard appeared and then returned with a pop up that said "There was an error while installing the application. Check the setup log for more information and contact the author". The log is attached below.
[SquirrelSetup.log](https://github.com/webtorrent/webtorrent-desktop/files/4464037/SquirrelSetup.log)
**What did you expect to happen?**
The program is installed successfully
**Are you willing to submit a pull request to fix this bug?**
I don't really know much about coding so I don't think I could help

**Comment by dsernst** [comment]
Any updates here? Were you ever able to successfully install on Win 8?

**Comment by feross** [comment]
I expect that this issue is resolved with the latest version of Electron and Squirrel, and also Windows 8 and 8.1 reached the end of Mainstream Support on January 9, 2018.
