### ISSUE TITLE
Expose DLNA server for devices like PS4

### ISSUE THREAD

**Issue by mathrick** [webtorrent/webtorrent-desktop#1808]
**What version of WebTorrent Desktop are you using?**
0.21.0 (0.107.16)

**What operating system and version?**
Linux Mint 18.3 / Ubuntu Xenial

**What problem do you want to solve?**
Currently, it seems the cast button only appears if WTD detects an active client listening for control commands. That makes it impossible to use with the PS4 media player, which supports DLNA, but is looking for *servers*, rather than advertising a control point.

**What do you think is the correct solution to this problem?**
It should be possible to put WTD in DLNA server mode (or even better, it should just advertise itself as a server whenever running), so that DLNA clients can find it. For bonus points, it could even expose inactive torrents and start download when playback is requested.

**Are you willing to submit a pull request to implement this change?**
I'm not familiar with WTD codebase or the stack, but with enough guidance it could be doable.

**Comment by dsernst** [comment]
I don’t have a ps4 so can’t test, but this sounds cool. What sort of help would you need to get started?

**Comment by mathrick** [comment]
General help pointing me to where in the code it would make sense to start adding this, as well as enough pointers for whatever parts of the stack for me to figure out how to create a DLNA server. I have experience programming, but no experience at all with anything related to WTD. I'm OK at Javascript, but have never used Node.js for development.

**Comment by feross** [comment]
You can take a look at how the existing Chromecast, Airplay, and DLNA support is implemented as an example. Looking at that code should be quite helpful.

**Comment by mathrick** [comment]
Would you mind pointing me to where that lives?

**Comment by feross** [comment]
@mathrick https://github.com/webtorrent/webtorrent-desktop/blob/f23e52c699ae2b9660246e911af81fa2b88b98a6/src/renderer/lib/cast.js
