### ISSUE TITLE
Can i edit the folder where it will download into?

### ISSUE THREAD

**Issue by M1178475702** [webtorrent/webtorrent-desktop#1809]
**What version of WebTorrent Desktop are you using?**

**What operating system and version?**

**What problem do you want to solve?**

**What do you think is the correct solution to this problem?**

**Are you willing to submit a pull request to implement this change?**

**Comment by alxhotel** [comment]
Yes.

Go to Edit > Preferences > Click on "Change" in the "Download folder" section.
