### ISSUE TITLE
Error while building and packaging the codebase for linux [deb]

### ISSUE THREAD

**Issue by thevirajshelke** [webtorrent/webtorrent-desktop#1810]
**What version of WebTorrent Desktop are you using?**
I did a git pull of the repo with the latest commit [cf0cf79](https://github.com/webtorrent/webtorrent-desktop/commit/cf0cf794400049502ea8f4b203b6ad4e55019ea5)
**What operating system and version?**
OS - Linux
Flavor - Ubuntu 18.04.4 
**What happened?**
I did an `npm install` & then tried creating a Debian file for installation with the command `npm run package linux --package=deb`. While the building processes I encountered the following messages and the building processes continued to create a Debian Package.
 
```bash
> node-gyp rebuild

make: Entering directory '/home/thevirajshelke/webtorrent-desktop/node_modules/fs-xattr/build'
  CC(target) Release/obj.target/xattr/src/async.o
  CC(target) Release/obj.target/xattr/src/error.o
  CC(target) Release/obj.target/xattr/src/sync.o
  CC(target) Release/obj.target/xattr/src/util.o
  CC(target) Release/obj.target/xattr/src/xattr.o
  SOLINK_MODULE(target) Release/obj.target/xattr.node
  COPY Release/xattr.node
make: Leaving directory '/home/thevirajshelke/webtorrent-desktop/node_modules/fs-xattr/build'

> macos-alias@0.2.11 install /home/thevirajshelke/webtorrent-desktop/node_modules/macos-alias
> node-gyp rebuild

make: Entering directory '/home/thevirajshelke/webtorrent-desktop/node_modules/macos-alias/build'
  CXX(target) Release/obj.target/volume/src/volume.o
../src/volume.cc:9:2: error: #error This platform is not implemented yet
 #error This platform is not implemented yet
  ^~~~~
../src/volume.cc: In function ‘void Initialize(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/volume.cc:16:49: error: ‘MethodGetVolumeName’ was not declared in this scope
     Nan::GetFunction(Nan::New<FunctionTemplate>(MethodGetVolumeName)).ToLocalChecked());
                                                 ^~~~~~~~~~~~~~~~~~~
volume.target.mk:111: recipe for target 'Release/obj.target/volume/src/volume.o' failed
make: *** [Release/obj.target/volume/src/volume.o] Error 1
make: Leaving directory '/home/thevirajshelke/webtorrent-desktop/node_modules/macos-alias/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/thevirajshelke/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-51-generic
gyp ERR! command "/home/thevirajshelke/.nvm/versions/node/v12.16.1/bin/node" "/home/thevirajshelke/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/thevirajshelke/webtorrent-desktop/node_modules/macos-alias
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 

> electron-chromedriver@7.0.0 install /home/thevirajshelke/webtorrent-desktop/node_modules/electron-chromedriver
> node ./download-chromedriver.js


> nodemon@2.0.0 postinstall /home/thevirajshelke/webtorrent-desktop/node_modules/nodemon
> node bin/postinstall || exit 0
```
Please note that this is not the full output of the build process but the part where it failed & I think is sufficient for analysis.
**What did you expect to happen?**
A smooth building process was supposed to happen without any errors.
**Are you willing to submit a pull request to fix this bug?**
No. Not as of now at least.

**Comment by hicom150** [comment]
This `macos-alias` error is "expected" to appear if you do a `npm install` in any system that is not macOS (like Linux), but this should not stop you from building a valid `deb` package.

**Comment by thevirajshelke** [comment]
The error didn't come when I did `npm install` it came when I executed `npm run package linux --package=deb`.

>  This macos-alias error is "expected" to appear if you do a npm install in any system that is not macOS (like Linux)

Can we not avoid this error? I mean logically speaking if the system is not macOS anything related to this should never execute. Nevertheless, my `deb` was not created at all! because the building process just failed!

I'lll take a git pull and try again! Will update it here! Thanks :)

**Comment by thevirajshelke** [comment]
@hicom150 My bad! After going through console logs again I saw that `npm run package linux --package=deb` internally installs node_modules and this error comes, but I could see that the build succeeded and `deb` was created successfully :) (Tried with the most recent commit [57d02aa](https://github.com/webtorrent/webtorrent-desktop/commit/57d02aa316eb41dca899788eeb2a75beeb0c5a7c))

I am not sure if we can avoid this error getting displayed! (Maybe it's not even needed & could be last thing that the developers will waste time upon)

Anyway closing the issue :+1:
