### ISSUE TITLE
Show stream download progress when playing via external player

### ISSUE THREAD

**Issue by subins2000** [webtorrent/webtorrent-desktop#1814]
**What version of WebTorrent Desktop are you using?**
0.21.0

**What operating system and version?**
Ubuntu 18.04 LTS

**What problem do you want to solve?**
When playing via external player, there's no way to know what's the current download progress. If you go back to the main window, the external streaming also stops.

**What do you think is the correct solution to this problem?**
Keep displaying the playback red line progress in the WebTorrent player even in the "Playing external" window.
![image](https://user-images.githubusercontent.com/2305675/81493071-dac2e700-92ba-11ea-9309-fb8aac9aff5c.png)

**Are you willing to submit a pull request to implement this change?**
Yes

**Comment by hicom150** [comment]
Could this be the same feature that it is implemented in #1217 ?
In that case let's get the PR reviewed and merged! 😉

**Comment by subins2000** [comment]
Yes that's it. I didn't know there was a PR & issue for this. Thanks @hicom150.

but it'd be also cool to show the bottom playback red line for progress

**Comment by subins2000** [comment]
The associated PR has been merged #1217. The one thing left to do is that WebTorrent needs a new release. Last release was in 2020 👀 .
