### ISSUE TITLE
devtool still remain open main window close

### ISSUE THREAD

**Issue by surajrathod** [webtorrent/webtorrent-desktop#1819]
**What version of WebTorrent Desktop are you using?**
v0.21.0
**What operating system and version?**
Windows 10
**What happened?**
devtool still remain open when the main windows are closed

**What did you expect to happen?**
close the devtool when the main window is closed

**Are you willing to submit a pull request to fix this bug?**
If you allow me I can do that

**Comment by dsernst** [comment]
This seems obscure, not sure how important it is 😄

How many users open DevTools, and if they do, is it so hard to close them after?

Is there a simple fix for this, like editing some electron config flag? In any case, this seems like an upstream electron issue.

I’m going to close to try to keep this Issue tracker relatively organized, feel free to comment if you have more thoughts though🙂
