### ISSUE TITLE
Download Freezes

### ISSUE THREAD

**Issue by droidtoss** [webtorrent/webtorrent-desktop#1821]
Have latest WebTorrent version and actually can't check what version it is in WebTorrent screen. (addition bug)
![opera_psmFHiM3o7](https://user-images.githubusercontent.com/51296326/84277302-fe887f80-ab3b-11ea-9168-c806d832da51.png)

My PC is g4600 and 1050ti, 16gb ram, SSD 120gb 
Windows 10 LTSC 1809

Hello have an issue, when im starting download torrent file, it freezing in 20-40% and not continue load
Actually it happens with me all the time when im using WebTorrent
https://youtu.be/FL6G4qF5jxc

**Comment by Kam1ni** [comment]
I  have this issue as well. I've noticed that if I watch a video that I'm downloading, it resumes the download.

**Comment by alxhotel** [comment]
If you can't see the version of the app (because the window is too short), most probably you have an old version.

Please download the latest version of Webtorrent Desktop and check if it's fixed.

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement. No one will be able to assist you.
