### ISSUE TITLE
Customize trackers for existing torrent

### ISSUE THREAD

**Issue by evolutionjay** [webtorrent/webtorrent-desktop#1822]
**What version of WebTorrent Desktop are you using?**
0.21.0
**What operating system and version?**
macOS 10.15.5 
**What problem do you want to solve?**
Need to customize tracker features
**What do you think is the correct solution to this problem?**
add customize tracker features options
**Are you willing to submit a pull request to implement this change?**
I'm sorry, I don't have this skill

**Comment by raspher** [comment]
Hi, i think description of this feature should be more specific. Do you want to have option to add/remove trackers in right-click  menu on torrent?

If yes, it's the feature i want too, if not i need to create an issue.

**Comment by pokapow** [comment]
I don't know what evolutionjay means, but I agree with raspher, for me the most important missing functionality is that of being able to add / remove a tracker from a torrent being downloaded, as is the case in the "tracker" tab of Transmission for example.

**Comment by feross** [comment]
Duplicate of #881
