### ISSUE TITLE
the program stop downloading

### ISSUE THREAD

**Issue by bassem567** [webtorrent/webtorrent-desktop#1823]
**What version of WebTorrent Desktop are you using?**
v0.21.0
**What operating system and version?**
windows 8.1
**What happened?**
it was working , but it stop downloading while it is connected to 10 - 14 peers
**What did you expect to happen?**
continue downloading my torrent file
**Are you willing to submit a pull request to fix this bug?**

**Comment by feross** [comment]
This is likely an issue in the core webtorrent library. Thank you for reporting. Follow here: https://github.com/webtorrent/webtorrent/issues/1880
