### ISSUE TITLE
Support moving download directory

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [webtorrent/webtorrent-desktop#1827]
**What version of WebTorrent Desktop are you using?**
Version 0.21.0 (0.107.16)
**What operating system and version?**
macOS Catalina
**What problem do you want to solve?**
When I need to organize downloads, if I forget to change the DL Dir before downloading, I have to leave it or break the link to categorize it
**What do you think is the correct solution to this problem?**
Support moving files
**Are you willing to submit a pull request to implement this change?**
Sorry, I'm not familiar enough with the language to do so

**Comment by dsernst** [comment]
How would you like this to work?

**Comment by ThinkDigitalSoftware** [comment]
Right click and hit move download directory. An open window opens up and you select the new directory and then it calls the move command in the background and updates the database accordingly.
