### ISSUE TITLE
Consider using Tauri instead of Electron

### ISSUE THREAD

**Issue by erlend-sh** [webtorrent/webtorrent-desktop#1829]
Using [Tauri](https://github.com/tauri-apps/tauri) would make webtorrent-desktop efficient enough to be on par with most native desktop clients.

They have a vibrant community of contributors, so there’s a pretty good chance someone from there could lend a big hand (maybe even take the lead) on this if an invitation to collaboration is extended 🙂

**Comment by feross** [comment]
Looks like a neat project! However, we need a full browser instance for WebRTC support. It's not clear to me that Tauri offers that. Plus, this would be a HUUGE amount of work. Closing, but feel free to continue discussing.
