### ISSUE TITLE
Downloads Don't Resume

### ISSUE THREAD

**Issue by HeshamMeneisi** [webtorrent/webtorrent-desktop#1843]
**What version of WebTorrent Desktop are you using?**
v0.23.0

**What operating system and version?**
Ubuntu 18.04

**What happened?**
Downloads stopped by a lack of peers don't automatically start when new peers are available. The download only resumes when the play button is clicked.

**What did you expect to happen?**
There would be a timer that checks if new peers are available and automatically resumes without user interaction.

**Are you willing to submit a pull request to fix this bug?**
Sure, I can check the issue when I have some time. I took a quick look at the playback code and I have a strong guess that "prioritizeTorrent" is what brings the torrent back alive.

**Comment by subins2000** [comment]
There is an announce timeout for trackers. I think it takes that 'timeout' seconds for next request to tracker for peers. Perhaps this is the cause of delay ?

**Comment by HeshamMeneisi** [comment]
It actually stayed paused for hours (stuck at 95%) then as soon as I pressed the play button, it started downloading again.
