### ISSUE TITLE
2160p 4K HDR Playback support

### ISSUE THREAD

**Issue by Sosoyan** [webtorrent/webtorrent-desktop#1848]
Currently it's unable to play 4K HDR content.

<img width="735" alt="Screen Shot 2020-07-22 at 12 36 44 PM" src="https://user-images.githubusercontent.com/5727306/88154583-19a8dd80-cc18-11ea-9315-f9dd2ce89d4c.png">

**Comment by hicom150** [comment]
The embedded web video player only supports a limited number of codec and this limitation is due to `Electron`, the base software we use to build `webtorrent-desktop`. There is nothing we can do here 😅

But you always have the option to `Play in VLC` 😉
