### ISSUE TITLE
No tray icon in non-Debian based distributions

### ISSUE THREAD

**Issue by BlueManCZ** [webtorrent/webtorrent-desktop#1851]
https://github.com/webtorrent/webtorrent-desktop/blob/3a92f596ffab65a13386eb3cddf8e1e362b7aca9/src/main/tray.js#L57

This check should be rewritten to avoid using `dpkg` but instead look into `/usr/lib` or `/usr/lib64` for `libappindicator*` files.

I use Gentoo which doesn't use `dpkg`. I have [libappindicator](https://packages.gentoo.org/packages/dev-libs/libappindicator) package installed.

```
ls -al /usr/lib64/libappindicator*   
lrwxrwxrwx 1 root root    25  Oct  1  2019 /usr/lib/libappindicator3.so -> libappindicator3.so.1.0.0
lrwxrwxrwx 1 root root    25  Oct  1  2019 /usr/lib/libappindicator3.so.1 -> libappindicator3.so.1.0.0
-rwxr-xr-x 1 root root 56104  Oct  1  2019 /usr/lib/libappindicator3.so.1.0.0
```

Related: https://github.com/webtorrent/webtorrent-desktop/issues/383, https://github.com/webtorrent/webtorrent-desktop/issues/1215, https://github.com/webtorrent/webtorrent-desktop/pull/1216, https://github.com/webtorrent/webtorrent-desktop/issues/1399.

**Comment by feross** [comment]
@BlueManCZ Do you have any interest in sending a PR for this issue? We'd be interested to merge it -- sounds like it might be just a few line change?
