### ISSUE TITLE
"select only" for magnet links doesn't work

### ISSUE THREAD

**Issue by pvlrmnnk** [webtorrent/webtorrent-desktop#1852]
**What version of WebTorrent Desktop are you using?**
0.23.0 (0.108.6)

**What operating system and version?**
macOS Catalina 10.15.6

**What happened?**
Tried to add `&so=0` arg to magnet link to download only first file, but webtorrent app downloaded all files 

**What did you expect to happen?**
Download only first one

**Are you willing to submit a pull request to fix this bug?**
Not familiar with js

**Comment by feross** [comment]
The pre-reqs for this issue are now in place since we support BEP53 properly in `webtorrent` now.

@hicom150 Is there anything else we need to do to support this in WebTorrent Desktop or can this issue be closed now?

**Comment by hicom150** [comment]
Yeah, I think we can close this issue 👍
It will be available for everyone as soon as we release the new version 😉
