### ISSUE TITLE
Enable uTP protocol 

### ISSUE THREAD

**Issue by karloluis** [webtorrent/webtorrent-desktop#1854]
**What version of WebTorrent Desktop are you using?**
v0.23.0

**What operating system and version?**
Mac OS

**What happened?**
A magnet link did not load as many peers/seeds as it did using another client.

A large torrent was taking long to DL and after a while I tried the same with uTor to see if there was any difference. To my surprise uTor did eventually find more peers/seeds than WebTor did. Even having the two run concurrently didn't seem to phase WebTor client.

Force Quit and pause/resume the torrent to no avail.

**What did you expect to happen?**
Discovering peers/seeds effectively.

**Are you willing to submit a pull request to fix this bug?**
Not at this time.

**Comment by dsernst** [comment]
Is this easy to reproduce?

**Comment by karloluis** [comment]
I've tried with some 2019 torrent files and happens fairly consistent with low peer/seed connections.

**Comment by dsernst** [comment]
Confirming that I am seeing this as well.

Had a download taking unusually long in Webtorrent Desktop... first time I recall running into this issue. For some reason the download effectively stopped, after it had successfully downloaded 4gb (7%). Even though it said 38 peers were still available.

### Webtorrent Desktop:

![webtorrent](https://user-images.githubusercontent.com/6340841/94335386-34892c80-ff90-11ea-8e68-c098c6ff7011.PNG)

------

I tried loading up the same magnet link in uTorrent and it pretty quickly was able to get download speeds up to 10MB/s again.

### uTorrent:

![utorrent](https://user-images.githubusercontent.com/6340841/94335389-394de080-ff90-11ea-96de-93a34631cc11.PNG)


Same torrent, same internet connection. This is on a fresh install of Windows 10 w/ Webtorrent Desktop 0.24.0

**Comment by dsernst** [comment]
@hicom150's PR https://github.com/webtorrent/webtorrent/pull/1923 may address this! 🤞

**Comment by feross** [comment]
@dsernst Yeah, perhaps some other popular client has been updated to prefer uTP? Without digging into the details of what's happening at the lower layers, it's hard to say. 

I'll repurpose this issue for enabling uTP in WebTorrent Desktop, since it needs an explicit `utp: true` flag to be set in order to work.

Does someone want to add this flag, test it out, and then send a PR?

**Comment by hicom150** [comment]
I've created #1900 to enable uTP 👍
