### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by femboylmao** [webtorrent/webtorrent-desktop#1857]
**What version of WebTorrent Desktop are you using?**
I am not using webtorrent, as there is no ARM support
**What operating system and version?**
I am using the raspberry pi 3 on raspian.
**What problem do you want to solve?**
I believe the application needs more support 
**What do you think is the correct solution to this problem?**
Adding ARM support
**Are you willing to submit a pull request to implement this change?**
I cannot code, apologies

**Comment by feross** [comment]
Don't we already support ARM on Debian-based Linux flavors? We added support in this PR: https://github.com/webtorrent/webtorrent-desktop/pull/1650

You can find the ARM .deb files here: https://github.com/webtorrent/webtorrent-desktop/releases

**Comment by hicom150** [comment]
Made #1901 to enable `armv7l` arch 🤓

Given that electron-packager can build for `armv7l` it is just as easy as enabling it to support devices like `Raspberry Pi 3`
and `Raspberry Pi 4` when running in a 32bit mode.

It would be nice if @femboylmao you could help testing this builds 😉
