### ISSUE TITLE
Multiple Layout Options & Custom folder selection for downloads

### ISSUE THREAD

**Issue by aqsax** [webtorrent/webtorrent-desktop#1860]
**What version of WebTorrent Desktop are you using?**
Version 0.23.0 (0.108.6) (x64)

**What operating system and version?**
Windows 10 Pro (x64) - Build 19041

**What problem do you want to solve?**
The current "tiled picture" layout for torrents is pretty to look at, but I think having multiple layout options would be better.
In addition to this, could there be an option where I get to select which folder each of my torrents get downloaded to instead of one specific folder for all torrents?  

**What do you think is the correct solution to this problem?**
For layout options, I would want something more clean like just a list of torrents with names and the progress bar and all those important info. A bit like how uTorrent has a list layout of torrents you're downloading. Maybe you can add a thumbnail layout as well, but I would prefer a cleaner, list layout over a thumbnail/current picture layout.

For the custom folder selection, I guess not everyone wants to be bothered with an extra step to click yes about where to store their torrent so maybe there can be an on/off option for this feature. If someone like me wants to be asked where to store each torrent every time, they can toggle it on, and someone else who doesn't want to be bothered with this can have it switched off.

**Comment by dsernst** [comment]
Friendly suggestion that this seems like 2 distinct issues: easier to discuss & track if they are separate 🙂 

Re alternate layout: I’m having difficulty visualizing your description. I think of the current design as a list already, not tiled. 

Could you make a simple visual mockup of what you have in mind? 

If you don’t already have a design tool handy, you may like https://excalidraw.com — it’s free and simple.

**Comment by aqsax** [comment]
Hi, I'm sorry about this. I thought if I write it in one place it'll be easier for you as you wouldn't have to deal with two tickets.

I'll attach 2 concept designs I found on Dribbble, I was gonna design myself but I found them online and they are exactly what I was trying to describe. Just want to add that since I didn't design them, they are someone else's copyrighted work so please do not copy it exactly, as it might lead to problems for you...

![UI_Torrent_List](https://user-images.githubusercontent.com/68828083/95677882-2cf99280-0be2-11eb-853c-13c7da1980e5.jpg)

![UI_Torrent_List_2](https://user-images.githubusercontent.com/68828083/95677880-2a973880-0be2-11eb-8ed3-bb988ab7590d.jpg)

This^ is the kind of layout I'm talking about, without the picture that the current list layout has.

Also, I just wanted an option to select which folder the torrent will be downloaded to - whenever I start a new torrent.

**Comment by aqsax** [comment]
Should I really open a new ticket/issue for the custom folder selection option?

**Comment by aqsax** [comment]
I've replied to this on GitHub along with some visual mockups.

**Comment by feross** [comment]
> This is the kind of layout I'm talking about, without the picture that the current list layout has.

I think we can definitely improve the UX of the current design and make it cleaner, but I don't think that complexifying the UI to the degree that the linked mockup does is what we want to do. I'm not convinced we need a left column with categories. The single column view is what makes WebTorrent feel a lot simpler and approachable than other torrent apps.

Having an button to toggle a more compact UI without the image background seems like a good option for those with a lot of torrents.
