### ISSUE TITLE
Can't setup...

### ISSUE THREAD

**Issue by aurelianopertile** [webtorrent/webtorrent-desktop#1866]
When I try to install I get this:
"Installation has failed. There was an erro w hile installing the application. Check the setup log for more information and  contact the author."
Attached goes the log. Thanks.

[Setup error.txt](https://github.com/webtorrent/webtorrent/files/5147249/Setup.error.txt)

**Comment by dsernst** [comment]
Thanks for including the log, that’s helpful.

Looks like you are running Windows. Do you know what version is it?

**Comment by dsernst** [comment]
Does your user account have permission to install new software?

**Comment by feross** [comment]
It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.
