### ISSUE TITLE
Thank you very much for the program!

### ISSUE THREAD

**Issue by mrkaban** [webtorrent/webtorrent-desktop#1867]
Thank you very much for the program distributed under a free open license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82/%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B8/webtorrent-desktop-%D1%82%D0%BE%D1%80%D1%80%D0%B5%D0%BD%D1%82-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82.html).

Please do not drop the project, this is a very interesting program!

**Comment by dsernst** [comment]
Awesome, thanks for sharing! 🎉

**Comment by feross** [comment]
Thanks!
