### ISSUE TITLE
Spyware on Webtorrent

### ISSUE THREAD

**Issue by MrDataCoder** [webtorrent/webtorrent-desktop#1869]
Hi all,
When I do open webtorrent it get do some spying kinds of stuff, like your search engines (Google.com) redirects to cse.google.com , because webtorrent can track some Infos like traffics, cookies, sessions, etc and it can hijack them. Please don't use this app, if you do be careful with your information in the browser, in security intelligence it calls Browser Hijacking attack.
Thank You

**Comment by Borewit** [comment]
Mr Jamal.D, specialist in penetration testing, what an honer to have you around. I suppose you did some research before accusing us. Can you show me where this spyware you claimed to have found is hidden, some other evidence?

**Comment by MrDataCoder** [comment]
I should take a video capturing  for this because you will deny it again if i send Pictures

**Comment by feross** [comment]
Hi @MrDataCoder, WebTorrent Desktop doesn't bundle malware. If you notice this happening again, please share the following:

- Which OS and version are you using?
- Which version of WebTorrent Desktop are you using?
- Which website did you download WebTorrent Desktop from? Please share the URL to the download page.
- Do you still have the installer file that you used to install the app?
- Can you share the SHA1 hash of the installer? Go to [this site](http://onlinemd5.com/), drag the installer file into it, select SHA1 and then share what the result is.

Thanks, this will help us determine what might have happened here.

**Comment by MrDataCoder** [comment]
OS: Windows 10 Pro Latest Update
I removed it now but i'v been downloaded it from here : https://webtorrent.io/desktop-download/windows
Intsaller file name: WebTorrentSetup-v0.23.0.exe
Hash: 4F3CF7CC29536820681B095A41960208C8C624AD

**Comment by MrDataCoder** [comment]
and I should mention to this too:
https://www.sophos.com/en-us/threat-center/threat-analyses/controlled-applications/WebTorrent.aspx

**Comment by graingert** [comment]
I'd recommend you read that link yourself fully before posting it:

> Controlled applications are programs, such as VoIP, IM, P2P and games, that can be blocked or allowed for different groups of computers, depending on productivity or security concerns.
>
> Block? Allow? Restrict their use? It's your choice. You can control the use of these applications to best meet your organization's business and regulatory needs.

> I should take a video capturing for this because you will deny it again if I send Pictures. and I will soon do this

Please do make that video, or even send the pictures, I'm interested to see what you mean

**Comment by graingert** [comment]
> I should take a video capturing for this because you will deny it again if I send Pictures. and I will soon do this

Please do make that video, or even send the pictures, I'm interested to see what you mean

**Comment by feross** [comment]
Since you're using the official download link and the hash you posted (4f3cf7cc29536820681b095a41960208c8c624ad) is the correct hash, I'm inclined to suspect this is a false positive from your antivirus, or you unfortunately happened to install some malware at the same time as you installed WebTorrent.

Furthermore, the Sophos link you published doesn't indicate anything interesting. It's just saying that WebTorrent is an app they have in their app database.

WebTorrent doesn't ship any additional bundled software with the application. If you (or anyone else) has information about antivirus reports or anything similar in the future, please do open a new issue and we'll investigate.

**Comment by MrDataCoder** [comment]
> 
> 
> Since you're using the official download link and the hash you posted (4f3cf7cc29536820681b095a41960208c8c624ad) is the correct hash, I'm inclined to suspect this is a false positive from your antivirus, or you unfortunately happened to install some malware at the same time as you installed WebTorrent.
> 
> Furthermore, the Sophos link you published doesn't indicate anything interesting. It's just saying that WebTorrent is an app they have in their app database. It's not tagged as malware or anything nefarious.
> 
> WebTorrent doesn't ship any additional bundled software with the application. If you (or anyone else) has information about antivirus reports or anything similar in the future, please do open a new issue and we'll investigate.

What are you talking about? i am saying when i close WebTorrent and removed it from my pc everything backed to normal

**Comment by graingert** [comment]
@MrDataCoder can you make and post the video and send the screenshots?

**Comment by Borewit** [comment]
> What are you talking about? i am saying when i close WebTorrent and removed it from my pc everything backed to normal.
It shows problem was from your app.

- You claimed there is some kind of spy-ware in WebTorrent-Desktop.
- You promised to provide proof soon.
- You claim to be senior penetration tester.
- You predicted we would deny your evidence.

So far you showed not any of these statements is true.

What you did provide is a report written by Sophos stating:
* WebTorrent is a file sharing application
* The uninstaller is confirmed to remove the application.
* No negative comments saying

But we did offer our help if you would come up with something tangible. That is what we are talking about.
