### ISSUE TITLE
Cannot find path for playback software - Flatpak

### ISSUE THREAD

**Issue by barcazama** [webtorrent/webtorrent-desktop#1874]
**What version of WebTorrent Desktop are you using?**
Version 0.23.0 (0.108.6) (x64), installed via Flatpak
**What operating system and version?**
Pop!_OS 20.04 LTS x86_64
**What happened?**
WebTorrent cannot open VLC. A window open with a VLC logo on black background, the video doesn't play.
**What did you expect to happen?**
A new video with VLC open, the video start.
**Are you willing to submit a pull request to fix this bug?**
No, I don't have sufficient knowledge. Just want to signal it.
**Notes**
I don't have much knowledge regarding those issue but I have tried to resolve the issue by manually adding vlc path in the parameter (I can find the app using the File manager. I tried to install VLC in .deb and flatpak, it doesn't resolve the issue). The app is not visible when I'm in the right folder (/usr/bin/vlc). And I think it's related to fact it was installed via Flatpak. I'm ready to do further testing, I just need someone to point me in the right direction.

**Comment by subins2000** [comment]
Hi @barcazama, I don't think WebTorrent Desktop is officially supported via Flatpak. Flathub allows anyone to package software and WebTorrent got packaged by someone. It's better to file this issue over there : https://github.com/flathub/io.webtorrent.WebTorrent

**Comment by subins2000** [comment]
On a second look, found that the issue is already filed there : https://github.com/flathub/io.webtorrent.WebTorrent/issues/3

**Comment by barcazama** [comment]
Awesome thank you @subins2000 for the explaining. I thought app owner choose on which platform they made it available, I didn't know it was unofficial. Closing the issue, sorry for the trouble :)
