### ISSUE TITLE
UI unclear for Skip (“Don’t Download”) indiv file

### ISSUE THREAD

**Issue by dsernst** [webtorrent/webtorrent-desktop#1876]
**What version of WebTorrent Desktop are you using?**

0.24

**What happened?**

The UI for “Skip File” / “Don’t Download” feature could be more clear. 

Currently, it’s hidden behind big X buttons on the far right side of the file list. This is inconsistent w/ the torrent controls, which use a checkbox on the left side for the similar control `Downloading` / `Pause Torrent Download`, and instead use the right side X for the destructive action `Remove Torrent`.

It took me months before discovering those individual Don’t Download file buttons, and only after finding a note from @feross about it while hunting through old Github Issues.

Now I understand it, and make use of it a lot more, but my hunch is other people could be similarly unclear about this.

**What did you expect to happen?**

Possible solutions:

A) Move these buttons to match the torrent controls, eg a checkbox on the left side. Concern this may look too cluttered?

B) Allow right clicking individual files, with an option to Don’t Download, which would cause the state change visual, so users would quickly learn what those file level right-side buttons are for.

B-2) Ideally you could also multi-select, e.g. hold `Shift` to select a group or `Ctrl` to add individual ones, and then toggle Don’t Download for all of them at once. uTorrent uses this approach, for example.

**Are you willing to submit a pull request to fix this bug?**

Yes, but not sure which design to take, or a different approach.

**Comment by alianza** [comment]
After literal years of use I always thought this program lacked such functionality

**Comment by fusir** [comment]
I agree.  It would be nice to see the standard full UI we see with most desktop clients with highlighting, and grouping.  I've tried a couple of the other recommended webtorrent desktop clients and there is a theme of either no file management (the usual), or this one gives us the exception of having file management but being very unclear, and unable to be done on multiple files at once.

If we could get the typical UI for torrent management web torrent would have much more adoption and you'd have more people willing to bridge content.
