### ISSUE TITLE
Webtorrent Desktop not showing up after restarting PC in windows 10

### ISSUE THREAD

**Issue by SebghatYusuf** [webtorrent/webtorrent-desktop#1879]
**Web version*
--
**What operating system and version?**
Windows 10, Version 10.0.19041 Build 19041
**What happened?**
Can't see the Application UI to work with. 
**What did you expect to happen?**
must show the UI. 
**Are you willing to submit a pull request to fix this bug?**
I'm not sure.

**Comment by SebghatYusuf** [comment]
Just Fixed The Issue

**Comment by SebghatYusuf** [comment]
The Issue has been solved, Maybe there was some problem with my windows

**Comment by feross** [comment]
Great – thanks for following up to close this issue :)
