### ISSUE TITLE
Play/Pause video by clicking the current video

### ISSUE THREAD

**Issue by DonovanPhoenix** [webtorrent/webtorrent-desktop#1893]
WebTorrent Desktop Version 0.24.0 (0.108.6) (x64)
Microsoft Windows [Version 10.0.19042.630]

I would like a feature that Plays/Pauses a video when you click on the current displaying/showing video. similar to how youtube works.

**Comment by feross** [comment]
I support adding this feature. Would someone like to send a pull request?

**Comment by dsernst** [comment]
Looks like this PR: https://github.com/webtorrent/webtorrent-desktop/pull/1878

**Comment by alxhotel** [comment]
> Looks like this PR: #1878

Yep. Closing
