### ISSUE TITLE
support of Mac OS Big Sur?

### ISSUE THREAD

**Issue by saurabh02468** [webtorrent/webtorrent-desktop#1894]
Will the Web torrent app run on Big Sur?

**Comment by justchen1369** [comment]
> **Mac build notes**
  The Mac app can only be packaged from macOS.

**Comment by justchen1369** [comment]
https://webtorrent.io/desktop/

**Comment by feross** [comment]
It should work on macOS Big Sur – however I'm updating right now to test it out.

**Comment by feross** [comment]
It works perfectly for me, but I've heard a report from someone else that the app doesn't start up. We can probably fix this by updating Electron.

**Comment by feross** [comment]
The person who said it doesn't work on macOS Big Sur ended up having issues with other apps too that seem to caused by a macOS bug. So not WebTorrent specific.

I think it's safe to say that WebTorrent Desktop works on macOS Big Sur without issues.
