### ISSUE TITLE
Private torrents

### ISSUE THREAD

**Issue by atomtm** [webtorrent/webtorrent-desktop#1897]
Can someone please explain in detail what private torrent option is for ?
![image](https://user-images.githubusercontent.com/6628454/99898365-97095b00-2ca9-11eb-852a-572748c34a27.png)

Thank you in advance

**Comment by alxhotel** [comment]
If the private checkbox is enabled, the client will only search for peers through the provided trackers. It will avoid using PEX or DHT, even if all trackers are down.

**Comment by atomtm** [comment]
Thank you!
Sorry for offtopic but is there a way to have a private tracker that only friends will have access too, and secure it with basic auth for example?

**Comment by alxhotel** [comment]
I think the common way to do this authentication is by passing query parameters in the URL.

Just as: `https://example-tracker.com/announce?auth=12345678`

**Comment by atomtm** [comment]
Any trackers you have in mind for this ?

**Comment by alxhotel** [comment]
No, sorry. You can search in Google. I'm sure there are plenty of thema.
