### ISSUE TITLE
The Download Wont Continue 

### ISSUE THREAD

**Issue by RTCHID** [webtorrent/webtorrent-desktop#1898]
Version 0.24.0 (0.108.6) (x64)

Windows 10 Pro Version: 20H2

The Download Just Stop Randomly Even When I Restart My Computer it just showing XX% Downloaded ↓0B/s ↑0B/s

I'm Expecting it Continue to Download

**Comment by feross** [comment]
This will happen with some torrents which lack peers, or if you're on an internet connection which is filtering torrent traffic to block it.
