### ISSUE TITLE
Refactor ETA and download progress calculations

### ISSUE THREAD

**Issue by hicom150** [webtorrent/webtorrent-desktop#1902]
**What problem do you want to solve?**
As it is described in https://github.com/webtorrent/webtorrent-desktop/pull/1217 ETA and download progress calculation code seems to be duplicated.

**What do you think is the correct solution to this problem?**
A code refactor should be made to move this calculations to a common place so it can be reused without duplication. 

**Are you willing to submit a pull request to implement this change?**
Sure! ;)

**Comment by AlexHladin** [comment]
I have already created a PR to refactor ETA code https://github.com/webtorrent/webtorrent-desktop/pull/2055

**Comment by alxhotel** [comment]
Closed by #2055
