### ISSUE TITLE
Some features not working well compare to downloaded WTD

### ISSUE THREAD

**Issue by martinsangdo** [webtorrent/webtorrent-desktop#1906]
Hi,
I downloaded WTD (WebTorrent Desktop) app version 0.24.0.
I did checkout latest source in master branch, build it in Windows platform.
I found 1 issue when compare between built source app & your app. (I use same magnet link, same folder, same PC)
WTD plays video faster. Ex: it starts playing when download 13%, whereas my app plays around 20~25%.

**Comment by alxhotel** [comment]
Hi @martinsangdo,

Thanks for the feedback!

The difference you are describing might be neglectable. Nonetheless, this might be interesting to look at.

Does this happen with every single torrent or just with one in particular?

What video format are you playing?

How big is the video you are playing?

Is this happening consistently with the magnet link you are trying?
