### ISSUE TITLE
webtorrent download virus with vlc

### ISSUE THREAD

**Issue by 2020karaulov2020** [webtorrent/webtorrent-desktop#1908]
After press download vlc, webtorrent download https://dnvnt0lrsqk55.cloudfront.net/vlc-3.0.5-streamer.exe file, but it blocked as Malware. Please remove this file from webtorrent !

**Comment by alxhotel** [comment]
Hi @2020karaulov2020,

That link doesn't seem to be used in the Webtorrent Desktop app.

If you want to download VLC, please do it from the official source: https://www.videolan.org/vlc/

**Comment by feross** [comment]
I noticed that we're linking to VLC over HTTP. We should use an HTTPS link in case this user was man-in-the-middled and redirected to a malicious website.

PR here: https://github.com/webtorrent/webtorrent-desktop/pull/1987
