### ISSUE TITLE
install erreur dpkg ldconfig PATH start-stop-daemon

### ISSUE THREAD

**Issue by djullius** [webtorrent/webtorrent-desktop#1909]
**What version of WebTorrent Desktop are you using?**
 webtorrent-desktop_0.24.0_amd64.deb

**What operating system and version?** 
`uname -a`
Linux debian 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
`cat /etc/debian_version`
10.7

**shell command?** 
`su root`
`cd /home/debian/Téléchargements`
`apt-get update`
`apt-get upgrade`
`dpkg -i webtorrent-desktop_0.24.0_amd64.deb`

**What happened?**
dpkg: avertissement: « ldconfig » introuvable dans la variable PATH ou non exécutable
dpkg: avertissement: « start-stop-daemon » introuvable dans la variable PATH ou non exécutable
dpkg: erreur: 2 programmes attendus non trouvés dans la variable PATH ou non exécutables
Note : la variable PATH du superutilisateur doit normalement contenir /usr/local/sbin, /usr/sbin et /sbin

**Are you willing to submit a pull request to fix this bug?**
Resolve :
`export PATH=$PATH:/usr/local/sbin`
`export PATH=$PATH:/usr/sbin`
`export PATH=$PATH:/sbin`

**Comment by alxhotel** [comment]
This error is based on your operating system configuration. This does not seem like something we should fix in the app.
