### ISSUE TITLE
Play button breaks after backing out of playback

### ISSUE THREAD

**Issue by stephen304** [webtorrent/webtorrent-desktop#1915]
**What version of WebTorrent Desktop are you using?**
Git master

**What operating system and version?**
Arch

**What happened?**
I added a torrent with multiple videos and started playing one. I backed out and tried to play another file from the same torrent but the play button did nothing despite the torrent being completed.

**What did you expect to happen?**
Play button should still work and not require a restart in between playing files.

**Are you willing to submit a pull request to fix this bug?**
Not at this time

**Comment by alxhotel** [comment]
Hi @stephen304,

Thanks for the feedback!

I had a similar experience and this seems to happen when there is an exception in JS.

Can you try to reproduce this bug again?

If so, can you open the developer tools by clicking `View > Developer > Developer Tools` and sharing the error you get in the console (if any)?

**Comment by stephen304** [comment]
I can't seem to reproduce this anymore so it seems it's been fixed
