### ISSUE TITLE
show web torrent process and corresponding hotkey does not open task manager to view process

### ISSUE THREAD

**Issue by hyperdeathbeam** [webtorrent/webtorrent-desktop#1917]
**What version of WebTorrent Desktop are you using?**
Version 0.24.0 (0.108.6) (x64)
**What operating system and version?**
Windows 10 Pro 20H2
**What happened?**
clicking view>developer>show web torrent process or hotkey ctrl+shift+p does not show process and instead shows developer tools
**What did you expect to happen?**
clicking view>developer>show web torrent process or hotkey ctrl+shift+p should open task manager to view process 
**Are you willing to submit a pull request to fix this bug?**
yes

**Comment by alxhotel** [comment]
Hi @hyperdeathbeam,

The goal of the `Show WebTorrent Process` option is to show the developer tools of the WebTorrent process that is running in the background. This is option is just meant for developers.

It is not supposed to open the task manager.
