### ISSUE TITLE
material-ui@"^0.20.2" doesn't support React 17

### ISSUE THREAD

**Issue by slayerjain** [webtorrent/webtorrent-desktop#1923]
**What version of WebTorrent Desktop are you using?**
master

**What operating system and version?**
Apple M1 Big Sur

**What happened?**
Dependency issue

**What did you expect to happen?**
install successfully

**Are you willing to submit a pull request to fix this bug?**
Maybe, migrating to the latest react could be large. 

I was actually trying to update the chrome-driver to 11 to compile this for Apple M1 MacBooks but faced with this problem. 

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: webtorrent-desktop@0.24.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.4.0 || ^16.0.0" from material-ui@0.20.2
npm ERR! node_modules/material-ui
npm ERR!   material-ui@"^0.20.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by marchellodev** [comment]
[material-ui](https://www.npmjs.com/package/material-ui) seems to be deprecated. It is advised to use [@material-ui/core](https://www.npmjs.com/package/@material-ui/core) instead
