### ISSUE TITLE
Speed limit

### ISSUE THREAD

**Issue by 2020karaulov2020** [webtorrent/webtorrent-desktop#1924]
Please add speed limit option)) I can't watch videos because upload speed bigger than download))
![110248886-57c6f780-7f84-11eb-9284-cff1d9e001bf](https://user-images.githubusercontent.com/62130676/110269925-c7b19e00-7fd5-11eb-9937-61dc279dfe95.png)

**Comment by alxhotel** [comment]
Do not use WebTorrent for copyright infringement. No one will be able to assist you.

**Comment by 2020karaulov2020** [comment]
> Do not use WebTorrent for copyright infringement. No one will be able to assist you.

Yes now I use bittorrent. )
