### ISSUE TITLE
Android app for webtorrent

### ISSUE THREAD

**Issue by vpn12** [webtorrent/webtorrent-desktop#1930]
Pls provide Android version of webtorrent like Webtorrent desktop.

**Comment by alxhotel** [comment]
Hi @vpn12,

Although it would be nice to have an Android app, at the moment we are focusing on desktop. The mobile version would have to use a different framework, since Electron is desktop-based.

So I'm closing this issue, but it might be cool for the future.

**Comment by dtantono** [comment]
I second this. mobile app will be awesome
