### ISSUE TITLE
Green screen when I do full screen

### ISSUE THREAD

**Issue by ParkerQ** [webtorrent/webtorrent-desktop#1975]
**0.24.0**

**macos*

**green screen when in full screen**

**not a green screen**

**yes**

**Comment by alxhotel** [comment]
Hi @ParkerQ,

Does the green screen happen always or just with a specific file/format?

**Comment by feross** [comment]
Also – what version of macOS? Intel or M1 chip?

This issue was opened without using the template. Please don't skip the template as it has useful that helps us.

**Comment by ParkerQ** [comment]
Hello,
It appears that after my recent Big Sur v11.4 update, the green screen has gone away when playing on full screen.
2.6 GHz Dual-Core Intel Core i5

Thank you,

Jon Quyle

><((((º>`·.¸¸.·´¯`·.¸.·´¯`·...¸><((((º>
´¯`·.¸. , . .·´¯`·.. ><((((º>
`·.¸¸.·´¯`·.¸.·´¯`·...><((((º>

**Comment by feross** [comment]
That's amazing!
