### ISSUE TITLE
Is there anyway to stop seeding/block torrents

### ISSUE THREAD

**Issue by IgglueOffical** [webtorrent/webtorrent-desktop#1995]
So basically my bandwidth is being eaten up by torrents. And I'm not sure how to stop it. There seems to be no feature inside of webtorrent, that allows me to limit bandwidth or stop seeding a torrent. So is there any other way to not have my bandwidth be eat up by seeded torrents?

**Comment by alxhotel** [comment]
Hi @IgglueOffical,

You can pause a torrent by clicking the checkbox of the torrent.

Limiting the bandwidth used in something already in progress webtorrent/webtorrent#2062
