### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by marchellodev** [webtorrent/webtorrent-desktop#2029]
WebTorrent is one of the best cross platform torrent clients. However, it seems like the last release was almost a year ago. While webtorrent package seems to receive a lot of updates, the webtorrent desktop app does not seem to progress.

Also, it seems like the master branch is broken. There are a lot of dependency incompatibility problems, which make it impossible to build the latest version from source.

Thanks!

**Comment by marchellodev** [comment]
Is there anyone who has a lot of experience with js/electron, and could maintain a fork of this repo? :>

I bet we could easily base the fork on 0.24.0, update all dependencies, and merge important PRs/commits from this repo.

**Comment by dreaddr** [comment]
I came here looking to see if this project is dead too, which is unfortunate if it is because it really is a solid torrent management software.

**Comment by DiegoRBaquero** [comment]
It's not dead, it's under active dev and maintenance :)

**Comment by marchellodev** [comment]
@DiegoRBaquero We w-want a new release uwu
