### ISSUE TITLE
I want to be able to see my download/upload ratio in the UI.

### ISSUE THREAD

**Issue by draav** [webtorrent/webtorrent-desktop#2069]
**What version of WebTorrent Desktop are you using?**

Version 0.24.0 (0.108.6)

**What operating system and version?**

MacOS Catalina 10.15.7

**What problem do you want to solve?**

I want to be able to see how much I've seeded. I can't find any easy way in the UI to make sure I' ve least hit a ratio of 1 between upload/download. 

**What do you think is the correct solution to this problem?**

If there was some option I could toggle to see these stats in the UI it would be useful. This may already exist and I am just not able to find it.

**Are you willing to submit a pull request to implement this change?**

Probably, if I was pointed to a spot in the code that would make sense to add the logic. I would try to do it. I see there is some `client.ratio` stat available [in the API](https://webtorrent.io/docs), but not sure where I would reference that call to display it in the UI.

**Comment by AndreCascais** [comment]
I would also love this feature!
