### ISSUE TITLE
Downloads are super slow or don't start

### ISSUE THREAD

**Issue by sph3** [webtorrent/webtorrent-desktop#2083]
**What version of WebTorrent Desktop are you using?**
0.24.0 (0.108.6) (x64)

**What operating system and version?**
Windows 10 Pro 20H2 19042.1288

**What happened?**
Downloads are super slow and sometimes don't even start. Max download speed is around 50kbps.
The same torrent on other apps such as qBittorrent downloads just fine.

**What did you expect to happen?**
For the torrent do download at maximum speed

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by KANLen09** [comment]
Been facing the same issue for days too where download speed is capped @ 100kbps. Upload speed is fine (even though I don't know how to set up the upload limiter).

Using Windows 11 21H2 22000.258 and it should work as fine as Windows 10 with the same version.
