### ISSUE TITLE
Webtorrent does not recognize flatpak installed vlc

### ISSUE THREAD

**Issue by kumavis** [webtorrent/webtorrent-desktop#2094]
i can run vlc from the cli as `flatpak run org.videolan.VLC`

**Comment by kumavis** [comment]
looks like this case should be covered https://github.com/feross/vlc-command/blob/3a18baefa38b8889709acdf220d9bae3a227f5b8/index.js#L64

**Comment by kumavis** [comment]
i think the issue might be that webtorrent is also installed via flatpak and has insufficient permissions to run vlc

**Comment by S7venLights** [comment]
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?

https://github.com/flathub/io.webtorrent.WebTorrent/issues/3 is relevant/linked to this issue.
