### ISSUE TITLE
Zero byte downloads

### ISSUE THREAD

**Issue by nokuchi** [webtorrent/webtorrent-desktop#2100]
WebTorrent says it's downloaded 4GB or 2GB or any size file but when I try to open the file (MacOS Monterey) they are all zero bytes. I've tried many different torrents and files with the same results. There's plenty of room on the hard disk. What gives?

**Comment by nokuchi** [comment]
I could not resolve the issue so I stopped using WebTorrent. So, no, I guess it is no longer relevant.

**Comment by alxhotel** [comment]
Hi @nokuchi,

Please send reproduction steps to check this problem (but without the torrent you are using)
