### ISSUE TITLE
flatpak webtorrent can't recognize flatpak vlc

### ISSUE THREAD

**Issue by zihaaad** [webtorrent/webtorrent-desktop#2101]
**Version 0.24.0 (0.108.6) (x64)**

**Fedora 35 Kinoite**

I have installed webtorrent and vlc via flatpak. Now webtorrent can't recognize vlc as external player.

**Comment by S7venLights** [comment]
How do you select an external flatpak app as an external player?

I'm also on Fedora Silverblue and using Webtorrent flatpak.
I can't figure out how to navigate to and allow an external flatpak app to set.

**Comment by r14c** [comment]
what is needed to demonstrate that this issue can be reproduced? i can say that its happening for me, i have both webtorrent and vlc installed via flatpak. if i try to play an unsupported video, it just kicks me to the vlc download page.
