### ISSUE TITLE
Files are stored in the computer

### ISSUE THREAD

**Issue by Deniz1433** [webtorrent/webtorrent-desktop#2118]
Why are streamed files stored in the computer? Doesn't it defeat the whole purpose of streaming? It's almost the same as downloading and playing the file, the only difference being that you don't have to wait until the entire file is downloaded.

**Comment by angrymouse** [comment]
You can play media files even before end of downloads

**Comment by Deniz1433** [comment]
> You can play media files even before end of downloads

"the only difference being that you don't have to wait until the entire file is downloaded."

**Comment by Avamander** [comment]
That's how streaming works, yes.

**Comment by DiegoRBaquero** [comment]
Streaming has never been about keeping a whole video in memory. Just delete it after watched (?)
