### ISSUE TITLE
TV IP Address is detected incorrectly is there a way to change the TV's IP?

### ISSUE THREAD

**Issue by asolopovas** [webtorrent/webtorrent-desktop#2212]
**What version of WebTorrent Desktop are you using?**
Version 0.24.0 (0.108.6) (x64)

**What operating system and version?**
Edition	Windows 10 Pro
Version	21H2
Installed on	‎14/‎04/‎2022
OS build	19044.1706
Experience	Windows Feature Experience Pack 120.2212.4170.0

**What happened?**
The DLNA ip address of the TV is shown as 192.168.1.7 rather than 192.168.1.9 thus it fails to connect whenever I try to stream to tv is there a way to modify TV ip address I cant seem to find the setting
**What did you expect to happen?**
I expected IP Address of the TV to be detected correctly
**Are you willing to submit a pull request to fix this bug?**
I am very much unfamiliar with internals of this library

**Comment by DominikNovosel** [comment]
Can you confirm you can cast to your TV outside of WebTorrent? Please also check if you can cast from other devices.

**Comment by DominikNovosel** [comment]
What about the device you're using WebTorrent on? Does it work there with applications other than WebTorrent?

**Comment by asolopovas** [comment]
It would be great if you let me know how can I diagnose that? It's just that I don't know how it's casts without issue on android but when it comes to Windows machine it isn't finding it, I tried turning off firewall, enable various share options so now I can sort of load video files from my pc directly on the TV but does not work in the app

**Comment by DominikNovosel** [comment]
Hm. I have an idea, but it probably won't solve your problem and will beat the purpose of having WebTorrent in the first place.
I don't know what kind of TV you have, but I guess you can try using Kodi's UPnP server and/or client, depending on whether or not you can install Kodi on your TV. 
Setup guide: https://kodi.wiki/view/UPnP
My theory is that Kodi may have its own UPnP implementation built in, possibly bypassing whatever problem exists in your system itself.

So, you setup the server on your Windows machine, and see if the TV (preferably with Kodi as the client) picks it up. If it works, yay, at least something does. If not, I... seriously don't know how to help you. Networks are nasty business with many potential hardware and software failure points, and if something doesn't work out of the box, reconfiguring it will be a pain and probably break something else. The DLNA/UPnP specifications are their own kind of mess: https://en.m.wikipedia.org/wiki/Universal_Plug_and_Play

**Comment by DominikNovosel** [comment]
You could also check whether your wired and wireless networks are on different subnets.
