### ISSUE TITLE
Webtorrent Mac Client not working in Monterey

### ISSUE THREAD

**Issue by timshutes** [webtorrent/webtorrent-desktop#2243]
**What version of WebTorrent Desktop are you using?**
0.24

**What operating system and version?**
Mac OS 12.5.1 (Monterey)

**What happened?**
Web Torrent queues torrent files but the download never starts. I've tried restarting, disabling the firewall, turning VPN on and off, deleting and re-installing. It does this with every torrent file.

When I quit and restart the app, I get the error: "Path Missing. Fix and restart the app, or delete the torrent" See screenshots.

**What did you expect to happen?**
Expected the torrent file to download and play.

**Are you willing to submit a pull request to fix this bug?**
Whatever is needed

<img width="530" alt="CleanShot 2022-09-02 at 12 01 08@2x" src="https://user-images.githubusercontent.com/779398/188193851-09b58724-be68-4d43-a058-91aa02182222.png">

![CleanShot 2022-09-02 at 12 04 16@2x](https://user-images.githubusercontent.com/779398/188194452-2bb212eb-dffd-4354-9ddc-a435b726eb22.png)

**Comment by DiegoRBaquero** [comment]
Are the torrents you are trying to download working in other clients?

**Comment by timshutes** [comment]
yes - they work in every other client I've tried

**Comment by timshutes** [comment]
Hi - sorry for letting this go stale - I've since removed WebTorrent mac client entirely, upgraded to Ventura, and have the same problem. The app is non-functional in the latest mac environments. Is anyone else reporting this?
