### ISSUE TITLE
I don't know how to update

### ISSUE THREAD

**Issue by thelordreturn** [webtorrent/webtorrent-desktop#2252]
I am currently using the v0.24.0 version that I downloaded from the website.

I want to update to webtorrent v1.8.30 but I don't know how I am updating an open source program for the first time.

Can you explain step by step please.

**Comment by DiegoRBaquero** [comment]
Hello, desktop version is bundled, sadly webtorrent library cannot be updated independently

**Comment by thelordreturn** [comment]
> Merhaba, masaüstü sürümü paket halindedir, ne yazık ki webtorrent kitaplığı bağımsız olarak güncellenemez

what is webtorrent v1.8.30 then?

**Comment by DiegoRBaquero** [comment]
That's the latest version if the library: https://github.com/webtorrent/webtorrent/

**Comment by thelordreturn** [comment]
> Bu, kütüphanenin en son sürümüdür: https://github.com/webtorrent/webtorrent/

I'm sorry I don't know how to use open source code can you tell me how to install these 2?

https://github.com/webtorrent/webtorrent-cli

https://github.com/webtorrent/webtorrent/

I just want the webtorrent I use to be up to date

**Comment by thelordreturn** [comment]
Is this currently the most current version v0.24.0 for desktop?
