### ISSUE TITLE
WebTorrent disable auto resize

### ISSUE THREAD

**Issue by RedaBousserhane** [webtorrent/webtorrent-desktop#2258]
WebTorrent disable auto resize
help me : reda@kollchi.com

**Comment by tomihbk** [comment]
One work around you can use is to simply use VLC as external player and inside the VLC's settings page. Make sure to untoggle "Resize interface to video size"

![image](https://user-images.githubusercontent.com/18231519/193890345-e050ecc6-67bc-4186-9765-4907cd725632.png)

**Comment by RedaBousserhane** [comment]
yes works in VLC, but not on WebTorrent

**Comment by tomihbk** [comment]
True, hence "work around"

**Comment by RedaBousserhane** [comment]
yes thanks
