### ISSUE TITLE
Webtorrents do not download after >5 mins

### ISSUE THREAD

**Issue by DubiousTunic** [webtorrent/webtorrent-desktop#2260]
**What version of WebTorrent Desktop are you using?**
v24.0
**What operating system and version?**
Ubuntu 22.04
**What happened?**
Torrents do not download from browser after WebTorrent Desktop is running for >5 minutes. Here is a .webm https://webm.red/y0wQ
**What did you expect to happen?**
Torrents should continue to download after WebTorrent has been running. This may be related to https://github.com/webtorrent/webtorrent/issues/1981
**Are you willing to submit a pull request to fix this bug?**
Not able

**Comment by DiegoRBaquero** [comment]
WebRTC P2P connection cannot be established between browser and app. And as you are probably the only seeder, if it doesn't work, there's nothing to be done. Please check that WebRTC is enabled in the browser and that there's no firewall blocking such connections.

**Comment by DubiousTunic** [comment]
WebRTC is enabled in the browser, and there is no firewall blocking the connections. If you watch the end of the .webm, when WebTorrent Desktop is restarted the torrent downloads from instant.io. It just hangs after Webtorrent Desktop has been open for around 5 minutes. I have about 180 torrents seeding if that matters

**Comment by norzak** [comment]
WebTorrent.app/Contents/Resources/app.asar/build/renderer/controllers/torrent-controller.js:46 warning for torrent 3: tracker request timed out (undefined) (udp://tracker.leechers-paradise.org:6969)
WebTorrent.app/Contents/Resources/app.asar/build/renderer/main.js:357 webtorrent: got wt-warning
WebTorrent.app/Contents/Resources/app.asar/build/renderer/controllers/torrent-controller.js:46 warning for torrent 3: tracker request timed out (undefined) (udp://tracker.coppersurfer.tk:6969)
WebTorrent.app/Contents/Resources/app.asar/build/renderer/main.js:357 webtorrent: got wt-warning
WebTorrent.app/Contents/Resources/app.asar/build/renderer/controllers/torrent-controller.js:46 warning for torrent 3: tracker request timed out (undefined) (udp://tracker.empire-js.us:1337)
WebTorrent.app/Contents/Resources/app.asar/build/renderer/main.js:357 webtorrent: got wt-warning
WebTorrent.app/Contents/Resources/app.asar/build/renderer/controllers/torrent-controller.js:46 warning for torrent 1: tracker request timed out (undefined) (udp://tracker.leechers-paradise.org:6969)
WebTorrent.app/Contents/Resources/app.asar/build/renderer/main.js:357 webtorrent: got wt-warning
WebTorrent.app/Contents/Resources/app.asar/build/renderer/controllers/torrent-controller.js:46 warning for torrent 1: tracker request timed out (undefined) (udp://tracker.coppersurfer.tk:6969)
WebTorrent.app/Contents/Resources/app.asar/build/renderer/main.js:357 webtorrent: got wt-warning
WebTorrent.app/Contents/Resources/app.asar/build/renderer/controllers/torrent-controller.js:46 warning for torrent 1: tracker request timed out (undefined) (udp://tracker.empire-js.us:1337)
WebTorrent.app/Contents/Resources/app.asar/build/renderer/main.js:357 webtorrent: got wt-warning
WebTorrent.app/Contents/Resources/app.asar/build/renderer/controllers/torrent-controller.js:46 warning for torrent 2: tracker request timed out (undefined) (udp://tracker.leechers-paradise.org:6969)
WebTorrent.app/Contents/Resources/app.asar/build/renderer/main.js:357 webtorrent: got wt-warning
WebTorrent.app/Contents/Resources/app.asar/build/renderer/controllers/torrent-controller.js:46 warning for torrent 2: tracker request timed out (undefined) (udp://tracker.coppersurfer.tk:6969)
WebTorrent.app/Contents/Resources/app.asar/build/renderer/main.js:357 webtorrent: got wt-warning
WebTorrent.app/Contents/Resources/app.asar/build/renderer/controllers/torrent-controller.js:46 warning for torrent 2: tracker request timed out (undefined) (udp://tracker.empire-js.us:1337)
WebTorrent.app/Contents/Resources/app.asar/build/renderer/main.js:357 webtorrent: got wt-warning
WebTorrent.app/Contents/Resources/app.asar/build/renderer/main.js:344 dispatch: openTorrentContextMenu Array(1)
21WebTorrent.app/Contents/Resources/app.asar/build/renderer/main.js:357 webtorrent: got wt-progress

**Comment by norzak** [comment]
After getting these timeouts webtorrent desktop stops. After a while later, it get wt-progress 21 times for some reason and starts to run again until it timeouts all trackers again

**Comment by Acelya-9028** [comment]
Yes same

**Comment by DubiousTunic** [comment]
This may be related to https://github.com/webtorrent/webtorrent/issues/1981 but the solution there isn't permanent it only works intermittently or up to 24 hrs
