### ISSUE TITLE
Downloads gets paused and stop, while playing video to an external media player

### ISSUE THREAD

**Issue by dexoidan** [webtorrent/webtorrent-desktop#2278]
**What version of WebTorrent Desktop are you using?**
WebTorrent Version 0.24.0 (0.108.6) (x64)

**What operating system and version?**
Windows 10 Home 21H1 build 19043.2130

**What happened?**
While downloading a torrent. I had finished another download that is a video I was like play. But I was trying playing the video from WebTorrent. There is a problem with downloads in the background gets stopped, when you start playing a video while downloading.

**What did you expect to happen?**
I can play all videos, while downloads is running in background, unless they gets manually stopped.

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by aqual3o** [comment]
@dexoidan - I believe it's a setting on WebTorrent desktop app. You can go to settings (preferences) and `un-select` the "Highest Playback Priority" setting. 
Having this selected pauses all active downloads while playing any media.
