### ISSUE TITLE
Is this still being developed?

### ISSUE THREAD

**Issue by DominikNovosel** [webtorrent/webtorrent-desktop#2309]
I know this has been asked before in #2029, but even another year later, there doesn't seem to have been significant progress. It would be a shame if development stopped, i really enjoy using the app since the UX is so simple.

**Comment by maddymodd** [comment]
Yes, this project is still being developed.

**Comment by DominikNovosel** [comment]
Any idea if there'll be a new release soon? A lot of important bug and security fixes have been made since the last one.

**Comment by sl-einert** [comment]
@maddymodd Is there any update on the upcoming release?

**Comment by shahin365** [comment]
> > Any idea if there'll be a new release soon? A lot of important bug and security fixes have been made since the last one.
> 
> There will likely be a new release this week.

any news on that?

**Comment by DominikNovosel** [comment]
> any news on that?

I guess not. Fun fact, this is the third Electron app I've used that appears to have been silently abandoned one day. Must be a curse or something.
In any case, some of the newer commits were carried over to this custom build: https://github.com/maddymodd/webtorrent-with-speed-limits.

**Comment by tutacat** [comment]
It just hasn't made a release for 3 years. No big deal/s

**Comment by Acelya-9028** [comment]
@DominikNovosel Hi, yes this project is dead and not maintained anymore. Are you interested to merge [this](https://github.com/webtorrent/webtorrent-desktop/pull/2292) in your custom build? Maybe your build can became the last up to date build...

**Comment by DominikNovosel** [comment]
> @DominikNovosel Hi, yes this project is dead and not maintained anymore. Are you interested to merge [this](https://github.com/webtorrent/webtorrent-desktop/pull/2292) in your custom build? Maybe your build can became the last up to date build...

That is not my build, it belongs to @maddymodd. Additionally, I'm not a programmer, I'm a multimedia technician and translator and unfortunately I don't have the time or knowledge to continue maintaining this project.

**Comment by Acelya-9028** [comment]
> > @DominikNovosel Hi, yes this project is dead and not maintained anymore. Are you interested to merge [this](https://github.com/webtorrent/webtorrent-desktop/pull/2292) in your custom build? Maybe your build can became the last up to date build...
> 
> That is not my build, it belongs to @maddymodd. Additionally, I'm not a programmer, I'm a multimedia technician and translator and unfortunately I don't have the time or knowledge to continue maintaining this project.

Oh yes my bad... So I redo my statement. @maddymodd Are you interested to merge [this](https://github.com/webtorrent/webtorrent-desktop/pull/2292) in your custom build? I can send you a PR x)

**Comment by Paxa** [comment]
Will it be nice to have builds for every commit via github actions? I can help with PR (I made it for my own electron app)

**Comment by farribeiro** [comment]
I saw a developer update the app some time ago but not everything. If I remember is @DiegoRBaquero

**Comment by farribeiro** [comment]
Interesting is to make the issue #2272

**Comment by Acelya-9028** [comment]
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?

Yes obviously.

**Comment by farribeiro** [comment]
idk

**Comment by produdez** [comment]
I've looked through the repo and from my view the project is most likely dead. It's a shame I really like the app and wanted to contribute (im newbie tho).
1. No meaningful commits since May 12, 2022, commits nows are only automated deps update
2. No issuses gets checked by authors/contributors/maintainers anymore after Sep 22, 2022 (last looked at issue is 2260) 
3. Same for PRs
4. Though maddymodd suggests that there's active development, I don't see him under the contributors list of the project or part of the webtorrent team. So it's likely he's workin on his fork rather than this one getting updates.

I could be wrong tho since alxhotel and ThaUnknown (member of webtorrent team) does tag/close some recent issues/prs but other than that, no comments or active devs from the team.

**Comment by Acelya-9028** [comment]
Definitely dead. It's a shame.
