### ISSUE TITLE
Unable to read property of undefined... reading 'getBounds' on file build/main/windows/main.js line 87

### ISSUE THREAD

**Issue by Kheurt** [webtorrent/webtorrent-desktop#2381]
**What version of WebTorrent Desktop are you using?**
WebTorrent V0.24.0 august 2020

**What operating system and version?**
window arch64

**What happened?**
After running the following commands in order
- npm install
- npm fund
- npm audit fix --force
- npm start

**What did you expect to happen?**
Expected to see the app home screen or something like on the README.md screenshot

**Are you willing to submit a pull request to fix this bug?**
I dont even know how to solve the

**Comment by vinitsingh-13** [comment]
can i start to work on this issue. so i can fix it

**Comment by Kheurt** [comment]
You can start...
