### ISSUE TITLE
NordVPN is reporting that this app is vulnerable

### ISSUE THREAD

**Issue by kaiyoma** [webtorrent/webtorrent-desktop#2393]
**What version of WebTorrent Desktop are you using?**

0.24.0

**What operating system and version?**

Windows 11

**What happened?**

When I open NordVPN, it reports that WebTorrent is a vulnerable app:

![image](https://github.com/webtorrent/webtorrent-desktop/assets/10719780/8ae9e152-6155-48d0-9c43-ff62e62b5a4b)

**What did you expect to happen?**

Not this.

**Are you willing to submit a pull request to fix this bug?**

No.

**Comment by kaiyoma** [comment]
Yes, still relevant.

**Comment by kaiyoma** [comment]
Still relevant. Waiting for someone else to respond.

**Comment by farribeiro** [comment]
There's not much you can do but launch a new version of the app... For now, it is still in development. A few days ago someone with a lot of praise managed to update the electron (the component that causes this warning).

It was supposed to have released a new version almost 2 years ago when they updated the dependencies.
