### ISSUE TITLE
Adding Watch Party Support

### ISSUE THREAD

**Issue by satnam-sandhu** [webtorrent/webtorrent-desktop#2413]
Hi everyone,
I wanna add Watch Party support for webtorrent.

Something pretty basic like requesting a peer to watch/stream a torrent together.
Thought it would probably be more productive to start a discussion before I submit a PR.

What do you think?

**Comment by Abiji-2020** [comment]
Is it possible to add in the existing torrent  app and could i know how are you going to implement it 

By the I am not part of the Webtorrent but I am eager about the watch party
