### ISSUE TITLE
Change audio track

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent-desktop#277]
Some video files have multiple audio tracks, most often for different languages. Once Chromium lands support for multiple audio tracks, we can add this to WebTorrent Desktop.

https://bugs.chromium.org/p/chromium/issues/detail?id=249427
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/7ZWqizEIK1E

**Comment by ethaniel** [comment]
I support. We need this.

**Comment by alienato** [comment]
We need that!

**Comment by klaygomes** [comment]
So... is it possible we see it on WebTorrent?

**Comment by petrstepanov** [comment]
guys please

**Comment by avmoraes** [comment]
<video id="video-player_html5_api" data-setup="{ &quot;controls&quot;: false, &quot;autoplay&quot;: false, &quot;preload&quot;: &quot;none&quot; }" class="vjs-tech" style="display: block; top: 0px;" preload="none" src="http://127.0.0.1:19575/stream?token=1abd50442a33007521974fb8743f78f5f6bbfd0&amp;localauth=localapi69806fb4f9ca3ff9:&amp;sid=15f043461e1e965c1bb34e4bf912a7485e0af8e4&amp;file=2&amp;ts=28.88181818181818&amp;accept=video/mp4; codecs=&quot;avc1.640029, mp4a.40.2&quot;&amp;audio=1&amp;session=9542553" poster=""><p class="vjs-no-js">

Change the audio track you can change it:
Exemplo, audio=2 is EN_US when i changed to audio=1 was to PT_BR.

You can made this when press f12 and inspect video element in HTML.

**Comment by hicom150** [comment]
I made and attempt to implement this feature in #1712 hope it can help 😊

**Comment by HugoPB** [comment]
> video id="video-player_html5_api" data-setup="{ "controls": false, "autoplay": false, "preload": "none" }" class="vjs-tech" style="display: block; top: 0px;" preload="none" src="http://127.0.0.1:19575/stream?token=1abd50442a33007521974fb8743f78f5f6bbfd0&amp;localauth=localapi69806fb4f9ca3ff9:&amp;sid=15f043461e1e965c1bb34e4bf912a7485e0af8e4&amp;file=2&amp;ts=28.88181818181818&amp;accept=video/mp4; codecs="avc1.640029, mp4a.40.2"&audio=1&session=9542553" poster=""><p class="vjs-no-js"
> 
> Change the audio track you can change it:
> Exemplo, audio=2 is EN_US when i changed to audio=1 was to PT_BR.
> 
> You can made this when press f12 and inspect video element in HTML.



a simple god
