### ISSUE TITLE
When player is active, other downloads should temporarily stop

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent-desktop#362]
So all download capacity goes to what the user actually wants to see.

**Comment by ungoldman** [comment]
Disagree! At least for me that is not desirable.

**Comment by rom1504** [comment]
Maybe there could be an option in the preferences window https://github.com/feross/webtorrent-desktop/pull/144

**Comment by karloluis** [comment]
Maybe throttle the rest? This really puts more stress on the preferences issue, specially since the goal is to keep it minimal.

**Comment by ungoldman** [comment]
I think a pause all button would be a good feature, would leave the
decision of how to manage downloads and streaming to the user.

**Comment by dcposch** [comment]
I think we can solve this with a global priority for pieces to download, across all active torrents.

While you're streaming, pieces within a few megabytes of where you're currently playing should get top priority. That way, your media should never pause to buffer as long as your internet connection (and the seeders) are fast enough.

Pieces that are far ahead of where you're currently playing can have the same priority as other torrents running in the background.

@feross thoughts? 

@ungoldman to your point, I think this could be more elegant than just pausing all other torrents while one is streaming. At the same time you never want to your video to buffer because other torrents are taking up too much bandwidth

**Comment by feross** [comment]
@dcposch This issue isn't really about piece selection priority as much as throttling. Piece selection priority affects what pieces we ask peers for next. Each torrent currently asks as fast as it can, based on the measured connection speeds, always asking for a little bit more data than the peer is currently sending.

Each torrent object in WebTorrent is isolated. One torrent object doesn't know anything about another. So, to solve this issue correctly, we need to add per-torrent throttling and a notion of torrent priority to WebTorrent.

We can probably devise a balanced solution where priority for the background torrents increases as the foreground torrent builds up a buffer. But this is a non-trivial change. 

In the meantime, I propose we do the right thing for 99% of users, and that is to make sure streaming works reliably.

Steam does this too. When you launch a game, all game downloads pause so the foreground game can use 100% of the available bandwidth.

That model makes sense for WebTorrent too. When the active torrent is not fully downloaded, the full bandwidth should be made available to it. Once it completes, the background torrent downloads can resume. Also, if the torrent is already completed when the playback beings, then background torrent downloading should not be interrupted.

**Comment by Moscarda** [comment]
Agree with those who've said it should be a user-specified preference.  Nobody likes torrent clients taking basic things like handling bandwidth out of the hands of the user.  That said, perhaps something could be done to improve the efficacy of streaking content, for example not all content loads chronologically yet, which hinders smooth streaming.

**Comment by feross** [comment]
@Moscarda Adding user-controlled bandwidth throttling is a planned feature :)

**Comment by ethaniel** [comment]
So here is what happens. When I add a torrent, all files are automatically added for download.
But imagine Battlestar Galactica, with around 100 episodes. I don't want to download them all at once.

So here is an idea: when I add a torrent, only show a list of files. When I click "play" on a file, download only that file. Or the ones that I have marked specifically by clicking a "plus" on the right side of a file name.

Here is how I would expect the torrent to look like when I first add it:
(all the files should be disabled by default)
![image](https://cloud.githubusercontent.com/assets/941973/16220876/bf3c536e-37b9-11e6-910b-ec9df3a34ac0.png)

**Comment by codealchemist** [comment]
I've got something already working on #840 which matches @feross description to satisfy 99% of the users.

Cheers!

**Comment by aug-riedinger** [comment]
I'd say it shall rely on how much buffer is available on the active one, but if little, sounds like it makes sense!

**Comment by bnjmnt4n** [comment]
Closing since #840 was merged. 🎉
