### ISSUE TITLE
accessibility problem with NVDA screen reader

### ISSUE THREAD

**Issue by sine-w** [webtorrent/webtorrent-desktop#439]
Hi,
I would like to have a taste with the software. I try installing the desktop app, yet it is not pretty accessible with [NVDA](https://www.nvaccess.org/)
I cannot access the interface and not knowing what to do with the app.

**Comment by feross** [comment]
@lstar4ever Thank you for raising this issue. I'll investigate what we can do to support NVDA and other screen reading software.

**Comment by lstar4ever** [comment]
Thankyou for your reply!


Feross Aboukhadijeh 於 28/4/2016 19:43 寫道:

**Comment by 47sallo93** [comment]
use that commands
DEBUG=* webtorrent
localStorage.debug = '*'

**Comment by lstar4ever** [comment]
Sorry, what do you mean by use that command?
How to use it???


47sallo93 於 27/5/2016 18:12 寫道:

**Comment by feross** [comment]
@lstar4ever I don't think @47sallo93's advice is relevant.

**Comment by lstar4ever** [comment]
Ok thanks


Feross Aboukhadijeh 於 28/5/2016 7:34 寫道:

**Comment by feross** [comment]
@lstar4ever Have you had a chance to play with a recent version of WebTorrent Desktop? Has the situation improved at all?

I ask you because according to this thread, later versions of Chromium expose a lot more to screen readers: https://github.com/atom/atom/issues/1691

If you could test with WebTorrent Desktop 0.18.0 that would be great!

**Comment by lstar4ever** [comment]
Yes, I tested the version just now.
Well I forgot how it was performing in the previous version, but I could 
say the current one is still have many accessibility problems.
e.g. screen reader may say there are clickable objects, but no more 
information, which not knowing what to do with it.




Feross Aboukhadijeh 於 10/2/2017 7:07 寫道:

**Comment by feross** [comment]
@lstar4ever Can you recommend a free screenreader? I'd like to test how the app behaves with one, but don't know which to use. Ideally it would be free.

**Comment by lstar4ever** [comment]
Oh, the most widely used and free one is NVDA.
download link here:https://www.nvaccess.org/download/



Feross Aboukhadijeh 於 12/2/2017 13:38 寫道:
