### ISSUE TITLE
Subtitles on Chromecast

### ISSUE THREAD

**Issue by mderazon** [webtorrent/webtorrent-desktop#530]
New subtitles feature works _really_ well, thank you very much for that!

You think it's technically possible to have them show in Cast mode, at least for Chromecast ? From what I see the underlying lib should support it, right? (https://github.com/mafintosh/chromecasts#playersubtitlestrack-cb)

**Comment by feross** [comment]
Yep, we can support this.

**Comment by mderazon** [comment]
Started digging a little bit to see if I can implement this easily and found out the following:

1. Only `.vtt` is supported - We'll need to convert srt to vtt
2. Subtitles would have to be loaded up front when the cast initializes and not "hot loaded" while the movie is playing on chromecast - see `play()` doc: https://github.com/mafintosh/chromecasts#playerplayurl-opts-cb. `subtitles()` is only used to switch between active tracks. This means that users will have to first load subtitles and then cast. Not a deal breaker IMO
3. Passing a subtitle file to chromecast through node-castv2-client is not as straight forward as passing a buffer. It expects a file url instead, sitting on a server with CORS enabled. see - https://github.com/thibauts/node-castv2-client/wiki/How-to-use-subtitles-with-the-DefaultMediaReceiver-app. Probably doable, not sure how as i'm not very familiar with Electron. Looks like it has been done before: https://github.com/mafintosh/playback/commit/968b985536cdf7231aaeb14fdd4ddb5e3e3c71c2#diff-168726dbe96b3ce427e7fedce31bb0bcR343

Thoughts?

**Comment by feross** [comment]
1. We already have code to convert `.srt` to `.vtt`. This is pretty straightforward.

2. This is no problem! We have the torrent file list upfront so we can pass all files that are `.vtt` into `player.play()`.

3. We are already running a server using [`torrent.createServer()`](https://github.com/feross/webtorrent/blob/master/docs/api.md#torrentcreateserveropts) that supports CORS. So we can reference any file in the torrent by URL. We can pass the `.vtt` ones directly into `player.play()`, but we'll need to extend the server to convert `.srt` files into `.vtt` on the fly.

**Comment by mderazon** [comment]
> we'll need to extend the server to convert .srt files into .vtt on the fly

Are you talking about extending it from within [webtorrent's server](https://github.com/feross/webtorrent/blob/d62778ed0786818971a72f75be4d4a52494cae83/lib/server.js#L11) ? Or do you have an idea for extending it from [webtorrent-desktop](https://github.com/feross/webtorrent-desktop/blob/master/src/renderer/webtorrent.js#L305) ?
