### ISSUE TITLE
Window doesn't auto-resize after opening torrent in maximized mode

### ISSUE THREAD

**Issue by Goldob** [webtorrent/webtorrent-desktop#648]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

0.7.2

**What operating system and version?**

Windows 10

**What did you do?**

Maximize window. Start the Sintel torrent. Unmaximize window.

**What did you expect to happen?**

The window should resize to fit the video, as when opening torrent on not maximized window.

**What actually happened?**

The window size returned to the original state (like in the home view).

![no-resize](https://cloud.githubusercontent.com/assets/2529619/16166652/593a37f8-34ed-11e6-883e-e8ad20b55293.png)

**Comment by dcposch** [comment]
Yeah, I like that idea: fit-to-video whenever you unmaximize while in the video player.

It will have a side effect that some people might not like: if you manually resize the window while watching a video, then maximize and unmaximize, the window won't return to the same size as before.

I think this is fine, though. You can argue it's a feature. It lets you make the window exactly fit the video again.

**Comment by Goldob** [comment]
That's not exactly what I had in mind. I just didn't want maximize to prevent initial auto-resize on player open.

I like your idea better though. Especially that you made me realize I might need something simlar in #642 - videos within one torrent might have variable aspect-ratio, so there will be a need for auto-resize when changing tracks.

But maybe we could avoid irritating people too much with that feature. How about resizing window only if it doesn't match video dimensions?

**Comment by RedaBousserhane** [comment]
WebTorrent disable auto resize
Help me : reda@kollchi.com
