### ISSUE TITLE
If I scroll into middle of file, it is downloaded sequentially until the end, but then continue downloads from beginning (which is not needed and a waste of traffic)

### ISSUE THREAD

**Issue by ethaniel** [webtorrent/webtorrent-desktop#654]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.7.2

**What operating system and version?**
Mac OS

**What did you do?**
Started playing my video from the middle.

**What did you expect to happen?**
Buffer until the end of the file and then stop completely.

**What actually happened?**
WTD downloaded until the end of the file. And continued downloading from the beginning, which I had no intention of viewing. Thus, wasting my bandwidth.

This is the best viewer I have seen so far. Set up a donation box, so I could throw in some beer money.

**Comment by Goldob** [comment]
See #630

WebTorrent automatically downloads all torrents, except for deselected files. Opening a file in player only proritizes that file, specifically the fragments which are needed on the fly. That's why after the file has loaded until the end, this file, and potentially other files, continues to download.

I agree this might be a waste of bandwidth. Sometimes I just want to stream a torrent and not download anything. Maybe there could be added an option for that in preferences/per-torrent options?

**Comment by feross** [comment]
This is interesting.

I don't want to add another preference. But I do think we could make a conceptual change to how the app works to make streaming the default behavior, to make things more intuitive. The enable/disable button we have now is not very intuitive.

Here's the idea:

- Torrents added to WebTorrent Desktop would be inactive by default. When the user wants to consume a torrent they hit the play button, it becomes active, and starts streaming. The download location is `/tmp`.

- With `/tmp` as the lcoation, the files will stick around until the OS needs to clean them up or disk space is low.

- The torrent remains active for a couple hours after streaming (or until a certain ratio is seeded) to give back to the network. Then it is automatically switched to inactive.

- Users can always remove torrents from WebTorrent Desktop to stop sharing and cleanup files, just like they can now.

- For users who want files to be available offline or want to access them directly in Finder / Windows Explorer, they enable an "Available Offline" switch.
  <img width="176" alt="screen shot 2016-08-04 at 8 00 25 pm" src="https://cloud.githubusercontent.com/assets/121766/17425051/22dc17ba-5a7e-11e6-95ed-7af98041ecd1.png">

- When enabled, the "Available Offline" switch changes the download location to `~/Downloads` (or whatever the user's download folder is) so the files become visible to the user and accessible via Finder / Windows Explorer.

With these changes, the user will care less which torrents are active vs. inactive (which honestly, is already a bit unclear in our interface). Active vs. inactive will be managed automatically most of the time. But, we can also have a right click > "Disable Torrent" and right click > "Enable Torrent" options for those who want to manage everything explicitly.
