### ISSUE TITLE
Modules/plugins etc. environment

### ISSUE THREAD

**Issue by iadj** [webtorrent/webtorrent-desktop#664]
It'd be awesome if for `1.0` there's some sort of an API environment that allows us to easily write modules and plug-ins for `webtorrent-desktop`.

**Comment by dcposch** [comment]
we might consider that after 1.0. for now we're prioritizing reliability, performance, and a minimalist UX

if we had this feature today, what would you use it for?

**Comment by amio** [comment]
Maybe something like #631 , it's better to be a plugin rather than built-in.

**Comment by dcposch** [comment]
#631 is two totally different things. First, the title and description make it sound like it's about live streaming. I think P2P live streaming is a cool idea, but it should be its own separate app.
 
Second, #631 suggests a kind of discovery or feed feature, where you could find new torrents within WebTorrent Desktop. If we ever add that I think it'll just be part of the main app.

As far as I can tell, none of the popular torrent clients have a plugin system: uTorrent, Transmission, etc. And we want to be clean and minimalist compared to those.

**Comment by amio** [comment]
+1 for clean and minimalist
and I mean the second one of #631 😅 

When I imagine the plugin system, I think it might be:

1. Some UI hooks
1. Expose some api

and of course, it should be under a condition that:

1. After 1.0
1. Clean & minimalist

Maybe there's a way to achieve it, anyway, we never thought about a torrent client in the browser while it's true now 😄

**Comment by feross** [comment]
I can see a plugin system being used for things like:

- search
- more casting options
- fancier subtitles

But this is def a post 1.0 feature IMO.
