### ISSUE TITLE
Add "select all" / "deselect all" buttons to torrent file list

### ISSUE THREAD

**Issue by janat08** [webtorrent/webtorrent-desktop#703]
feature don't download all, since there're torrents spanning a couple hundred of files that youd like to be selective about

**Comment by retrohacker** [comment]
It would be nice to have `torrent.select` and `torrent.deselect` exposed through the UI along with manually controlling the priority for each file. Something like:

![wt](https://cloud.githubusercontent.com/assets/1081565/17074690/7b436c50-504c-11e6-8f77-ede753b422cb.png)

Where the priority is a number between 0 and 9, 9 being highest and 0 being lowest.

**Comment by dcposch** [comment]
@retrohacker you can delete + deselect files by clicking (X) to the right. Conversely, if you start streaming a file, that file will get top priority.

I don't think we'll ever have per-file priorities. We want to keep things minimalist.

**Comment by dcposch** [comment]
@janat08 I agree, we should have a better interface for downloading just a few files from a torrent. Currently, the only way to do that is to add the torrent, then click X individually on all the files you don't want

**Comment by thepelkus-too** [comment]
Despite the change in title, I'd like to cast a vote in support of a "select all / deselect all" option. I added it to a local copy of the code and found it useful; would folks be open to taking a look at a PR for it once I clean up the code?

**Comment by feross** [comment]
@thepelkus-too Sure, send the PR!

**Comment by saimadm** [comment]
I added this button in my fork
