### ISSUE TITLE
Allow to select streaming device from the main screen

### ISSUE THREAD

**Issue by luisdavim** [webtorrent/webtorrent-desktop#704]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.8.1 (0.95.2)

**What operating system and version?**
Linux

**What did you expect to happen?**
The application should allow the user to select the destination streaming device before starting to play the video

**What actually happened?**
The user has to start playing the video and from the player screen he can select an alternative streaming device.

**Comment by dcposch** [comment]
This seems reasonable.

We're trying to come up with a good UI to let the user play media in an external player (eg VLC) directly from the torrent list view. We could include cast devices as additional options.

**Comment by feross** [comment]
I think this option (as well as the "Play in VLC..." one) should just be in the right click menu.

Right click:

- Play in VLC
- Play on Chromecast
- Play on Apple TV
- Play on DLNA

But these should only show up if VLC is installed, or a Chromecast is detected on the network
