### ISSUE TITLE
File list tree view

### ISSUE THREAD

**Issue by bluelovers** [webtorrent/webtorrent-desktop#755]
# hope can have this option
1. file tree view for torrent's file list
   for easy choose which file on torrent or more easy choose skip some file
2. use define filter or skip list for torrent file
3. not auto start download torrent
   let user can skip some file before start download
4. download time by current speed
5. open with default system player

**Comment by nilskp** [comment]
Lack of this feature makes it monumentally painful, if not impossible, to select a few files from a large collection.

**Comment by dsernst** [comment]
If I understand this correctly, there are two different feature requests in here: 

(A) group files visually by folder

(B) the ability to uncheck individual files or folders as “Don’t Download”.

Both sound good to me (found this issue by searching for B, after wanting it earlier tonight). 

Just trying to piece out that they are technically separate, nor do I think they necessarily depend upon each other.

**Comment by dsernst** [comment]
Nvm on B, it’s already in there, although I forgot & agree it’s pretty hidden right now.

Quoting Feross from https://github.com/webtorrent/webtorrent-desktop/issues/930#issuecomment-247810453

> We support deselecting certain files from getting downloaded. It might be a bit hidden in the current design. Click a torrent to open the list of files, then click the little X icon on the right side to deselect the file.
