### ISSUE TITLE
video player: current play position and downloaded pieces are not aligned

### ISSUE THREAD

**Issue by allefeld** [webtorrent/webtorrent-desktop#779]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.10.0 (0.96.0)

**What operating system and version?**
Linux 3.16.0 (Debian 8.5)

**What did you do?**
While downloading and playing _Tears of Steel_, I clicked on the "time line" to skip to another part of the video.

**What did you expect to happen?**
I expected new parts of the red indicator for downloaded pieces to appear at and to the right of the indicator for the current play position (white dot).

**What actually happened?**
New parts of the red indicator for downloaded pieces appeared at another place in the time line, to the left.

Screenshot:
![snapshot1](https://cloud.githubusercontent.com/assets/1738353/17670592/06f39706-6313-11e6-9b61-beb6ef766493.png)

**Comment by dcposch** [comment]
@allefeld this is a tricky problem to solve. the mapping between byte offsets in the file and second offsets in the video is something we'd have to extract from the video file, and that varies between video container formats and codecs.

as far as i can tell, the [<audio> and <video>](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement) tags don't give you a way to do that.

--

we might change the red bar to a light grey bar. Youtube uses the red bar for *current playback position*, not for how much of the video has been loaded. i've seen people using the app get confused by that

**Comment by allefeld** [comment]
I understand. But then how does the app determine which pieces to download next if the user skips to a specific time? There must be some kind of translation between the two going on.

One possibility would be to separate the two bars. There is a time line, with a white dot for the current time (and maybe a red bar, YT style), and there is a "download line", at the lower border of the controls, which visualizes downloaded pieces (maybe in grey).

**Comment by dcposch** [comment]
@allefeld the `<video>` tag source points to a local HTTP server. that's a separate process, running webtorrent.js, that translates HTTP range requests to bittorrent requests. so Chrome / the `<video>` tag *does* know how to go from a second offset to a byte offset, but afaik there's no clean way to query that

**Comment by mathiasvr** [comment]
It might be possible to solve this with the [.buffered](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/buffered) property which contains a list of TimeRanges that has been buffered. I'm not sure how precise it is though.

**Comment by allefeld** [comment]
@mathiasvr, yes, or would it be possible to capture in parallel seek commands made to the `<video>` element and the resulting byte range requests to the webserver? This would provide data points that relate time and byte offsets / torrent pieces, and this pointwise information could be extended by intrapolation.

Also, YT manages to show which parts of a video have been buffered, correctly overlayed on the time line. And since it is implemented in HTML5+JS, too, it should be possible to reproduce this here?

But I think just separating the two lines to avoid confusion would suffice already.

**Comment by mathiasvr** [comment]
@allefeld I bet YouTube uses the `buffered` property or the `progress` event. The byte range of the HTTP range request usually starts with a cue offset close to the seek time and ends with the total file length, so I'm not sure this will be useful. However it might be possible to relate the TimeRanges to the available torrent pieces, but sounds a bit overkill to me.

**Comment by allefeld** [comment]
@mathiasvr sounds good, `buffered` it is. :)

**Comment by allefeld** [comment]
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?

I haven't used Webtorrent for a long time, so I don't know if this issue still applies to the current version. I'll close the issue, feel free to reopen.
