### ISSUE TITLE
Preferences should save instantly

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent-desktop#805]
I'm not sure what the whole `state.unsaved` vs. `state.saved` is about.

@dcposch Any ideas?

It creates weird situations where I can change a preference, quit the app without leaving the preferences page first, start the app again, preference was not saved.

Let's just do what every Mac app does and persist settings immediately when they are changed.

**Comment by dcposch** [comment]
Yeah, I agree

**Comment by dcposch** [comment]
Just ran into this. Pretty bad bug actually--makes it looks like the Prefs page is broken when you quit after changing settings

**Comment by dcposch** [comment]
Fixing this will also clean up the code, because we won't have `state.unsaved`
