### ISSUE TITLE
Add support for searching/filtering through torrents

### ISSUE THREAD

**Issue by bnjmnt4n** [webtorrent/webtorrent-desktop#831]
A search/filter bar would be really helpful if there are a large number of torrents.

**Comment by feross** [comment]
@dcposch and I have discussed a "feeds" feature for v2.0, and I think a search bar would fit nicely with that concept. But I think this is too much for v1.0.

**Comment by PfisterFactor** [comment]
I think the [Jackett](https://github.com/Jackett/Jackett) project would be very useful here!
