### ISSUE TITLE
Add "right click" -> "Paste torrent address" option to torrent list

### ISSUE THREAD

**Issue by Shankymahajan** [webtorrent/webtorrent-desktop#834]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.12.0
**What operating system and version?**
Every OS
**What did you do?**
Right click on the main screen of webtorrent

**What did you expect to happen?**
I always expect to be right click option of paste the magnet link 

**What actually happened?**
 *Nothing

I was thinking what is missing in the main screen  . Now I found out it is the right click menu to paste new torrent file or magnet link . 
I always used (Ctrl + v ) to paste the magnet links.

**Comment by dcposch** [comment]
Ctrl+V works for you, right? I think that's fine. You can also drag-and-drop torrent files.

**Comment by dcposch** [comment]
Just to confirm, you're asking for a Paste Magnet Link... option in the right-click menu

**Comment by Shankymahajan** [comment]
yes I'm asking to put a paste button ,Drag and drop and ctrl+v are working

**Comment by feross** [comment]
Reopening as this was never resolved.
