### ISSUE TITLE
Add custom trackers to an existing torrent

### ISSUE THREAD

**Issue by fenilgandhi** [webtorrent/webtorrent-desktop#881]
WebTorrent Version : Version 0.8.1 (0.95.2)

Operating System(s) : Windows 7 (x64) , Windows 8 (x32) , Windows 10 Insider (x64)

Well , this is a feature request . 

I have webtorrent installed on some of my computers and it works perfectly on all of them . 
But some torrents are really bad at finding trackers while other pc's on same network work properly . 
So can you add a feature of adding custom trackers , so we can add appropriate trackers to get proper peers for the streaming. 

Nice work guys ,
Thank You

**Comment by dcposch** [comment]
You can already add your own trackers when creating a new torrent.

If I understand it right, you want to add trackers to existing torrents?

Do other torrent clients, like Transmission and uTorrent, support this?

Do you add custom trackers to each torrent individually, or is there some preference to announce *all* your torrents to a specific list of extra trackers?

**Comment by fanilgandhi** [comment]
Transmission and uTorrent both allow private trackers to be added during the start and even later on . And in my case i only want to add private trackers when the torrent does not have proper peers so that can be found out at a later stage only. 
Also trackers are indiviual for torrents. but having them announce for all your torrents would be a new and    useful feature.

**Comment by feross** [comment]
@fanilgandhi Thanks for the feature request.

Honestly, this seems like a bit of an edge case to me. I know that most torrent apps do support this, but I can't imagine that more than a few percent of our users would ever use a feature that let them modify the trackers used by an individual torrent.

That said, we're currently adding four default webtorrent (ws:// and wss://) trackers to all torrents without making this very clear to users. There is an argument to be made that we should allow users to turn this off (just from a privacy perspective), so we could add a preference called "Global Trackers" that defaults to the four webtorrent trackers, and would also incidentally satisfy this feature request as well.

Thoughts?

**Comment by fanilgandhi** [comment]
Thank You , for providing time for my request. Yes, it definitely it a bit of an edge case but also very useful one . And sometimes we have torrents going on for weeks and you better know how dynamic trackers are . So it could be a nice feature for any user. Also some private high speed torrent sites change their trackers every 48 hours in which case it can be truly great.

Also love your work man , it's very nice .

**Comment by mfurlend** [comment]
Personally, I think this is an important feature to have. Whenever I am downloading a torrent which has very few seeds/peers I will google the hash and add any trackers I find to it.

Great job on the app, btw.

**Comment by jxoesneon** [comment]
I disagree with this being an edge case, while it might not be something used by new users, it is one of the first thing that is suggested whenever you find a very slow torrent, I believe that this and settings for max allowed connections should be implemented to cater to mid to high level torrent users and has the potential to greatly improve the user experience.

**Comment by jamiejackherer** [comment]
I see this has been an open issue for years now.. this is not an edge case i dont think.. its very common and with nearly all other torrent clients you can do this as said previously. surely its not too  much of a difficult thing to do for an experienced node dev....

**Comment by subins2000** [comment]
One usage would be to add trackers to existing torrents from [this list](https://github.com/ngosang/trackerslist).

**Comment by mcnaveen** [comment]
Would be a great feature. :relieved:

**Comment by subins2000** [comment]
#1836 added a new setting for custom global trackers, that partially fixes this issue. But editing tracker list of an existing torrent is a new feature, so this issue should stay up.

One other thing: Last WebTorrent release was in 2020, since a couple of PRs, features got merged we should do a new release?

**Comment by subins2000** [comment]
Discord channel said WebTorrent-desktop doesn't build anymore because many dependencies were bumped by dependabot without proper testing. So yeah making it build will be a step forward.

**Comment by subins2000** [comment]
This is still relevant till a new release is made?

**Comment by red0888** [comment]
Still waiting for custom tracker support
