### ISSUE TITLE
Check for update enhancement

### ISSUE THREAD

**Issue by CragVFX** [webtorrent/webtorrent-desktop#895]
Give the user the ability to check for updates or confirm that they are on the latest version.

Something like below would be nice:
![screen shot 2016-09-04 at 10 52 33 pm](https://cloud.githubusercontent.com/assets/11527278/18236260/5712e7a2-72f2-11e6-88e6-f72fa963b509.png)

**Comment by dcposch** [comment]
Right now, the app only checks for updates on startup. This means you can get out of date if you leave WebTorrent running for days at a time.

I'm not sure we need a button. Instead, what if we checked more often (eg every six hours)? When a new version is downloaded, we could create a desktop notification with a button to restart.

"New version downloaded! WebTorrent Desktop 0.15.0. Click to restart..."

**Comment by feross** [comment]
@dcposch I think that notifications would be a bit annoying and not very informative to users. "What's in version 0.15.0? Why do I care?"

Real-world example: Chrome doesn't notify users about the version they're on, except if they've been running for months without a restart (which is an edge case we can ignore IMO.)

On the other hand, an explicit "check for updates" button would let users who know they're on an older version (they just read a tweet, news article, or got asked by one of us in a GitHub issue to make sure they're on the latest version) force an update check without restarting the app and hoping that it works.

Real-world example: Chrome has a "check for updates" button on their About page.

**Comment by feross** [comment]
> @CragVFX what if we just checked more often, say every six hours?

Checking for updates on more than just startup sounds good. Every 24 or 48 hours sounds good to me.

**Comment by dcposch** [comment]
> Real-world example: Chrome has a "check for updates" button on their About page.

I think that would be fine. I think giving it its own menu item would be too much clutter

**Comment by CragVFX** [comment]
That's a pretty common menu option so I don't think user's would perceive it as clutter.  Other possible option: add it to preferences/ settings instead of OS's menu.

Checking for updates every 24/48 hours like @feross said would also be good.

**Comment by coodoo** [comment]
@dcposch I have `0.13.1` installed, when I launched it seemed it *didn't* notice there's a new `0.14.0` version and upgrade itself, wondering is the auto upgrading thing really working? Thanks!

**Comment by andresgottlieb** [comment]
I had v0.14.0 and and it didn't notice there was a new v0.15.0. I've never been notified of new versions being available and have been using this app (and updating it manually) for months. I'm on Mac OS X El Capitan.

**Comment by dcposch** [comment]
@andresgottlieb you shouldn't have to. Did you install the standard way, via the dmg file?

On Mac and Windows, the app should update itself automatically.

It only pops up a modal dialog saying a new version's available on Linux, where there is no auto updater.

**Comment by dcposch** [comment]
@andresgottlieb @coodoo I just double checked, and it works for me.

1. I installed WebTorrent 0.14.0 from the dmg file.
2. I ran WebTorrent. (Make sure you're running the one that you installed, in Applications, in case you also have a local development copy.) Verify version 0.14 by opening About WebTorrent.
2. I left it open for a bit. Depending on how fast your internet is, it might take a few minutes to download ~40MB update. If you open Dev Tools, you can see "Checking for update", "Update available", and "Update downloaded":

<img width="494" alt="screen shot 2016-09-17 at 8 55 15 am" src="https://cloud.githubusercontent.com/assets/169280/18609358/2b31a1e2-7cb5-11e6-8d2c-6af862b627d4.png">


3. I quit the app entirely--not just closing the window, but Cmd+Q
4. I restarted the app. Open About WebTorrent. Bam, version 0.15

**Comment by feross** [comment]
Yeah, this is a common thing I've seen. I was telling a friend about the newest version of WebTorrent Desktop and he opened it up said "how do I update?" and I said, "Oh, just leave it open for a while then restart it."

@dcposch I think that people just aren't waiting long enough before restarting. Showing a bit more UI around update status on the About window is a good idea IMO:

<img width="248" alt="screen shot 2016-09-17 at 2 57 38 pm" src="https://cloud.githubusercontent.com/assets/121766/18611200/23815e1a-7ce7-11e6-8aea-e622ecb785a5.png">
<img width="395" alt="screen shot 2016-09-17 at 2 57 41 pm" src="https://cloud.githubusercontent.com/assets/121766/18611201/261f5348-7ce7-11e6-8718-2eaec0f2bfd0.png">

**Comment by coodoo** [comment]
@dcposch Thanks for the update, just confirmed it's working and after restarting it's `v0.15.0`, as @feross suggested, some visual hinting would really be nice too 😄

**Comment by sguergachi** [comment]
I was wondering how to update from the app instead of going to the website and checking, especially since this is a beta app I expect updates to happen frequently enough to warrant a UI.
