### ISSUE TITLE
Clicking on Magnet links doesn't do anything after 0.10.0

### ISSUE THREAD

**Issue by djgenesis** [webtorrent/webtorrent-desktop#911]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.11.0 and above
**What operating system and version?**
Windows 10 Pro
**What did you do?**
Click a magnet link in any website.
**What did you expect to happen?**
Open it in Webtorrent Desktop
**What actually happened?**
Nothing

Until version 0.10.0 I clicked on magnet links and it opened just fine. I have tried:
-ALL versions after 0.10.0 -> 11.12.13.13.1 & 14
-All 3 browsers (Firefox, Chrome, MEdge) 
-both without making it the default torrent app and with making it
-3 devices. 2 laptops and a media box. All with windows 10
and none of these combinations opens a magnet link. I am no programmer but since 0.10.0 still works fine clicking on any magnet link I am guessing that there is something going on with 0.11.0 new feature of "New Preference to "Set WebTorrent as default handler for torrents and magnet links"". I am looking through the issues and there is no mention on this. Hey... I cant be the only one :)

Hope you figure this out cause I am stuck to v0.10.0 for ever.

**Comment by djgenesis** [comment]
The only solution I found so far is through Firefox to set the default handler for magnet links inside Firefox settings to Webtorrent Desktop.

**Comment by Goldob** [comment]
This is intentional. Some users found it intrusive for WebTorrent to automatically set itself as default magnet and torrent file handler. Try setting WebTorrent as default torrent app in `Edit > Preferences` menu.  See #771.

**Comment by djgenesis** [comment]
As I mentioned above, I already did. I tried every combination with settings, browsers and WTD versions. Any version above 0.10.0 doesnt grab the magnet links. I have also checked all the issues. Am I the only one with this problem? Strange cause I tried the same things on 2 laptops, 1 tablet and one Media Box all on windows 10. If there is any more info logs etc I can provide, let me know.

**Comment by anonymlol** [comment]
Same issue as #791 I assume.

**Comment by djgenesis** [comment]
Yes. I also confirm that the problem exists in all versions after 0.10.0. Both fresh installs (after uninstallation) and upgrades from previous versions.

**Comment by dcposch** [comment]
@djgenesis thanks for being so thorough. We'll try to fix this in the next release

**Comment by djgenesis** [comment]
Happy to help guys. Keep up the great work.

**Comment by djgenesis** [comment]
Installed v0.15 on one of my laptops and now the problem is fixed on all browsers (Chrome, Edge, Firefox) !!! On Firefox you just need to "unassociate" magnets with webtorrent and then when it asks you what to do, you just have to "reassociate". So the problem was in versions between 0.10 and 0.15. I will try it on all the devices once again to see if all are grabing the magnet links

**Comment by dcposch** [comment]
@djgenesis wow, sweet. I didn't think we had fixed it yet.

There were def other bugfixes in 0.15, so maybe one of them indirectly made the magnet link handler work again.

**Comment by pepjo** [comment]
I'm at 0.16 and still does not work :/
