### ISSUE TITLE
Move torrent data while still seeding

### ISSUE THREAD

**Issue by Shankymahajan** [webtorrent/webtorrent-desktop#917]
After downloading is finished , It is difficult to organise torrent files in my local directory I want to seed even after changing the directory of my torrent files .I think it should be added to every torrent file while downloading or after completing the download .

**Comment by dcposch** [comment]
Do other torrent clients (uTorrent or Transmission) allow you to move an individual torrent's data files and keep seeding?

**Comment by Shankymahajan** [comment]
yes Sir ! uTorrent and qBittorent or any other torrent client has this feature .

**Comment by dcposch** [comment]
Ya I think we can add this before 1.0

**Comment by Kitefr** [comment]
I upvote this.

I lot of torrent clients have a feature to set a directory for incomplete file and to set another one for to move torrent upon completion. The possibility to still seeding after that will be perfect!

**Comment by desci** [comment]
When I remove and add a magnet link, it shows that it's downloading (the UI should say it's checking). There's no easy way for the user to know whether it's downloading all over again or checking the local files.

When you select "move files" from within Transmission's user interface, it asks whether the files are already in the new directory or shall be moved from the current directory to the new. Rtorrent has better inner file moving methods IMO however.

**Comment by paulobrizolara** [comment]
This is the feature that is missing to me.

The app is amazing, but it is bad to have all my torrent (video) files in one directory.

Also, would be amazing if there is an option that allow me to choice where i can save the torrent when i add it.
Firefox, for example, has an option (on preferences) that i can choose the download behaviour (save at some folder or ask me where to save):

![firefox downloads option](https://cloud.githubusercontent.com/assets/1710573/24838561/8a97e932-1d20-11e7-818d-1c7f17987ee1.png)
 
This may be a different (but related) feature. But i think both are complementary.

**Comment by dotnetCarpenter** [comment]
Looks like this was fixed in #1268 but which was closed (rejected) due to developer posting images that could destroy the entire project pretty quickly.
