### ISSUE TITLE
Automatic resize is incorrect on Linux

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent-desktop#927]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

0.15.0

**What operating system and version?**

Ubuntu 16.04 x64

**What did you do?**

Play a video.

**What did you expect to happen?**

Window resizes to the correct size, with no black bars.

**What actually happened?**

<img width="928" alt="screen shot 2016-09-16 at 10 40 33 am" src="https://cloud.githubusercontent.com/assets/121766/18595562/27524736-7bfa-11e6-8c66-5c34c316051f.png">

We fixed a similar issue on Windows recently. Has this issue returned on Windows, as well? Or is this issue just on Ubuntu?

**Comment by demoneaux** [comment]
The automatic resize seems to be working fine on Windows (0.17.0). Don't have a Linux machine so can't test on Linux.

**Comment by luenemam** [comment]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.17.2 (0.97.2) (64-bit)

**What operating system and version?**
Win10 (1607)

**What did you do?**
Play Video (Big Bunny)

**What did you expect to happen?**
Window resize to max display width or height.

**What actually happened?**
Window gets bigger than screen.

![resize-to-big](https://cloud.githubusercontent.com/assets/468949/20339786/98b413d2-abde-11e6-9f08-a891b1eaa32f.png)
