### ISSUE TITLE
Disabled "Show in Folder/Finder" and "Remove Data File" for unstarted torrents

### ISSUE THREAD

**Issue by dcposch** [webtorrent/webtorrent-desktop#936]
**What version of WebTorrent Desktop?** master

**What operating system and version?** all

**What did you do?** Right click one of the default torrents, **before** playing or downloading that torrent. Click Show in Folder.

**What did you expect to happen?** Show in Folder should probably be disabled, since the torrent does not have a data folder and nothing has been downloaded yet.

**What actually happened?** It opens a different, unrelated folder. Looks like this is electron's `showItemInFolder` falling back to some default behavior when the path it's given doesn't exist.

@feross

**Comment by dcposch** [comment]
While we're at it, we should also disable Remove Data File

**Comment by feross** [comment]
Good call.

**Comment by feross** [comment]
> @dcposch It opens a different, unrelated folder.

It looks like this behavior doesn't happen anymore (v0.17.1). Maybe this bug was fixed in an Electron update?

Still we should disable the menu items.
