### ISSUE TITLE
Embed VLC

### ISSUE THREAD

**Issue by bitnom** [webtorrent/webtorrent-desktop#938]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

**What operating system and version?**
0.16.0 (0.97.1) (64 bit)
**What did you do?**
Played video of various formats
**What did you expect to happen?**
Playback within the application even if VLC is required.
**What actually happened?**
VLC is launched independent of webtorrent in a new window.

There's another player called Powder Player which beautifully embeds VLC. It's far better a solution to do that, espcially in support of people who would embed this streamer/player in their application. It can't be that hard. I once managed a software project where VLC was embedded in a Java applet and one of our devs had that done in a day.

This if of course a feature request. I'd like to include this streamer in my upcoming application but this is what's holding me back. Thanks and keep up the good work.

**Comment by feross** [comment]
> embeds VLC. It's far better a solution to do that

This is an approach that @dcposch investigated a while ago. I think he ran into errors and segfaults when WebChimera.js was used to embed VLC. Maybe we can give it another go since it's been a few months? This is one of the last features we need before 1.0!

> I'd like to include this streamer in my upcoming application

Can you elaborate? How do you plan to embed WebTorrent Desktop into your app? Do you mean you plan to use WebTorrent, the library?

**Comment by bmathews** [comment]
One problem I had using webchimera in electron was the rendering performance and cpu usage.

Today I stumbled upon this, which uses chromium's pepper api, which gives a native C plugin raw access to OpenGL rendering. This project uses https://mpv.io for this:

https://github.com/Kagami/boram/blob/c22b3b6cb48bfe3678ba9f63c6249cce295c290c/src/mpv/index.js#L136
https://github.com/Kagami/boram/blob/master/src/mpv/interop.cc

**Comment by albinekb** [comment]
This looks promising: https://github.com/Kagami/mpv.js

**Comment by marcus-sa** [comment]
Any updates on this?

**Comment by ryan4888** [comment]
+1

**Comment by asolopovas** [comment]
+1

**Comment by marcus-sa** [comment]
I did get started on a project which used the libvlcpp, but actually never really got further

https://github.com/venobo/cerberus

**Comment by asolopovas** [comment]
I think its irrelevant we can close it



On 18 Oct 2022, 13:07, at 13:07, "github-actions[bot]" ***@***.***> wrote:
>Is this still relevant? If so, what is blocking it? Is there anything
>you can do to help move it forward?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/webtorrent/webtorrent-desktop/issues/938#issuecomment-1282281230
>You are receiving this because you commented.
>
>Message ID:
***@***.***>
