### ISSUE TITLE
Add ability to automatically start downloads from a folder

### ISSUE THREAD

**Issue by montoulieu** [webtorrent/webtorrent-desktop#953]
Hey guys, been using WebTorrent as my daily driver now, but one feature I miss greatly is the ability to save torrent files to a specific folder and have them automatically start downloading when detected. Any plans to include this?

**Comment by feross** [comment]
This wouldn't be that hard to support, but it's definitely a power user feature, so not a top priority right now.

Our number 1 priority is to get the existing features to be really solid in preparation of the 1.0 release. I'll tag this as 2.0.
