### ISSUE TITLE
Consider switching to Material Design Lite

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent-desktop#977]
This material design library is implemented by Google in plain HTML, CSS, and JavaScript.

https://github.com/google/material-design-lite

Potential pros:
- Lighter-weight, fewer complex dependencies than material-ui
- More explicit, we'll have to create a new react Button component for WD, etc.
- No reliance on material-ui, which is planning huge breaking changes in the next version
- Easier to tweak the style of components, since they doesn't use inline styles like material-ui
  - (Ideally, we can make some classy tweaks to standard material design so WD doesn't feel like a Google product, or an Android app, which is what most associate material design with. We just want it as a starting point, and for consistency)
- Project is run by Google instead of startup company, so more likely to be maintained

Potential cons:
- We have to write React components for everything

Idea: maybe we publish these React components as a separate project so others can benefit from a simpler, lighter-weight alternative to material-ui, based on Google's material-design-lite.

**Comment by mathiasvr** [comment]
I'm not sure mdl would work well with React. Many components have special tags injected and classes added when loaded. Won't React's virtual dom tree interfere with this? I don't know much about React though, so maybe there's a way around this.

**Comment by feross** [comment]
Hm, that's a good point. It might not be easy to use the JS functionality of MDL without reactifying it, which would be a large undertaking.

**Comment by Flet** [comment]
Like this @feross?
https://github.com/tleunen/react-mdl

**Comment by feross** [comment]
@Flet I just gave React-MDL a try. It's still a bit rough around the edges, it seems. It's so unfortunate the state of all these libraries...
