### ISSUE TITLE
Add port forwarding preference

### ISSUE THREAD

**Issue by ZaneCEO** [webtorrent/webtorrent-desktop#986]
I'm looking for WebTorrent Desktop ports informations for port-forwarding on the router.
1. Which TCP ports does it use for communicating with other "standard" BitTorrent clients?
2. Is it possible to change the default ports?
3. Does it use UPnP? if so, can we turn it off?
4. What about WebRTC communications with other non-Desktop WebTorrent clients? which ports are used here?

Thanks!

**Comment by feross** [comment]
> 1. Which TCP ports does it use for communicating with other "standard" BitTorrent clients?

Random port, changed automatically on startup.

> 2. Is it possible to change the default ports?

Underlying `webtorrent` torrent engine support it. Just need to expose a preference.

> 3. Does it use UPnP? if so, can we turn it off?

No UPnP support yet. Once we have that, we'll add a preference.

> 4. What about WebRTC communications with other non-Desktop WebTorrent clients? which ports are used here?

The ports used are different each time, chosen by the WebRTC stack in Chromium. If you want to ensure communication only over a single port, then we'll need another option to disable WebRTRC peers.

---

I'm okay adding a new "Networking" section to the preferences, for these options. But it ought to be hidden by default, like we do today on the Create Torrent page:

<img width="292" alt="screen shot 2016-10-30 at 4 22 50 pm" src="https://cloud.githubusercontent.com/assets/121766/19840866/214f8c96-9ebd-11e6-8926-c3f91c5cdf39.png">

**Comment by alphabt** [comment]
+1 for UPnP support. Right now it's hard to punch through my router without knowing which port WebTorrent is using. If it has UPnP then I don't even have to worry about configuring the router to open ports.

**Comment by erazemk** [comment]
@feross You seem to have knowledge regarding the status of this issue, any news or reasons as to why this can't be added?
